import jsonPb from './index.pb.js'

export const berty = {
	chat: {
		ChatService: jsonPb.lookup('.berty.chat.ChatService'),
		SearchRequest: jsonPb.lookup('.berty.chat.SearchRequest'),
		SearchReply: jsonPb.lookup('.berty.chat.SearchReply'),
		EventSubscribeRequest: jsonPb.lookup('.berty.chat.EventSubscribeRequest'),
		EventSubscribeReply: jsonPb.lookup('.berty.chat.EventSubscribeReply'),
		DevEventSubscribeRequest: jsonPb.lookup('.berty.chat.DevEventSubscribeRequest'),
		DevEventSubscribeReply: jsonPb.lookup('.berty.chat.DevEventSubscribeReply'),
		ConversationListRequest: jsonPb.lookup('.berty.chat.ConversationListRequest'),
		ConversationListReply: jsonPb.lookup('.berty.chat.ConversationListReply'),
		ConversationGetRequest: jsonPb.lookup('.berty.chat.ConversationGetRequest'),
		ConversationCreateRequest: jsonPb.lookup('.berty.chat.ConversationCreateRequest'),
		ConversationCreateReply: jsonPb.lookup('.berty.chat.ConversationCreateReply'),
		ConversationGetReply: jsonPb.lookup('.berty.chat.ConversationGetReply'),
		ConversationUpdateRequest: jsonPb.lookup('.berty.chat.ConversationUpdateRequest'),
		ConversationUpdateReply: jsonPb.lookup('.berty.chat.ConversationUpdateReply'),
		ConversationMuteRequest: jsonPb.lookup('.berty.chat.ConversationMuteRequest'),
		ConversationMuteReply: jsonPb.lookup('.berty.chat.ConversationMuteReply'),
		ConversationLeaveRequest: jsonPb.lookup('.berty.chat.ConversationLeaveRequest'),
		ConversationLeaveReply: jsonPb.lookup('.berty.chat.ConversationLeaveReply'),
		ConversationEraseRequest: jsonPb.lookup('.berty.chat.ConversationEraseRequest'),
		ConversationEraseReply: jsonPb.lookup('.berty.chat.ConversationEraseReply'),
		ConversationInvitationSendRequest: jsonPb.lookup(
			'.berty.chat.ConversationInvitationSendRequest',
		),
		ConversationInvitationSendReply: jsonPb.lookup('.berty.chat.ConversationInvitationSendReply'),
		ConversationInvitationAcceptRequest: jsonPb.lookup(
			'.berty.chat.ConversationInvitationAcceptRequest',
		),
		ConversationInvitationAcceptReply: jsonPb.lookup(
			'.berty.chat.ConversationInvitationAcceptReply',
		),
		ConversationInvitationDeclineRequest: jsonPb.lookup(
			'.berty.chat.ConversationInvitationDeclineRequest',
		),
		ConversationInvitationDeclineReply: jsonPb.lookup(
			'.berty.chat.ConversationInvitationDeclineReply',
		),
		MessageListRequest: jsonPb.lookup('.berty.chat.MessageListRequest'),
		MessageListReply: jsonPb.lookup('.berty.chat.MessageListReply'),
		MessageGetRequest: jsonPb.lookup('.berty.chat.MessageGetRequest'),
		MessageGetReply: jsonPb.lookup('.berty.chat.MessageGetReply'),
		MessageSendRequest: jsonPb.lookup('.berty.chat.MessageSendRequest'),
		MessageSendReply: jsonPb.lookup('.berty.chat.MessageSendReply'),
		MessageEditRequest: jsonPb.lookup('.berty.chat.MessageEditRequest'),
		MessageEditReply: jsonPb.lookup('.berty.chat.MessageEditReply'),
		MessageHideRequest: jsonPb.lookup('.berty.chat.MessageHideRequest'),
		MessageHideReply: jsonPb.lookup('.berty.chat.MessageHideReply'),
		MessageReactRequest: jsonPb.lookup('.berty.chat.MessageReactRequest'),
		MessageReactReply: jsonPb.lookup('.berty.chat.MessageReactReply'),
		MessageReadRequest: jsonPb.lookup('.berty.chat.MessageReadRequest'),
		MessageReadReply: jsonPb.lookup('.berty.chat.MessageReadReply'),
		MemberListRequest: jsonPb.lookup('.berty.chat.MemberListRequest'),
		MemberListReply: jsonPb.lookup('.berty.chat.MemberListReply'),
		MemberGetRequest: jsonPb.lookup('.berty.chat.MemberGetRequest'),
		MemberGetReply: jsonPb.lookup('.berty.chat.MemberGetReply'),
		MemberUpdateRequest: jsonPb.lookup('.berty.chat.MemberUpdateRequest'),
		MemberUpdateReply: jsonPb.lookup('.berty.chat.MemberUpdateReply'),
		ContactListRequest: jsonPb.lookup('.berty.chat.ContactListRequest'),
		ContactListReply: jsonPb.lookup('.berty.chat.ContactListReply'),
		ContactGetRequest: jsonPb.lookup('.berty.chat.ContactGetRequest'),
		ContactGetReply: jsonPb.lookup('.berty.chat.ContactGetReply'),
		ContactBlockRequest: jsonPb.lookup('.berty.chat.ContactBlockRequest'),
		ContactBlockReply: jsonPb.lookup('.berty.chat.ContactBlockReply'),
		ContactRemoveRequest: jsonPb.lookup('.berty.chat.ContactRemoveRequest'),
		ContactRemoveReply: jsonPb.lookup('.berty.chat.ContactRemoveReply'),
		ContactRequestSendRequest: jsonPb.lookup('.berty.chat.ContactRequestSendRequest'),
		ContactRequestSendReply: jsonPb.lookup('.berty.chat.ContactRequestSendReply'),
		ContactRequestAcceptRequest: jsonPb.lookup('.berty.chat.ContactRequestAcceptRequest'),
		ContactRequestAcceptReply: jsonPb.lookup('.berty.chat.ContactRequestAcceptReply'),
		ContactRequestDeclineRequest: jsonPb.lookup('.berty.chat.ContactRequestDeclineRequest'),
		ContactRequestDeclineReply: jsonPb.lookup('.berty.chat.ContactRequestDeclineReply'),
		AccountListRequest: jsonPb.lookup('.berty.chat.AccountListRequest'),
		AccountListReply: jsonPb.lookup('.berty.chat.AccountListReply'),
		AccountGetRequest: jsonPb.lookup('.berty.chat.AccountGetRequest'),
		AccountGetReply: jsonPb.lookup('.berty.chat.AccountGetReply'),
		AccountCreateRequest: jsonPb.lookup('.berty.chat.AccountCreateRequest'),
		AccountCreateReply: jsonPb.lookup('.berty.chat.AccountCreateReply'),
		AccountUpdateRequest: jsonPb.lookup('.berty.chat.AccountUpdateRequest'),
		AccountUpdateReply: jsonPb.lookup('.berty.chat.AccountUpdateReply'),
		AccountOpenRequest: jsonPb.lookup('.berty.chat.AccountOpenRequest'),
		AccountOpenReply: jsonPb.lookup('.berty.chat.AccountOpenReply'),
		AccountCloseRequest: jsonPb.lookup('.berty.chat.AccountCloseRequest'),
		AccountCloseReply: jsonPb.lookup('.berty.chat.AccountCloseReply'),
		AccountRemoveRequest: jsonPb.lookup('.berty.chat.AccountRemoveRequest'),
		AccountRemoveReply: jsonPb.lookup('.berty.chat.AccountRemoveReply'),
		AccountPairingInvitationCreateRequest: jsonPb.lookup(
			'.berty.chat.AccountPairingInvitationCreateRequest',
		),
		AccountPairingInvitationCreateReply: jsonPb.lookup(
			'.berty.chat.AccountPairingInvitationCreateReply',
		),
		AccountRenewIncomingContactRequestLinkRequest: jsonPb.lookup(
			'.berty.chat.AccountRenewIncomingContactRequestLinkRequest',
		),
		AccountRenewIncomingContactRequestLinkReply: jsonPb.lookup(
			'.berty.chat.AccountRenewIncomingContactRequestLinkReply',
		),
	},
	chatmodel: {
		Contact: jsonPb.lookup('.berty.chatmodel.Contact'),
		Device: jsonPb.lookup('.berty.chatmodel.Device'),
		Conversation: jsonPb.lookup('.berty.chatmodel.Conversation'),
		Member: jsonPb.lookup('.berty.chatmodel.Member'),
		Message: jsonPb.lookup('.berty.chatmodel.Message'),
		Attachment: jsonPb.lookup('.berty.chatmodel.Attachment'),
		Reaction: jsonPb.lookup('.berty.chatmodel.Reaction'),
		Account: jsonPb.lookup('.berty.chatmodel.Account'),
	},
}
export const google = {
	api: {
		http: jsonPb.lookup('.google.api.http'),
		Http: jsonPb.lookup('.google.api.Http'),
		HttpRule: jsonPb.lookup('.google.api.HttpRule'),
		CustomHttpPattern: jsonPb.lookup('.google.api.CustomHttpPattern'),
	},
	protobuf: {
		FileDescriptorSet: jsonPb.lookup('.google.protobuf.FileDescriptorSet'),
		FileDescriptorProto: jsonPb.lookup('.google.protobuf.FileDescriptorProto'),
		DescriptorProto: jsonPb.lookup('.google.protobuf.DescriptorProto'),
		ExtensionRangeOptions: jsonPb.lookup('.google.protobuf.ExtensionRangeOptions'),
		FieldDescriptorProto: jsonPb.lookup('.google.protobuf.FieldDescriptorProto'),
		OneofDescriptorProto: jsonPb.lookup('.google.protobuf.OneofDescriptorProto'),
		EnumDescriptorProto: jsonPb.lookup('.google.protobuf.EnumDescriptorProto'),
		EnumValueDescriptorProto: jsonPb.lookup('.google.protobuf.EnumValueDescriptorProto'),
		ServiceDescriptorProto: jsonPb.lookup('.google.protobuf.ServiceDescriptorProto'),
		MethodDescriptorProto: jsonPb.lookup('.google.protobuf.MethodDescriptorProto'),
		FileOptions: jsonPb.lookup('.google.protobuf.FileOptions'),
		MessageOptions: jsonPb.lookup('.google.protobuf.MessageOptions'),
		FieldOptions: jsonPb.lookup('.google.protobuf.FieldOptions'),
		OneofOptions: jsonPb.lookup('.google.protobuf.OneofOptions'),
		EnumOptions: jsonPb.lookup('.google.protobuf.EnumOptions'),
		EnumValueOptions: jsonPb.lookup('.google.protobuf.EnumValueOptions'),
		ServiceOptions: jsonPb.lookup('.google.protobuf.ServiceOptions'),
		MethodOptions: jsonPb.lookup('.google.protobuf.MethodOptions'),
		UninterpretedOption: jsonPb.lookup('.google.protobuf.UninterpretedOption'),
		SourceCodeInfo: jsonPb.lookup('.google.protobuf.SourceCodeInfo'),
		GeneratedCodeInfo: jsonPb.lookup('.google.protobuf.GeneratedCodeInfo'),
		Timestamp: jsonPb.lookup('.google.protobuf.Timestamp'),
	},
}
export const gogoproto = {
	goprotoEnumPrefix: jsonPb.lookup('.gogoproto.goprotoEnumPrefix'),
	goprotoEnumStringer: jsonPb.lookup('.gogoproto.goprotoEnumStringer'),
	enumStringer: jsonPb.lookup('.gogoproto.enumStringer'),
	enumCustomname: jsonPb.lookup('.gogoproto.enumCustomname'),
	enumdecl: jsonPb.lookup('.gogoproto.enumdecl'),
	enumvalueCustomname: jsonPb.lookup('.gogoproto.enumvalueCustomname'),
	goprotoGettersAll: jsonPb.lookup('.gogoproto.goprotoGettersAll'),
	goprotoEnumPrefixAll: jsonPb.lookup('.gogoproto.goprotoEnumPrefixAll'),
	goprotoStringerAll: jsonPb.lookup('.gogoproto.goprotoStringerAll'),
	verboseEqualAll: jsonPb.lookup('.gogoproto.verboseEqualAll'),
	faceAll: jsonPb.lookup('.gogoproto.faceAll'),
	gostringAll: jsonPb.lookup('.gogoproto.gostringAll'),
	populateAll: jsonPb.lookup('.gogoproto.populateAll'),
	stringerAll: jsonPb.lookup('.gogoproto.stringerAll'),
	onlyoneAll: jsonPb.lookup('.gogoproto.onlyoneAll'),
	equalAll: jsonPb.lookup('.gogoproto.equalAll'),
	descriptionAll: jsonPb.lookup('.gogoproto.descriptionAll'),
	testgenAll: jsonPb.lookup('.gogoproto.testgenAll'),
	benchgenAll: jsonPb.lookup('.gogoproto.benchgenAll'),
	marshalerAll: jsonPb.lookup('.gogoproto.marshalerAll'),
	unmarshalerAll: jsonPb.lookup('.gogoproto.unmarshalerAll'),
	stableMarshalerAll: jsonPb.lookup('.gogoproto.stableMarshalerAll'),
	sizerAll: jsonPb.lookup('.gogoproto.sizerAll'),
	goprotoEnumStringerAll: jsonPb.lookup('.gogoproto.goprotoEnumStringerAll'),
	enumStringerAll: jsonPb.lookup('.gogoproto.enumStringerAll'),
	unsafeMarshalerAll: jsonPb.lookup('.gogoproto.unsafeMarshalerAll'),
	unsafeUnmarshalerAll: jsonPb.lookup('.gogoproto.unsafeUnmarshalerAll'),
	goprotoExtensionsMapAll: jsonPb.lookup('.gogoproto.goprotoExtensionsMapAll'),
	goprotoUnrecognizedAll: jsonPb.lookup('.gogoproto.goprotoUnrecognizedAll'),
	gogoprotoImport: jsonPb.lookup('.gogoproto.gogoprotoImport'),
	protosizerAll: jsonPb.lookup('.gogoproto.protosizerAll'),
	compareAll: jsonPb.lookup('.gogoproto.compareAll'),
	typedeclAll: jsonPb.lookup('.gogoproto.typedeclAll'),
	enumdeclAll: jsonPb.lookup('.gogoproto.enumdeclAll'),
	goprotoRegistration: jsonPb.lookup('.gogoproto.goprotoRegistration'),
	messagenameAll: jsonPb.lookup('.gogoproto.messagenameAll'),
	goprotoSizecacheAll: jsonPb.lookup('.gogoproto.goprotoSizecacheAll'),
	goprotoUnkeyedAll: jsonPb.lookup('.gogoproto.goprotoUnkeyedAll'),
	goprotoGetters: jsonPb.lookup('.gogoproto.goprotoGetters'),
	goprotoStringer: jsonPb.lookup('.gogoproto.goprotoStringer'),
	verboseEqual: jsonPb.lookup('.gogoproto.verboseEqual'),
	face: jsonPb.lookup('.gogoproto.face'),
	gostring: jsonPb.lookup('.gogoproto.gostring'),
	populate: jsonPb.lookup('.gogoproto.populate'),
	stringer: jsonPb.lookup('.gogoproto.stringer'),
	onlyone: jsonPb.lookup('.gogoproto.onlyone'),
	equal: jsonPb.lookup('.gogoproto.equal'),
	description: jsonPb.lookup('.gogoproto.description'),
	testgen: jsonPb.lookup('.gogoproto.testgen'),
	benchgen: jsonPb.lookup('.gogoproto.benchgen'),
	marshaler: jsonPb.lookup('.gogoproto.marshaler'),
	unmarshaler: jsonPb.lookup('.gogoproto.unmarshaler'),
	stableMarshaler: jsonPb.lookup('.gogoproto.stableMarshaler'),
	sizer: jsonPb.lookup('.gogoproto.sizer'),
	unsafeMarshaler: jsonPb.lookup('.gogoproto.unsafeMarshaler'),
	unsafeUnmarshaler: jsonPb.lookup('.gogoproto.unsafeUnmarshaler'),
	goprotoExtensionsMap: jsonPb.lookup('.gogoproto.goprotoExtensionsMap'),
	goprotoUnrecognized: jsonPb.lookup('.gogoproto.goprotoUnrecognized'),
	protosizer: jsonPb.lookup('.gogoproto.protosizer'),
	compare: jsonPb.lookup('.gogoproto.compare'),
	typedecl: jsonPb.lookup('.gogoproto.typedecl'),
	messagename: jsonPb.lookup('.gogoproto.messagename'),
	goprotoSizecache: jsonPb.lookup('.gogoproto.goprotoSizecache'),
	goprotoUnkeyed: jsonPb.lookup('.gogoproto.goprotoUnkeyed'),
	nullable: jsonPb.lookup('.gogoproto.nullable'),
	embed: jsonPb.lookup('.gogoproto.embed'),
	customtype: jsonPb.lookup('.gogoproto.customtype'),
	customname: jsonPb.lookup('.gogoproto.customname'),
	jsontag: jsonPb.lookup('.gogoproto.jsontag'),
	moretags: jsonPb.lookup('.gogoproto.moretags'),
	casttype: jsonPb.lookup('.gogoproto.casttype'),
	castkey: jsonPb.lookup('.gogoproto.castkey'),
	castvalue: jsonPb.lookup('.gogoproto.castvalue'),
	stdtime: jsonPb.lookup('.gogoproto.stdtime'),
	stdduration: jsonPb.lookup('.gogoproto.stdduration'),
	wktpointer: jsonPb.lookup('.gogoproto.wktpointer'),
}
