source "https://rubygems.org"

gem "fastlane", "2.145.0"

# Fastlane plugins path
plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
eval_gemfile(plugins_path) if File.exist?(plugins_path)

gem "cocoapods", "~> 1.9.3"
