version: '2'
services:
  berty:
    image: bertychat/berty
    ports:
      - "8700:8700"
      - "4004:4004"
    command: "daemon --log-level=debug --log-namespaces='*' --bind-p2p /ip4/0.0.0.0/tcp/4004 --mdns=false"
