commit_message: "fix: new translations %original_file_name% from Crowdin"
append_commit_message: false

files:
  - source: /js/packages/berty-i18n/locale/en/messages.json
    translation: /js/packages/berty-i18n/locale/%two_letters_code%/%original_file_name%
