linters:
  golint:
    fixer: false
  shellcheck:
    shell: bash
  # eslint:
  #  config: './client/react-native/.eslintrc'
  #  install_plugins: true
  swiftlint: {  }
files:
  ignore:
    - 'bower_components/*'
    - 'node_modules/*'
    - 'vendor/*'
    - '*.gen.*'
fixers:
  enable: true
