codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "1...100"
  status:
    project: no
    patch: no
    changes: no

ignore:
  - "**/*.gen.go"
  - "**/generated.go"
  - "**/*.pb.go"
  - "**/gen/**"
