# get lastest artifact
GET https://circleci.com/api/v1.1/project/github/berty/berty/latest/artifacts?circle-token=4386d7e53001bcc6687ad85d72a32fbfae28afb3&filter=successful

# List builds
GET https://circleci.com/api/v1/project/berty/berty?circle-token=4386d7e53001bcc6687ad85d72a32fbfae28afb3&limit=1&offset=5

GET https://circleci.com/api/v1/recent-builds?circle-token=4386d7e53001bcc6687ad85d72a32fbfae28afb3&limit=100&offset=0
Host: circleci.com
User-Agent: Go-http-client/1.1
Accept: application/json
Content-Type: application/json
Accept-Encoding: gzip
