// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: entity/event.proto

package entity

import (
	fmt "fmt"
	io "io"
	math "math"
	time "time"

	_ "berty.tech/core/api/protobuf/graphql"
	_ "berty.tech/core/pkg/validate"
	_ "github.com/gogo/protobuf/gogoproto"
	github_com_gogo_protobuf_types "github.com/gogo/protobuf/types"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/timestamp"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

//
// enums
//
type Event_Direction int32

const (
	Event_UnknownDirection Event_Direction = 0
	// Incoming is the value for events created by peers, should be set by the receiver when receiving an event.
	Event_Incoming Event_Direction = 1
	// Outgoing is the value for locally-created events, should be set by the sender when creating an event.
	Event_Outgoing Event_Direction = 2
	// Node is the value for local events, see ./core/api/node/kind.proto
	Event_Node Event_Direction = 99
)

var Event_Direction_name = map[int32]string{
	0:  "UnknownDirection",
	1:  "Incoming",
	2:  "Outgoing",
	99: "Node",
}

var Event_Direction_value = map[string]int32{
	"UnknownDirection": 0,
	"Incoming":         1,
	"Outgoing":         2,
	"Node":             99,
}

func (x Event_Direction) String() string {
	return proto.EnumName(Event_Direction_name, int32(x))
}

func (Event_Direction) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a0737e212f090f50, []int{0, 0}
}

type Event struct {
	// ID is a unique ID generated by the event creator.
	// This field is required by gorm.
	ID string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" gorm:"primary_key"`
	// Sender is the ID of the sender.
	// this field is a member of the composite primary key to avoid id collisions.
	SenderID string `protobuf:"bytes,2,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty" gorm:"primary_key"`
	// CreatedAt is set to current date when initializing a new Event object.
	// This field is required by gorm.
	CreatedAt time.Time `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3,stdtime" json:"created_at"`
	// UpdatedAt is set to current date each time the object is updated in database.
	// This field is required by gorm.
	UpdatedAt time.Time `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3,stdtime" json:"updated_at"`
	// SentAt is set to current date just after sending the event.
	SentAt *time.Time `protobuf:"bytes,6,opt,name=sent_at,json=sentAt,proto3,stdtime" json:"sent_at,omitempty"`
	// ReceivedAt is set to current date just after receiving the event.
	ReceivedAt *time.Time `protobuf:"bytes,7,opt,name=received_at,json=receivedAt,proto3,stdtime" json:"received_at,omitempty"`
	// AckedAt is set to current date just after receiving a `Ack` event.
	AckedAt *time.Time `protobuf:"bytes,8,opt,name=acked_at,json=ackedAt,proto3,stdtime" json:"acked_at,omitempty"`
	// Direction is sent to Outgoing by the sender and to Incoming by the receiver.
	Direction Event_Direction `protobuf:"varint,9,opt,name=direction,proto3,enum=berty.entity.Event_Direction" json:"direction,omitempty"`
	// SenderAPIVersion is set by the sender when creating the message to be sent.
	SenderAPIVersion uint32 `protobuf:"varint,10,opt,name=sender_api_version,json=senderApiVersion,proto3" json:"sender_api_version,omitempty"`
	// ReceiverAPIVersion is set by the receiver when receiving a message.
	// this field may be useful to apply local migrations when processing old events stored in db.
	ReceiverAPIVersion uint32 `protobuf:"varint,11,opt,name=receiver_api_version,json=receiverApiVersion,proto3" json:"receiver_api_version,omitempty"`
	// Receiver is the ID of the receiver.
	ReceiverID string `protobuf:"bytes,12,opt,name=receiver_id,json=receiverId,proto3" json:"receiver_id,omitempty"`
	// Kind is an enum defining the event type.
	Kind Kind `protobuf:"varint,13,opt,name=kind,proto3,enum=berty.entity.Kind" json:"kind,omitempty"`
	// Attributes is a nested protobuf message containing per-event-type additional attributes, stored in db.
	Attributes []byte `protobuf:"bytes,14,opt,name=attributes,proto3" json:"attributes,omitempty"`
	// ConversationID needs to be set if the event belongs to a conversation.
	ConversationID string `protobuf:"bytes,15,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	// SeenAt is set to the date when the event has been displayed on the user's screen
	SeenAt *time.Time `protobuf:"bytes,16,opt,name=seen_at,json=seenAt,proto3,stdtime" json:"seen_at,omitempty"`
	// Additional metadata
	Metadata             []*MetadataKeyValue `protobuf:"bytes,99,rep,name=metadata,proto3" json:"metadata,omitempty" gorm:"-"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0737e212f090f50, []int{0}
}
func (m *Event) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Event.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(m, src)
}
func (m *Event) XXX_Size() int {
	return m.Size()
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Event) GetSenderID() string {
	if m != nil {
		return m.SenderID
	}
	return ""
}

func (m *Event) GetCreatedAt() time.Time {
	if m != nil {
		return m.CreatedAt
	}
	return time.Time{}
}

func (m *Event) GetUpdatedAt() time.Time {
	if m != nil {
		return m.UpdatedAt
	}
	return time.Time{}
}

func (m *Event) GetSentAt() *time.Time {
	if m != nil {
		return m.SentAt
	}
	return nil
}

func (m *Event) GetReceivedAt() *time.Time {
	if m != nil {
		return m.ReceivedAt
	}
	return nil
}

func (m *Event) GetAckedAt() *time.Time {
	if m != nil {
		return m.AckedAt
	}
	return nil
}

func (m *Event) GetDirection() Event_Direction {
	if m != nil {
		return m.Direction
	}
	return Event_UnknownDirection
}

func (m *Event) GetSenderAPIVersion() uint32 {
	if m != nil {
		return m.SenderAPIVersion
	}
	return 0
}

func (m *Event) GetReceiverAPIVersion() uint32 {
	if m != nil {
		return m.ReceiverAPIVersion
	}
	return 0
}

func (m *Event) GetReceiverID() string {
	if m != nil {
		return m.ReceiverID
	}
	return ""
}

func (m *Event) GetKind() Kind {
	if m != nil {
		return m.Kind
	}
	return Kind_Unknown
}

func (m *Event) GetAttributes() []byte {
	if m != nil {
		return m.Attributes
	}
	return nil
}

func (m *Event) GetConversationID() string {
	if m != nil {
		return m.ConversationID
	}
	return ""
}

func (m *Event) GetSeenAt() *time.Time {
	if m != nil {
		return m.SeenAt
	}
	return nil
}

func (m *Event) GetMetadata() []*MetadataKeyValue {
	if m != nil {
		return m.Metadata
	}
	return nil
}

type MetadataKeyValue struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Values               []string `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MetadataKeyValue) Reset()         { *m = MetadataKeyValue{} }
func (m *MetadataKeyValue) String() string { return proto.CompactTextString(m) }
func (*MetadataKeyValue) ProtoMessage()    {}
func (*MetadataKeyValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0737e212f090f50, []int{1}
}
func (m *MetadataKeyValue) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MetadataKeyValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MetadataKeyValue.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MetadataKeyValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetadataKeyValue.Merge(m, src)
}
func (m *MetadataKeyValue) XXX_Size() int {
	return m.Size()
}
func (m *MetadataKeyValue) XXX_DiscardUnknown() {
	xxx_messageInfo_MetadataKeyValue.DiscardUnknown(m)
}

var xxx_messageInfo_MetadataKeyValue proto.InternalMessageInfo

func (m *MetadataKeyValue) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *MetadataKeyValue) GetValues() []string {
	if m != nil {
		return m.Values
	}
	return nil
}

func init() {
	proto.RegisterEnum("berty.entity.Event_Direction", Event_Direction_name, Event_Direction_value)
	proto.RegisterType((*Event)(nil), "berty.entity.Event")
	proto.RegisterType((*MetadataKeyValue)(nil), "berty.entity.MetadataKeyValue")
}

func init() { proto.RegisterFile("entity/event.proto", fileDescriptor_a0737e212f090f50) }

var fileDescriptor_a0737e212f090f50 = []byte{
	// 708 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0xcd, 0x6e, 0xd3, 0x4a,
	0x18, 0x8d, 0x93, 0xdc, 0xd4, 0x99, 0xa4, 0xa9, 0xef, 0x28, 0x8a, 0xdc, 0xdc, 0x4b, 0x6c, 0x59,
	0x2c, 0xb2, 0x00, 0x1b, 0x95, 0x15, 0xb0, 0xa8, 0xec, 0x06, 0xd1, 0xa8, 0xe2, 0x47, 0x06, 0xba,
	0x60, 0x13, 0x4d, 0xec, 0xc1, 0x1d, 0x25, 0xb1, 0x8d, 0x33, 0x09, 0xca, 0xba, 0x2f, 0xc0, 0x92,
	0x07, 0xe0, 0x21, 0x78, 0x84, 0x2e, 0x59, 0xb2, 0x32, 0x95, 0xd9, 0xb0, 0xac, 0xfa, 0x04, 0x68,
	0xc6, 0xe3, 0x34, 0x45, 0x42, 0x94, 0x55, 0xc6, 0xe7, 0x7c, 0xe7, 0xcc, 0x9c, 0xf9, 0xbe, 0x09,
	0x80, 0x38, 0xa4, 0x84, 0xae, 0x2c, 0xbc, 0xc4, 0x21, 0x35, 0xe3, 0x24, 0xa2, 0x11, 0x6c, 0x8e,
	0x71, 0x42, 0x57, 0x66, 0xce, 0x74, 0x0d, 0x14, 0x13, 0x8b, 0x13, 0xe3, 0xc5, 0x5b, 0x2b, 0x48,
	0x50, 0x7c, 0xf2, 0x6e, 0x5a, 0xfc, 0xe6, 0x8a, 0xee, 0xbf, 0xc2, 0x65, 0x42, 0x42, 0x5f, 0x40,
	0xed, 0x20, 0x0a, 0x22, 0xbe, 0xb4, 0xd8, 0x4a, 0xa0, 0x5a, 0x10, 0x45, 0xc1, 0x14, 0x5f, 0xf9,
	0x51, 0x32, 0xc3, 0x73, 0x8a, 0x66, 0xb1, 0x28, 0xf8, 0x2f, 0x9e, 0x04, 0xd6, 0x12, 0x4d, 0x89,
	0x8f, 0x28, 0x5e, 0x2f, 0x72, 0xd2, 0xf8, 0x24, 0x83, 0x7f, 0x1e, 0xb3, 0x83, 0xc2, 0x7b, 0xa0,
	0x4c, 0x7c, 0x55, 0xd2, 0xa5, 0x7e, 0xdd, 0xd1, 0xcf, 0x2f, 0x76, 0xa5, 0x2c, 0xd5, 0xca, 0xc3,
	0xc1, 0x65, 0xaa, 0xc1, 0x20, 0x4a, 0x66, 0x0f, 0x8d, 0x38, 0x21, 0x33, 0x94, 0xac, 0x46, 0x13,
	0xbc, 0x32, 0xdc, 0x32, 0xf1, 0xe1, 0x3e, 0xa8, 0xcf, 0x71, 0xe8, 0xe3, 0x64, 0x44, 0x7c, 0xb5,
	0xcc, 0x85, 0x46, 0x96, 0x6a, 0xf2, 0x4b, 0x0e, 0xfe, 0x56, 0x2a, 0xe7, 0xa2, 0xa1, 0x0f, 0x0f,
	0x00, 0xf0, 0x12, 0x8c, 0x28, 0xf6, 0x47, 0x88, 0xaa, 0x15, 0x5d, 0xea, 0x37, 0xf6, 0xba, 0x66,
	0x9e, 0xc7, 0x2c, 0xf2, 0x98, 0xaf, 0x8a, 0x3c, 0x8e, 0x7c, 0x96, 0x6a, 0xa5, 0x0f, 0xdf, 0x34,
	0xc9, 0xad, 0x0b, 0x9d, 0x4d, 0x99, 0xc9, 0x22, 0xf6, 0x0b, 0x93, 0xea, 0xdf, 0x98, 0x08, 0x9d,
	0x4d, 0xe1, 0x03, 0xb0, 0x35, 0xc7, 0x21, 0x65, 0x0e, 0xb5, 0x3f, 0x3a, 0x54, 0xb9, 0xba, 0xc6,
	0x04, 0x36, 0x85, 0x36, 0x68, 0x24, 0xd8, 0xc3, 0x64, 0x99, 0x1f, 0x60, 0xeb, 0x86, 0x72, 0x50,
	0x88, 0x6c, 0x0a, 0x1f, 0x01, 0x19, 0x79, 0x93, 0x5c, 0x2f, 0xdf, 0x50, 0xbf, 0xc5, 0x15, 0x7c,
	0xff, 0xba, 0x4f, 0x12, 0xec, 0x51, 0x12, 0x85, 0x6a, 0x5d, 0x97, 0xfa, 0xad, 0xbd, 0x5b, 0xe6,
	0xe6, 0xb8, 0x99, 0xbc, 0xbf, 0xe6, 0xa0, 0x28, 0x72, 0xaa, 0x5f, 0x4f, 0xbb, 0x25, 0xf7, 0x4a,
	0x05, 0x1d, 0x00, 0x45, 0x23, 0x51, 0x4c, 0x46, 0x4b, 0x9c, 0xcc, 0x99, 0x17, 0xd0, 0xa5, 0xfe,
	0xb6, 0xd3, 0xce, 0x52, 0x4d, 0xc9, 0x3b, 0x6a, 0xbf, 0x18, 0x1e, 0xe7, 0x9c, 0xab, 0xe4, 0xf5,
	0x76, 0x4c, 0x04, 0x02, 0x0f, 0x41, 0x5b, 0x24, 0xba, 0xee, 0xd2, 0xe0, 0x2e, 0x9d, 0x2c, 0xd5,
	0xa0, 0x2b, 0xf8, 0x0d, 0x1f, 0x58, 0x68, 0x36, 0x9c, 0xac, 0xf5, 0x85, 0xf2, 0xc1, 0x6a, 0xf2,
	0xc1, 0x6a, 0x65, 0xa9, 0x06, 0x0a, 0x83, 0xe1, 0x60, 0x7d, 0x7d, 0x6c, 0x8c, 0xee, 0x80, 0x2a,
	0x7b, 0x25, 0xea, 0x36, 0x0f, 0x0f, 0xaf, 0x87, 0x3f, 0x22, 0xa1, 0x2f, 0x12, 0xf3, 0x2a, 0x78,
	0x1b, 0x00, 0x44, 0x69, 0x42, 0xc6, 0x0b, 0x8a, 0xe7, 0x6a, 0x4b, 0x97, 0xfa, 0x4d, 0xa7, 0xfa,
	0xe3, 0x62, 0x57, 0x72, 0x37, 0x70, 0xb8, 0x0f, 0x76, 0xbc, 0x28, 0x64, 0x21, 0x10, 0xbb, 0x22,
	0x76, 0x90, 0x1d, 0x7e, 0x90, 0x8e, 0x78, 0x1a, 0xad, 0x83, 0x0d, 0x7a, 0x38, 0x70, 0x5b, 0x9b,
	0xe5, 0x43, 0x3f, 0x9f, 0x28, 0x1c, 0xb2, 0x96, 0x2a, 0x37, 0x9f, 0x28, 0x1c, 0xda, 0x14, 0x1e,
	0x02, 0x79, 0x86, 0x29, 0xf2, 0x11, 0x45, 0xaa, 0xa7, 0x57, 0xfa, 0x8d, 0xbd, 0xde, 0xf5, 0x4c,
	0x4f, 0x05, 0x7b, 0x84, 0x57, 0xc7, 0x68, 0xba, 0xc0, 0x4e, 0xf3, 0x32, 0xd5, 0xe4, 0xfc, 0xa9,
	0xdd, 0x35, 0xdc, 0xb5, 0xda, 0x78, 0x02, 0xea, 0xeb, 0xb6, 0xc3, 0x36, 0x50, 0x5e, 0x87, 0x93,
	0x30, 0x7a, 0x1f, 0xae, 0x31, 0xa5, 0x04, 0x9b, 0x40, 0x1e, 0x86, 0x5e, 0x34, 0x23, 0x61, 0xa0,
	0x48, 0xec, 0xeb, 0xf9, 0x82, 0x06, 0x11, 0xfb, 0x2a, 0x43, 0x19, 0x54, 0x9f, 0x45, 0x3e, 0x56,
	0x3c, 0xe3, 0x10, 0x28, 0xbf, 0x6e, 0x0a, 0x3b, 0xa0, 0x32, 0xc1, 0x2b, 0xf1, 0x8f, 0x51, 0xfd,
	0x7c, 0xda, 0x95, 0x5c, 0x06, 0xc0, 0xff, 0x41, 0x6d, 0xc9, 0x0a, 0xe6, 0x6a, 0x59, 0xaf, 0x30,
	0xea, 0x8c, 0x51, 0x02, 0x73, 0xfa, 0x67, 0x59, 0x4f, 0xfa, 0x92, 0xf5, 0xa4, 0xf3, 0xac, 0x27,
	0x7d, 0xfc, 0xde, 0x2b, 0xbd, 0xe9, 0xe4, 0xd9, 0x28, 0xf6, 0x4e, 0x2c, 0x2f, 0x4a, 0xb0, 0x95,
	0xa7, 0x1c, 0xd7, 0xf8, 0x45, 0xdd, 0xff, 0x19, 0x00, 0x00, 0xff, 0xff, 0x51, 0xde, 0x1a, 0x72,
	0x50, 0x05, 0x00, 0x00,
}

func (m *Event) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Event) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.ID) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintEvent(dAtA, i, uint64(len(m.ID)))
		i += copy(dAtA[i:], m.ID)
	}
	if len(m.SenderID) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintEvent(dAtA, i, uint64(len(m.SenderID)))
		i += copy(dAtA[i:], m.SenderID)
	}
	dAtA[i] = 0x1a
	i++
	i = encodeVarintEvent(dAtA, i, uint64(github_com_gogo_protobuf_types.SizeOfStdTime(m.CreatedAt)))
	n1, err := github_com_gogo_protobuf_types.StdTimeMarshalTo(m.CreatedAt, dAtA[i:])
	if err != nil {
		return 0, err
	}
	i += n1
	dAtA[i] = 0x22
	i++
	i = encodeVarintEvent(dAtA, i, uint64(github_com_gogo_protobuf_types.SizeOfStdTime(m.UpdatedAt)))
	n2, err := github_com_gogo_protobuf_types.StdTimeMarshalTo(m.UpdatedAt, dAtA[i:])
	if err != nil {
		return 0, err
	}
	i += n2
	if m.SentAt != nil {
		dAtA[i] = 0x32
		i++
		i = encodeVarintEvent(dAtA, i, uint64(github_com_gogo_protobuf_types.SizeOfStdTime(*m.SentAt)))
		n3, err := github_com_gogo_protobuf_types.StdTimeMarshalTo(*m.SentAt, dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n3
	}
	if m.ReceivedAt != nil {
		dAtA[i] = 0x3a
		i++
		i = encodeVarintEvent(dAtA, i, uint64(github_com_gogo_protobuf_types.SizeOfStdTime(*m.ReceivedAt)))
		n4, err := github_com_gogo_protobuf_types.StdTimeMarshalTo(*m.ReceivedAt, dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n4
	}
	if m.AckedAt != nil {
		dAtA[i] = 0x42
		i++
		i = encodeVarintEvent(dAtA, i, uint64(github_com_gogo_protobuf_types.SizeOfStdTime(*m.AckedAt)))
		n5, err := github_com_gogo_protobuf_types.StdTimeMarshalTo(*m.AckedAt, dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n5
	}
	if m.Direction != 0 {
		dAtA[i] = 0x48
		i++
		i = encodeVarintEvent(dAtA, i, uint64(m.Direction))
	}
	if m.SenderAPIVersion != 0 {
		dAtA[i] = 0x50
		i++
		i = encodeVarintEvent(dAtA, i, uint64(m.SenderAPIVersion))
	}
	if m.ReceiverAPIVersion != 0 {
		dAtA[i] = 0x58
		i++
		i = encodeVarintEvent(dAtA, i, uint64(m.ReceiverAPIVersion))
	}
	if len(m.ReceiverID) > 0 {
		dAtA[i] = 0x62
		i++
		i = encodeVarintEvent(dAtA, i, uint64(len(m.ReceiverID)))
		i += copy(dAtA[i:], m.ReceiverID)
	}
	if m.Kind != 0 {
		dAtA[i] = 0x68
		i++
		i = encodeVarintEvent(dAtA, i, uint64(m.Kind))
	}
	if len(m.Attributes) > 0 {
		dAtA[i] = 0x72
		i++
		i = encodeVarintEvent(dAtA, i, uint64(len(m.Attributes)))
		i += copy(dAtA[i:], m.Attributes)
	}
	if len(m.ConversationID) > 0 {
		dAtA[i] = 0x7a
		i++
		i = encodeVarintEvent(dAtA, i, uint64(len(m.ConversationID)))
		i += copy(dAtA[i:], m.ConversationID)
	}
	if m.SeenAt != nil {
		dAtA[i] = 0x82
		i++
		dAtA[i] = 0x1
		i++
		i = encodeVarintEvent(dAtA, i, uint64(github_com_gogo_protobuf_types.SizeOfStdTime(*m.SeenAt)))
		n6, err := github_com_gogo_protobuf_types.StdTimeMarshalTo(*m.SeenAt, dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n6
	}
	if len(m.Metadata) > 0 {
		for _, msg := range m.Metadata {
			dAtA[i] = 0x9a
			i++
			dAtA[i] = 0x6
			i++
			i = encodeVarintEvent(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *MetadataKeyValue) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MetadataKeyValue) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Key) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintEvent(dAtA, i, uint64(len(m.Key)))
		i += copy(dAtA[i:], m.Key)
	}
	if len(m.Values) > 0 {
		for _, s := range m.Values {
			dAtA[i] = 0x12
			i++
			l = len(s)
			for l >= 1<<7 {
				dAtA[i] = uint8(uint64(l)&0x7f | 0x80)
				l >>= 7
				i++
			}
			dAtA[i] = uint8(l)
			i++
			i += copy(dAtA[i:], s)
		}
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func encodeVarintEvent(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *Event) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ID)
	if l > 0 {
		n += 1 + l + sovEvent(uint64(l))
	}
	l = len(m.SenderID)
	if l > 0 {
		n += 1 + l + sovEvent(uint64(l))
	}
	l = github_com_gogo_protobuf_types.SizeOfStdTime(m.CreatedAt)
	n += 1 + l + sovEvent(uint64(l))
	l = github_com_gogo_protobuf_types.SizeOfStdTime(m.UpdatedAt)
	n += 1 + l + sovEvent(uint64(l))
	if m.SentAt != nil {
		l = github_com_gogo_protobuf_types.SizeOfStdTime(*m.SentAt)
		n += 1 + l + sovEvent(uint64(l))
	}
	if m.ReceivedAt != nil {
		l = github_com_gogo_protobuf_types.SizeOfStdTime(*m.ReceivedAt)
		n += 1 + l + sovEvent(uint64(l))
	}
	if m.AckedAt != nil {
		l = github_com_gogo_protobuf_types.SizeOfStdTime(*m.AckedAt)
		n += 1 + l + sovEvent(uint64(l))
	}
	if m.Direction != 0 {
		n += 1 + sovEvent(uint64(m.Direction))
	}
	if m.SenderAPIVersion != 0 {
		n += 1 + sovEvent(uint64(m.SenderAPIVersion))
	}
	if m.ReceiverAPIVersion != 0 {
		n += 1 + sovEvent(uint64(m.ReceiverAPIVersion))
	}
	l = len(m.ReceiverID)
	if l > 0 {
		n += 1 + l + sovEvent(uint64(l))
	}
	if m.Kind != 0 {
		n += 1 + sovEvent(uint64(m.Kind))
	}
	l = len(m.Attributes)
	if l > 0 {
		n += 1 + l + sovEvent(uint64(l))
	}
	l = len(m.ConversationID)
	if l > 0 {
		n += 1 + l + sovEvent(uint64(l))
	}
	if m.SeenAt != nil {
		l = github_com_gogo_protobuf_types.SizeOfStdTime(*m.SeenAt)
		n += 2 + l + sovEvent(uint64(l))
	}
	if len(m.Metadata) > 0 {
		for _, e := range m.Metadata {
			l = e.Size()
			n += 2 + l + sovEvent(uint64(l))
		}
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *MetadataKeyValue) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Key)
	if l > 0 {
		n += 1 + l + sovEvent(uint64(l))
	}
	if len(m.Values) > 0 {
		for _, s := range m.Values {
			l = len(s)
			n += 1 + l + sovEvent(uint64(l))
		}
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovEvent(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozEvent(x uint64) (n int) {
	return sovEvent(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Event) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvent
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Event: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Event: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SenderID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SenderID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatedAt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(&m.CreatedAt, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UpdatedAt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(&m.UpdatedAt, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SentAt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.SentAt == nil {
				m.SentAt = new(time.Time)
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(m.SentAt, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReceivedAt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ReceivedAt == nil {
				m.ReceivedAt = new(time.Time)
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(m.ReceivedAt, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AckedAt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.AckedAt == nil {
				m.AckedAt = new(time.Time)
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(m.AckedAt, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Direction", wireType)
			}
			m.Direction = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Direction |= (Event_Direction(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SenderAPIVersion", wireType)
			}
			m.SenderAPIVersion = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SenderAPIVersion |= (uint32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReceiverAPIVersion", wireType)
			}
			m.ReceiverAPIVersion = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ReceiverAPIVersion |= (uint32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReceiverID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ReceiverID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 13:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Kind", wireType)
			}
			m.Kind = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Kind |= (Kind(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 14:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Attributes", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Attributes = append(m.Attributes[:0], dAtA[iNdEx:postIndex]...)
			if m.Attributes == nil {
				m.Attributes = []byte{}
			}
			iNdEx = postIndex
		case 15:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ConversationID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ConversationID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 16:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SeenAt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.SeenAt == nil {
				m.SeenAt = new(time.Time)
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(m.SeenAt, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 99:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Metadata", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Metadata = append(m.Metadata, &MetadataKeyValue{})
			if err := m.Metadata[len(m.Metadata)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEvent(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthEvent
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MetadataKeyValue) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvent
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MetadataKeyValue: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MetadataKeyValue: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Key", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Key = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Values", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Values = append(m.Values, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEvent(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthEvent
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipEvent(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowEvent
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthEvent
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowEvent
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipEvent(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthEvent = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowEvent   = fmt.Errorf("proto: integer overflow")
)
