#!/bin/bash

STAGED_GO_FILES=$(git diff --cached --name-only | grep "\.go$")

if [[ "$STAGED_GO_FILES" = "" ]]; then
    exit 0
fi
GOPATH=${GOPATH:-$HOME/go}
GOIMPORTS=$GOPATH/bin/goimports
PASS=true

# Check for goimports
if [[ ! -x "$GOIMPORTS" ]]; then
    printf "\t\033[41mPlease install goimports\033[0m (go get golang.org/x/tools/cmd/goimports)\n"
    PASS=false
fi

if ! $PASS; then
    exit 1
fi

PASS=true

for FILE in $STAGED_GO_FILES
do
    # Run goimports on the staged file
    $GOIMPORTS -w $FILE
done

if ! $PASS; then
    printf "\033[0;30m\033[41mCOMMIT FAILED\033[0m\n"
    exit 1
else
    printf "\033[0;30m\033[42mCOMMIT SUCCEEDED\033[0m\n"
fi

exit 0
