export * as mutations from './mutations'
export * as queries from './queries'
export * as subscriptions from './subscriptions'
export * as fragments from './fragments'
export * as enums from './enums.gen'
