steps:
  - label: android-build
    if: build.branch == "master" || (build.message !~ /\[skip android-build\]/ && build.message !~ /\[skip-ci\]/)
    plugins:
      - n0izn0iz/docker#v3.5.4:
          image: bitriseio/android-ndk:v2019_12_28-08_15-b1793
          propagate-uid-gid: true
          workdir: /home/buildkite-agent/go/src/berty.tech/berty
          environment:
            [
              "BUILDKITE=true",
              "GO111MODULE=on",
              "GOPATH=/home/buildkite-agent/go",
              "HOME=/home/buildkite-agent",
              "GRADLE_USER_HOME=/home/buildkite-agent/.gradle",
            ]
          volumes:
            [
              "/usr/local/go:/usr/local/go",
              "~:/home/buildkite-agent",
            ]
    agents:
      queue: "bigcores"
    commands:
      - set -x
      - java -version
