steps:
  - label: go-docker
    if: build.branch == "master" || (build.message !~ /\[skip go-docker\]/ && build.message !~ /\[skip-ci\]/)
    agents:
      queue: "bigcores"
    commands:
      - set -x
      - cd go
      - make docker.build

  - label: go-generate
    if: build.branch == "master" || (build.message !~ /\[skip go-generate\]/ && build.message !~ /\[skip-ci\]/)
    agents:
      queue: "bigcores"
    plugins:
      - n0izn0iz/docker#v3.5.4:
          image: bertytech/protoc:22
          propagate-uid-gid: true
          workdir: /go/src/berty.tech/berty
          environment: ["GO111MODULE=on", "GOPATH=/go"]
          volumes: ["~/go/pkg/mod:/go/pkg/mod"]
    commands:
      - set -x
      - go version
      - find . -name gen.sum -delete
      - cd go
      - time go mod vendor
      - make generate_local
      - make tidy
      - cd ../docs
      - make generate_local
      - cd ..
      - git status | cat
      - git diff -w | cat
      - git diff-index -w --quiet HEAD --

  - label: githooks
    if: build.branch == "master" || (build.message !~ /\[skip githooks\]/ && build.message !~ /\[skip-ci\]/)
    agents:
      queue: "bigcores"
    plugins:
      - n0izn0iz/docker#v3.5.4:
          image: bertytech/githooks:v1
          propagate-uid-gid: true
          workdir: /go/src/berty.tech/berty
          environment: ["GO111MODULE=on", "GOPATH=/go"]
    commands:
      - set -x
      - ./githooks/pre-commit
      - git status | cat
      - git diff -w | cat
      - git diff-index -w --quiet HEAD --

  - label: go-build
    if: build.branch == "master" || (build.message !~ /\[skip go-build\]/ && build.message !~ /\[skip-ci\]/)
    retry:
      automatic:
        limit: 3
    agents:
      queue: "bigcores"
    plugins:
      - n0izn0iz/docker#v3.5.4:
          image: bertytech/build-go:v3
          propagate-uid-gid: true
          workdir: /go/src/berty.tech/berty
          propagate-environment: true
          environment:
            [
              "GO111MODULE=on",
              "GOPATH=/home/buildkite-agent/go",
              "HOME=/home/buildkite-agent",
              "GOSUMDB=off",
              "CODECOV_TOKEN",
            ]
          volumes: ["~:/home/buildkite-agent"]
    commands:
      - set -x

      - go version
      - go mod download
      # https://circleci.com/orbs/registry/orb/gotest/tools#commands-mod-tidy-check
      - go mod tidy -v
      - git --no-pager diff go.mod go.sum
      - git --no-pager diff --quiet go.mod go.sum

      - cd go
      - touch gen.sum # avoid triggering make generate
      - make go.install
      - SKIP_SLOW_TESTS=1 make go.unittest GO_TEST_OPTS="-v -test.timeout=1000s -count 10"
      - SKIP_SLOW_TESTS=0 make go.unittest GO_TEST_OPTS="-v -test.timeout=1000s -count 2"
      - make tidy
      - make lint
      - cd ..
      - codecov -f ./go/coverage.txt

  - label: android-build
    if: build.branch == "master" || (build.message !~ /\[skip android-build\]/ && build.message !~ /\[skip-ci\]/)
    plugins:
      - n0izn0iz/docker#v3.5.4:
          image: bitriseio/android-ndk:v2019_12_28-08_15-b1793
          propagate-uid-gid: true
          workdir: /home/buildkite-agent/go/src/berty.tech/berty
          environment:
            [
              "GO111MODULE=off",
              "GOPATH=/home/buildkite-agent/go",
              "HOME=/home/buildkite-agent",
              "GRADLE_USER_HOME=/home/buildkite-agent/.gradle",
            ]
          volumes: ["~:/home/buildkite-agent"]
    agents:
      queue: "bigcores"
    commands:
      - set -x
      - export PATH=$$PATH:/home/buildkite-agent/go/bin
      - go get golang.org/x/mobile/cmd/gomobile
      - gomobile init
      - cd js
      - make deps.android
      - cd packages/berty-app
      - npx jetify
      - cd android
      - "echo 'android.buildCacheDir=/home/buildkite-agent/.cache/android-build-cache' >> gradle.properties"
      - ./gradlew bundleRelease
      - find . -name '*.aab'
      - "[ -f ~/bundletool-all-0.12.0.jar ] || wget -O ~/bundletool-all-0.12.0.jar https://github.com/google/bundletool/releases/download/0.12.0/bundletool-all-0.12.0.jar"
      - "java -jar ~/bundletool-all-0.12.0.jar build-apks --bundle=./app/build/outputs/bundle/release/app-release.aab --output=./app.apks --mode=universal"
      - unzip ./app.apks
      - find . -name '*.apk'
    artifact_paths:
      - "js/packages/berty-app/android/universal.apk"
      - "js/packages/berty-app/android/toc.pb"
      - "js/packages/berty-app/android/app/build/outputs/bundle/release/app-release.aab"

  - label: ios-build
    if: build.branch == "master" || (build.message !~ /\[skip ios-build\]/ && build.message !~ /\[skip-ci\]/)
    agents:
      queue: "macos"
    plugins:
      - gopath-checkout#v1.0.1:
          import: berty.tech/berty
    commands:
      - set -x
      - export PATH=$$(brew --prefix ruby)/bin:$$PATH # use brew ruby
      - go get golang.org/x/mobile/cmd/gomobile
      - gomobile init
      - cd js
      - make release.ios.staff
      - find . -name '.ipa'
      - find . -name '.app'
    artifact_paths:
      - "js/packages/berty-app/build/**/*"

  - label: js-generate
    if: build.branch == "master" || (build.message !~ /\[skip js-generate\]/ && build.message !~ /\[skip-ci\]/)
    plugins:
      - n0izn0iz/docker#v3.5.4:
          image: bertytech/protoc:22
          propagate-uid-gid: true
          workdir: /go/src/berty.tech/berty
          environment:
            ["GO111MODULE=on", "GOPATH=/go", "HOME=/home/buildkite-agent"]
          volumes: ["~:/home/buildkite-agent", "~/go/pkg/mod:/go/pkg/mod"]
    agents:
      queue: "bigcores"
    commands:
      - set -x
      - cd js
      - make gen.clean
      - make gen
      - cd ..
      - git status | cat
      - git diff -w | cat
      - git diff-index -w --quiet HEAD --

  - label: js-lint
    if: build.branch == "master" || (build.message !~ /\[skip js-lint\]/ && build.message !~ /\[skip-ci\]/)
    plugins:
      - n0izn0iz/docker#v3.5.4:
          image: bertytech/protoc:22
          propagate-uid-gid: true
          workdir: /go/src/berty.tech/berty
          environment:
            ["GO111MODULE=on", "GOPATH=/go", "HOME=/home/buildkite-agent"]
          volumes: ["~:/home/buildkite-agent", "~/go/pkg/mod:/go/pkg/mod"]
    agents:
      queue: "bigcores"
    commands:
      - set -x
      - cd js
      - make lint
      - ./node_modules/.bin/check-deps-sync .

  - label: js-test
    if: build.branch == "master" || (build.message !~ /\[skip js-test\]/ && build.message !~ /\[skip-ci\]/)
    plugins:
      - n0izn0iz/docker#v3.5.4:
          image: bertytech/protoc:22
          propagate-uid-gid: true
          workdir: /go/src/berty.tech/berty
          environment:
            ["GO111MODULE=on", "GOPATH=/go", "HOME=/home/buildkite-agent"]
          volumes: ["~:/home/buildkite-agent", "~/go/pkg/mod:/go/pkg/mod"]
    agents:
      queue: "bigcores"
    commands:
      - set -x
      - cd js
      - make test

  - label: bazel-go
    if: build.branch == "master" || (build.message !~ /\[skip bazel-go\]/ && build.message !~ /\[skip-ci\]/)
    agents:
      queue: "bigcores"
    plugins:
      - n0izn0iz/docker#v3.5.4:
          image: bertytech/bazel:2.0.0-buster-r0
          propagate-uid-gid: true
          workdir: /go/src/berty.tech/berty
          environment:
            [
              "GO111MODULE=on",
              "GOPATH=/home/buildkite-agent/go",
              "HOME=/home/buildkite-agent",
              'BAZEL_CMD_ARGS=--test_output=errors --action_env="GTEST_COLOR=1"',
            ]
          volumes: ["~:/home/buildkite-agent"]
    commands:
      - set -x
      - export USER=$(id -u)
      - bazel --version
      - go version
      - make bazel.unittest
      - make bazel.build
