export default ([
  {
    key: 'afghanistan-93',
    name: 'Afghanistan',
    clean: 'afghanistan',
    code: '93',
    flag: '🇦🇫',
  },
  {
    key: 'aland-islands-358',
    name: 'Åland Islands',
    clean: 'aland islands',
    code: '358',
    flag: '🇦🇽',
  },
  {
    key: 'albania-355',
    name: 'Albania',
    clean: 'albania',
    code: '355',
    flag: '🇦🇱',
  },
  {
    key: 'algeria-213',
    name: 'Algeria',
    clean: 'algeria',
    code: '213',
    flag: '🇩🇿',
  },
  {
    key: 'american-samoa-1684',
    name: 'American Samoa',
    clean: 'american samoa',
    code: '1684',
    flag: '🇦🇸',
  },
  {
    key: 'andorra-376',
    name: 'Andorra',
    clean: 'andorra',
    code: '376',
    flag: '🇦🇩',
  },
  {
    key: 'angola-244',
    name: 'Angola',
    clean: 'angola',
    code: '244',
    flag: '🇦🇴',
  },
  {
    key: 'anguilla-1264',
    name: 'Anguilla',
    clean: 'anguilla',
    code: '1264',
    flag: '🇦🇮',
  },
  {
    key: 'antigua-barbuda-1268',
    name: 'Antigua & Barbuda',
    clean: 'antigua & barbuda',
    code: '1268',
    flag: '🇦🇬',
  },
  {
    key: 'argentina-54',
    name: 'Argentina',
    clean: 'argentina',
    code: '54',
    flag: '🇦🇷',
  },
  {
    key: 'armenia-374',
    name: 'Armenia',
    clean: 'armenia',
    code: '374',
    flag: '🇦🇲',
  },
  {
    key: 'aruba-297',
    name: 'Aruba',
    clean: 'aruba',
    code: '297',
    flag: '🇦🇼',
  },
  {
    key: 'ascension-island-247',
    name: 'Ascension Island',
    clean: 'ascension island',
    code: '247',
    flag: '🇦🇨',
  },
  {
    key: 'australia-61',
    name: 'Australia',
    clean: 'australia',
    code: '61',
    flag: '🇦🇺',
  },
  {
    key: 'austria-43',
    name: 'Austria',
    clean: 'austria',
    code: '43',
    flag: '🇦🇹',
  },
  {
    key: 'azerbaijan-994',
    name: 'Azerbaijan',
    clean: 'azerbaijan',
    code: '994',
    flag: '🇦🇿',
  },
  {
    key: 'bahamas-1242',
    name: 'Bahamas',
    clean: 'bahamas',
    code: '1242',
    flag: '🇧🇸',
  },
  {
    key: 'bahrain-973',
    name: 'Bahrain',
    clean: 'bahrain',
    code: '973',
    flag: '🇧🇭',
  },
  {
    key: 'bangladesh-880',
    name: 'Bangladesh',
    clean: 'bangladesh',
    code: '880',
    flag: '🇧🇩',
  },
  {
    key: 'barbados-1246',
    name: 'Barbados',
    clean: 'barbados',
    code: '1246',
    flag: '🇧🇧',
  },
  {
    key: 'belarus-375',
    name: 'Belarus',
    clean: 'belarus',
    code: '375',
    flag: '🇧🇾',
  },
  {
    key: 'belgium-32',
    name: 'Belgium',
    clean: 'belgium',
    code: '32',
    flag: '🇧🇪',
  },
  {
    key: 'belize-501',
    name: 'Belize',
    clean: 'belize',
    code: '501',
    flag: '🇧🇿',
  },
  {
    key: 'benin-229',
    name: 'Benin',
    clean: 'benin',
    code: '229',
    flag: '🇧🇯',
  },
  {
    key: 'bermuda-1441',
    name: 'Bermuda',
    clean: 'bermuda',
    code: '1441',
    flag: '🇧🇲',
  },
  {
    key: 'bhutan-975',
    name: 'Bhutan',
    clean: 'bhutan',
    code: '975',
    flag: '🇧🇹',
  },
  {
    key: 'bolivia-591',
    name: 'Bolivia',
    clean: 'bolivia',
    code: '591',
    flag: '🇧🇴',
  },
  {
    key: 'bosnia-herzegovina-387',
    name: 'Bosnia & Herzegovina',
    clean: 'bosnia & herzegovina',
    code: '387',
    flag: '🇧🇦',
  },
  {
    key: 'botswana-267',
    name: 'Botswana',
    clean: 'botswana',
    code: '267',
    flag: '🇧🇼',
  },
  {
    key: 'brazil-55',
    name: 'Brazil',
    clean: 'brazil',
    code: '55',
    flag: '🇧🇷',
  },
  {
    key: 'british-indian-ocean-territory-246',
    name: 'British Indian Ocean Territory',
    clean: 'british indian ocean territory',
    code: '246',
    flag: '🇮🇴',
  },
  {
    key: 'british-virgin-islands-1284',
    name: 'British Virgin Islands',
    clean: 'british virgin islands',
    code: '1284',
    flag: '🇻🇬',
  },
  {
    key: 'brunei-673',
    name: 'Brunei',
    clean: 'brunei',
    code: '673',
    flag: '🇧🇳',
  },
  {
    key: 'bulgaria-359',
    name: 'Bulgaria',
    clean: 'bulgaria',
    code: '359',
    flag: '🇧🇬',
  },
  {
    key: 'burkina-faso-226',
    name: 'Burkina Faso',
    clean: 'burkina faso',
    code: '226',
    flag: '🇧🇫',
  },
  {
    key: 'burundi-257',
    name: 'Burundi',
    clean: 'burundi',
    code: '257',
    flag: '🇧🇮',
  },
  {
    key: 'cambodia-855',
    name: 'Cambodia',
    clean: 'cambodia',
    code: '855',
    flag: '🇰🇭',
  },
  {
    key: 'cameroon-237',
    name: 'Cameroon',
    clean: 'cameroon',
    code: '237',
    flag: '🇨🇲',
  },
  {
    key: 'canada-1',
    name: 'Canada',
    clean: 'canada',
    code: '1',
    flag: '🇨🇦',
  },
  {
    key: 'cape-verde-238',
    name: 'Cape Verde',
    clean: 'cape verde',
    code: '238',
    flag: '🇨🇻',
  },
  {
    key: 'caribbean-netherlands-1345',
    name: 'Caribbean Netherlands',
    clean: 'caribbean netherlands',
    code: '1345',
    flag: '🇧🇶',
  },
  {
    key: 'cayman-islands-1345',
    name: 'Cayman Islands',
    clean: 'cayman islands',
    code: '1345',
    flag: '🇰🇾',
  },
  {
    key: 'central-african-republic-236',
    name: 'Central African Republic',
    clean: 'central african republic',
    code: '236',
    flag: '🇨🇫',
  },
  {
    key: 'chad-235',
    name: 'Chad',
    clean: 'chad',
    code: '235',
    flag: '🇹🇩',
  },
  {
    key: 'chile-56',
    name: 'Chile',
    clean: 'chile',
    code: '56',
    flag: '🇨🇱',
  },
  {
    key: 'china-86',
    name: 'China',
    clean: 'china',
    code: '86',
    flag: '🇨🇳',
  },
  {
    key: 'christmas-island-61',
    name: 'Christmas Island',
    clean: 'christmas island',
    code: '61',
    flag: '🇨🇽',
  },
  {
    key: 'cocos-keeling-islands-61',
    name: 'Cocos (Keeling) Islands',
    clean: 'cocos (keeling) islands',
    code: '61',
    flag: '🇨🇨',
  },
  {
    key: 'colombia-57',
    name: 'Colombia',
    clean: 'colombia',
    code: '57',
    flag: '🇨🇴',
  },
  {
    key: 'comoros-269',
    name: 'Comoros',
    clean: 'comoros',
    code: '269',
    flag: '🇰🇲',
  },
  {
    key: 'congo-brazzaville-242',
    name: 'Congo - Brazzaville',
    clean: 'congo - brazzaville',
    code: '242',
    flag: '🇨🇬',
  },
  {
    key: 'congo-kinshasa-243',
    name: 'Congo - Kinshasa',
    clean: 'congo kinshasa',
    code: '243',
    flag: '🇨🇩',
  },
  {
    key: 'cook-islands-682',
    name: 'Cook Islands',
    clean: 'cook islands',
    code: '682',
    flag: '🇨🇰',
  },
  {
    key: 'costa-rica-506',
    name: 'Costa Rica',
    clean: 'costa rica',
    code: '506',
    flag: '🇨🇷',
  },
  {
    key: 'cote-d-ivoire-225',
    name: "Côte d'Ivoire",
    clean: "cote d'ivoire",
    code: '225',
    flag: '🇨🇮',
  },
  {
    key: 'croatia-385',
    name: 'Croatia',
    clean: 'croatia',
    code: '385',
    flag: '🇭🇷',
  },
  {
    key: 'cuba-53',
    name: 'Cuba',
    clean: 'cuba',
    code: '53',
    flag: '🇨🇺',
  },
  {
    key: 'curacao-5999',
    name: 'Curaçao',
    clean: 'curacao',
    code: '5999',
    flag: '🇨🇼',
  },
  {
    key: 'cyprus-357',
    name: 'Cyprus',
    clean: 'cyprus',
    code: '357',
    flag: '🇨🇾',
  },
  {
    key: 'czechia-420',
    name: 'Czechia',
    clean: 'czechia',
    code: '420',
    flag: '🇨🇿',
  },
  {
    key: 'denmark-45',
    name: 'Denmark',
    clean: 'denmark',
    code: '45',
    flag: '🇩🇰',
  },
  {
    key: 'djibouti-253',
    name: 'Djibouti',
    clean: 'djibouti',
    code: '253',
    flag: '🇩🇯',
  },
  {
    key: 'dominica-1767',
    name: 'Dominica',
    clean: 'dominica',
    code: '1767',
    flag: '🇩🇲',
  },
  {
    key: 'dominican-republic-1809',
    name: 'Dominican Republic',
    clean: 'dominican republic',
    code: '1809',
    flag: '🇩🇴',
  },
  {
    key: 'ecuador-593',
    name: 'Ecuador',
    clean: 'ecuador',
    code: '593',
    flag: '🇪🇨',
  },
  {
    key: 'egypt-20',
    name: 'Egypt',
    clean: 'egypt',
    code: '20',
    flag: '🇪🇬',
  },
  {
    key: 'el-salvador-503',
    name: 'El Salvador',
    clean: 'el salvador',
    code: '503',
    flag: '🇸🇻',
  },
  {
    key: 'equatorial-guinea-240',
    name: 'Equatorial Guinea',
    clean: 'equatorial guinea',
    code: '240',
    flag: '🇬🇶',
  },
  {
    key: 'eritrea-291',
    name: 'Eritrea',
    clean: 'eritrea',
    code: '291',
    flag: '🇪🇷',
  },
  {
    key: 'estonia-372',
    name: 'Estonia',
    clean: 'estonia',
    code: '372',
    flag: '🇪🇪',
  },
  {
    key: 'ethiopia-251',
    name: 'Ethiopia',
    clean: 'ethiopia',
    code: '251',
    flag: '🇪🇹',
  },
  {
    key: 'falkland-islands-500',
    name: 'Falkland Islands',
    clean: 'falkland islands',
    code: '500',
    flag: '🇫🇰',
  },
  {
    key: 'faroe-islands-298',
    name: 'Faroe Islands',
    clean: 'faroe islands',
    code: '298',
    flag: '🇫🇴',
  },
  {
    key: 'fiji-679',
    name: 'Fiji',
    clean: 'fiji',
    code: '679',
    flag: '🇫🇯',
  },
  {
    key: 'finland-358',
    name: 'Finland',
    clean: 'finland',
    code: '358',
    flag: '🇫🇮',
  },
  {
    key: 'france-33',
    name: 'France',
    clean: 'france',
    code: '33',
    flag: '🇫🇷',
  },
  {
    key: 'french-guiana-594',
    name: 'French Guiana',
    clean: 'french guiana',
    code: '594',
    flag: '🇬🇫',
  },
  {
    key: 'french-polynesia-689',
    name: 'French Polynesia',
    clean: 'french polynesia',
    code: '689',
    flag: '🇵🇫',
  },
  {
    key: 'gabon-241',
    name: 'Gabon',
    clean: 'gabon',
    code: '241',
    flag: '🇬🇦',
  },
  {
    key: 'gambia-220',
    name: 'Gambia',
    clean: 'gambia',
    code: '220',
    flag: '🇬🇲',
  },
  {
    key: 'georgia-995',
    name: 'Georgia',
    clean: 'georgia',
    code: '995',
    flag: '🇬🇪',
  },
  {
    key: 'germany-49',
    name: 'Germany',
    clean: 'germany',
    code: '49',
    flag: '🇩🇪',
  },
  {
    key: 'ghana-233',
    name: 'Ghana',
    clean: 'ghana',
    code: '233',
    flag: '🇬🇭',
  },
  {
    key: 'gibraltar-350',
    name: 'Gibraltar',
    clean: 'gibraltar',
    code: '350',
    flag: '🇬🇮',
  },
  {
    key: 'greece-30',
    name: 'Greece',
    clean: 'greece',
    code: '30',
    flag: '🇬🇷',
  },
  {
    key: 'greenland-299',
    name: 'Greenland',
    clean: 'greenland',
    code: '299',
    flag: '🇬🇱',
  },
  {
    key: 'grenada-1473',
    name: 'Grenada',
    clean: 'grenada',
    code: '1473',
    flag: '🇬🇩',
  },
  {
    key: 'guadeloupe-590',
    name: 'Guadeloupe',
    clean: 'guadeloupe',
    code: '590',
    flag: '🇬🇵',
  },
  {
    key: 'guam-1671',
    name: 'Guam',
    clean: 'guam',
    code: '1671',
    flag: '🇬🇺',
  },
  {
    key: 'guatemala-502',
    name: 'Guatemala',
    clean: 'guatemala',
    code: '502',
    flag: '🇬🇹',
  },
  {
    key: 'guernsey-44',
    name: 'Guernsey',
    clean: 'guernsey',
    code: '44',
    flag: '🇬🇬',
  },
  {
    key: 'guinea-224',
    name: 'Guinea',
    clean: 'guinea',
    code: '224',
    flag: '🇬🇳',
  },
  {
    key: 'guinea-bissau-245',
    name: 'Guinea-Bissau',
    clean: 'guinea bissau',
    code: '245',
    flag: '🇬🇼',
  },
  {
    key: 'guyana-592',
    name: 'Guyana',
    clean: 'guyana',
    code: '592',
    flag: '🇬🇾',
  },
  {
    key: 'haiti-509',
    name: 'Haiti',
    clean: 'haiti',
    code: '509',
    flag: '🇭🇹',
  },
  {
    key: 'heard-mc-donald-islands-672',
    name: 'Heard & McDonald Islands',
    clean: 'heard & mcdonald islands',
    code: '672',
    flag: '🇭🇲',
  },
  {
    key: 'honduras-504',
    name: 'Honduras',
    clean: 'honduras',
    code: '504',
    flag: '🇭🇳',
  },
  {
    key: 'hong-kong-852',
    name: 'Hong Kong',
    clean: 'hong kong',
    code: '852',
    flag: '🇭🇰',
  },
  {
    key: 'hungary-36',
    name: 'Hungary',
    clean: 'hungary',
    code: '36',
    flag: '🇭🇺',
  },
  {
    key: 'iceland-354',
    name: 'Iceland',
    clean: 'iceland',
    code: '354',
    flag: '🇮🇸',
  },
  {
    key: 'india-91',
    name: 'India',
    clean: 'india',
    code: '91',
    flag: '🇮🇳',
  },
  {
    key: 'indonesia-62',
    name: 'Indonesia',
    clean: 'indonesia',
    code: '62',
    flag: '🇮🇩',
  },
  {
    key: 'iran-98',
    name: 'Iran',
    clean: 'iran',
    code: '98',
    flag: '🇮🇷',
  },
  {
    key: 'iraq-964',
    name: 'Iraq',
    clean: 'iraq',
    code: '964',
    flag: '🇮🇶',
  },
  {
    key: 'ireland-353',
    name: 'Ireland',
    clean: 'ireland',
    code: '353',
    flag: '🇮🇪',
  },
  {
    key: 'isle-of-man-44',
    name: 'Isle of Man',
    clean: 'isle of man',
    code: '44',
    flag: '🇮🇲',
  },
  {
    key: 'israel-972',
    name: 'Israel',
    clean: 'israel',
    code: '972',
    flag: '🇮🇱',
  },
  {
    key: 'italy-39',
    name: 'Italy',
    clean: 'italy',
    code: '39',
    flag: '🇮🇹',
  },
  {
    key: 'jamaica-1876',
    name: 'Jamaica',
    clean: 'jamaica',
    code: '1876',
    flag: '🇯🇲',
  },
  {
    key: 'japan-81',
    name: 'Japan',
    clean: 'japan',
    code: '81',
    flag: '🇯🇵',
  },
  {
    key: 'jersey-44',
    name: 'Jersey',
    clean: 'jersey',
    code: '44',
    flag: '🇯🇪',
  },
  {
    key: 'jordan-962',
    name: 'Jordan',
    clean: 'jordan',
    code: '962',
    flag: '🇯🇴',
  },
  {
    key: 'kazakhstan-76',
    name: 'Kazakhstan',
    clean: 'kazakhstan',
    code: '76',
    flag: '🇰🇿',
  },
  {
    key: 'kenya-254',
    name: 'Kenya',
    clean: 'kenya',
    code: '254',
    flag: '🇰🇪',
  },
  {
    key: 'kiribati-686',
    name: 'Kiribati',
    clean: 'kiribati',
    code: '686',
    flag: '🇰🇮',
  },
  {
    key: 'kosovo-377',
    name: 'Kosovo',
    clean: 'kosovo',
    code: '377',
    flag: '🇽🇰',
  },
  {
    key: 'kosovo-381',
    name: 'Kosovo',
    clean: 'kosovo',
    code: '381',
    flag: '🇽🇰',
  },
  {
    key: 'kosovo-386',
    name: 'Kosovo',
    clean: 'kosovo',
    code: '386',
    flag: '🇽🇰',
  },
  {
    key: 'kuwait-965',
    name: 'Kuwait',
    clean: 'kuwait',
    code: '965',
    flag: '🇰🇼',
  },
  {
    key: 'kyrgyzstan-996',
    name: 'Kyrgyzstan',
    clean: 'kyrgyzstan',
    code: '996',
    flag: '🇰🇬',
  },
  {
    key: 'laos-856',
    name: 'Laos',
    clean: 'laos',
    code: '856',
    flag: '🇱🇦',
  },
  {
    key: 'latvia-371',
    name: 'Latvia',
    clean: 'latvia',
    code: '371',
    flag: '🇱🇻',
  },
  {
    key: 'lebanon-961',
    name: 'Lebanon',
    clean: 'lebanon',
    code: '961',
    flag: '🇱🇧',
  },
  {
    key: 'lesotho-266',
    name: 'Lesotho',
    clean: 'lesotho',
    code: '266',
    flag: '🇱🇸',
  },
  {
    key: 'liberia-231',
    name: 'Liberia',
    clean: 'liberia',
    code: '231',
    flag: '🇱🇷',
  },
  {
    key: 'libya-218',
    name: 'Libya',
    clean: 'libya',
    code: '218',
    flag: '🇱🇾',
  },
  {
    key: 'liechtenstein-423',
    name: 'Liechtenstein',
    clean: 'liechtenstein',
    code: '423',
    flag: '🇱🇮',
  },
  {
    key: 'lithuania-370',
    name: 'Lithuania',
    clean: 'lithuania',
    code: '370',
    flag: '🇱🇹',
  },
  {
    key: 'luxembourg-352',
    name: 'Luxembourg',
    clean: 'luxembourg',
    code: '352',
    flag: '🇱🇺',
  },
  {
    key: 'macau-china-853',
    name: 'Macau (China)',
    clean: 'macau (china)',
    code: '853',
    flag: '🇲🇴',
  },
  {
    key: 'macedonia-389',
    name: 'Macedonia',
    clean: 'macedonia',
    code: '389',
    flag: '🇲🇰',
  },
  {
    key: 'madagascar-261',
    name: 'Madagascar',
    clean: 'madagascar',
    code: '261',
    flag: '🇲🇬',
  },
  {
    key: 'malawi-265',
    name: 'Malawi',
    clean: 'malawi',
    code: '265',
    flag: '🇲🇼',
  },
  {
    key: 'malaysia-60',
    name: 'Malaysia',
    clean: 'malaysia',
    code: '60',
    flag: '🇲🇾',
  },
  {
    key: 'maldives-960',
    name: 'Maldives',
    clean: 'maldives',
    code: '960',
    flag: '🇲🇻',
  },
  {
    key: 'mali-223',
    name: 'Mali',
    clean: 'mali',
    code: '223',
    flag: '🇲🇱',
  },
  {
    key: 'malta-356',
    name: 'Malta',
    clean: 'malta',
    code: '356',
    flag: '🇲🇹',
  },
  {
    key: 'marshall-islands-692',
    name: 'Marshall Islands',
    clean: 'marshall islands',
    code: '692',
    flag: '🇲🇭',
  },
  {
    key: 'martinique-596',
    name: 'Martinique',
    clean: 'martinique',
    code: '596',
    flag: '🇲🇶',
  },
  {
    key: 'mauritania-222',
    name: 'Mauritania',
    clean: 'mauritania',
    code: '222',
    flag: '🇲🇷',
  },
  {
    key: 'mauritius-230',
    name: 'Mauritius',
    clean: 'mauritius',
    code: '230',
    flag: '🇲🇺',
  },
  {
    key: 'mayotte-262',
    name: 'Mayotte',
    clean: 'mayotte',
    code: '262',
    flag: '🇾🇹',
  },
  {
    key: 'mexico-52',
    name: 'Mexico',
    clean: 'mexico',
    code: '52',
    flag: '🇲🇽',
  },
  {
    key: 'micronesia-691',
    name: 'Micronesia',
    clean: 'micronesia',
    code: '691',
    flag: '🇫🇲',
  },
  {
    key: 'moldova-373',
    name: 'Moldova',
    clean: 'moldova',
    code: '373',
    flag: '🇲🇩',
  },
  {
    key: 'monaco-377',
    name: 'Monaco',
    clean: 'monaco',
    code: '377',
    flag: '🇲🇨',
  },
  {
    key: 'mongolia-976',
    name: 'Mongolia',
    clean: 'mongolia',
    code: '976',
    flag: '🇲🇳',
  },
  {
    key: 'montenegro-382',
    name: 'Montenegro',
    clean: 'montenegro',
    code: '382',
    flag: '🇲🇪',
  },
  {
    key: 'montserrat-1664',
    name: 'Montserrat',
    clean: 'montserrat',
    code: '1664',
    flag: '🇲🇸',
  },
  {
    key: 'morocco-212',
    name: 'Morocco',
    clean: 'morocco',
    code: '212',
    flag: '🇲🇦',
  },
  {
    key: 'mozambique-258',
    name: 'Mozambique',
    clean: 'mozambique',
    code: '258',
    flag: '🇲🇿',
  },
  {
    key: 'myanmar-burma-95',
    name: 'Myanmar (Burma)',
    clean: 'myanmar (burma)',
    code: '95',
    flag: '🇲🇲',
  },
  {
    key: 'namibia-264',
    name: 'Namibia',
    clean: 'namibia',
    code: '264',
    flag: '🇳🇦',
  },
  {
    key: 'nauru-674',
    name: 'Nauru',
    clean: 'nauru',
    code: '674',
    flag: '🇳🇷',
  },
  {
    key: 'nepal-977',
    name: 'Nepal',
    clean: 'nepal',
    code: '977',
    flag: '🇳🇵',
  },
  {
    key: 'netherlands-31',
    name: 'Netherlands',
    clean: 'netherlands',
    code: '31',
    flag: '🇳🇱',
  },
  {
    key: 'new-caledonia-687',
    name: 'New Caledonia',
    clean: 'new caledonia',
    code: '687',
    flag: '🇳🇨',
  },
  {
    key: 'new-zealand-64',
    name: 'New Zealand',
    clean: 'new zealand',
    code: '64',
    flag: '🇳🇿',
  },
  {
    key: 'nicaragua-505',
    name: 'Nicaragua',
    clean: 'nicaragua',
    code: '505',
    flag: '🇳🇮',
  },
  {
    key: 'niger-227',
    name: 'Niger',
    clean: 'niger',
    code: '227',
    flag: '🇳🇪',
  },
  {
    key: 'nigeria-234',
    name: 'Nigeria',
    clean: 'nigeria',
    code: '234',
    flag: '🇳🇬',
  },
  {
    key: 'niue-683',
    name: 'Niue',
    clean: 'niue',
    code: '683',
    flag: '🇳🇺',
  },
  {
    key: 'norfolk-island-672',
    name: 'Norfolk Island',
    clean: 'norfolk island',
    code: '672',
    flag: '🇳🇫',
  },
  {
    key: 'north-korea-850',
    name: 'North Korea',
    clean: 'north korea',
    code: '850',
    flag: '🇰🇵',
  },
  {
    key: 'northern-mariana-islands-1670',
    name: 'Northern Mariana Islands',
    clean: 'northern mariana islands',
    code: '1670',
    flag: '🇲🇵',
  },
  {
    key: 'norway-47',
    name: 'Norway',
    clean: 'norway',
    code: '47',
    flag: '🇳🇴',
  },
  {
    key: 'oman-968',
    name: 'Oman',
    clean: 'oman',
    code: '968',
    flag: '🇴🇲',
  },
  {
    key: 'pakistan-92',
    name: 'Pakistan',
    clean: 'pakistan',
    code: '92',
    flag: '🇵🇰',
  },
  {
    key: 'palau-680',
    name: 'Palau',
    clean: 'palau',
    code: '680',
    flag: '🇵🇼',
  },
  {
    key: 'palestinian-territories-970',
    name: 'Palestinian Territories',
    clean: 'palestinian territories',
    code: '970',
    flag: '🇵🇸',
  },
  {
    key: 'panama-507',
    name: 'Panama',
    clean: 'panama',
    code: '507',
    flag: '🇵🇦',
  },
  {
    key: 'papua-new-guinea-675',
    name: 'Papua New Guinea',
    clean: 'papua new guinea',
    code: '675',
    flag: '🇵🇬',
  },
  {
    key: 'paraguay-595',
    name: 'Paraguay',
    clean: 'paraguay',
    code: '595',
    flag: '🇵🇾',
  },
  {
    key: 'peru-51',
    name: 'Peru',
    clean: 'peru',
    code: '51',
    flag: '🇵🇪',
  },
  {
    key: 'philippines-63',
    name: 'Philippines',
    clean: 'philippines',
    code: '63',
    flag: '🇵🇭',
  },
  {
    key: 'poland-48',
    name: 'Poland',
    clean: 'poland',
    code: '48',
    flag: '🇵🇱',
  },
  {
    key: 'portugal-351',
    name: 'Portugal',
    clean: 'portugal',
    code: '351',
    flag: '🇵🇹',
  },
  {
    key: 'puerto-rico-1787',
    name: 'Puerto Rico',
    clean: 'puerto rico',
    code: '1787',
    flag: '🇵🇷',
  },
  {
    key: 'qatar-974',
    name: 'Qatar',
    clean: 'qatar',
    code: '974',
    flag: '🇶🇦',
  },
  {
    key: 'reunion-262',
    name: 'Réunion',
    clean: 'reunion',
    code: '262',
    flag: '🇷🇪',
  },
  {
    key: 'romania-40',
    name: 'Romania',
    clean: 'romania',
    code: '40',
    flag: '🇷🇴',
  },
  {
    key: 'russia-7',
    name: 'Russia',
    clean: 'russia',
    code: '7',
    flag: '🇷🇺',
  },
  {
    key: 'rwanda-250',
    name: 'Rwanda',
    clean: 'rwanda',
    code: '250',
    flag: '🇷🇼',
  },
  {
    key: 'samoa-685',
    name: 'Samoa',
    clean: 'samoa',
    code: '685',
    flag: '🇼🇸',
  },
  {
    key: 'san-marino-378',
    name: 'San Marino',
    clean: 'san marino',
    code: '378',
    flag: '🇸🇲',
  },
  {
    key: 'sao-tome-principe-239',
    name: 'São Tomé & Príncipe',
    clean: 'sao tome principe',
    code: '239',
    flag: '🇸🇹',
  },
  {
    key: 'saudi-arabia-966',
    name: 'Saudi Arabia',
    clean: 'saudi arabia',
    code: '966',
    flag: '🇸🇦',
  },
  {
    key: 'senegal-221',
    name: 'Senegal',
    clean: 'senegal',
    code: '221',
    flag: '🇸🇳',
  },
  {
    key: 'serbia-381',
    name: 'Serbia',
    clean: 'serbia',
    code: '381',
    flag: '🇷🇸',
  },
  {
    key: 'seychelles-248',
    name: 'Seychelles',
    clean: 'seychelles',
    code: '248',
    flag: '🇸🇨',
  },
  {
    key: 'sierra-leone-232',
    name: 'Sierra Leone',
    clean: 'sierra leone',
    code: '232',
    flag: '🇸🇱',
  },
  {
    key: 'singapore-65',
    name: 'Singapore',
    clean: 'singapore',
    code: '65',
    flag: '🇸🇬',
  },
  {
    key: 'sint-maarten-1721',
    name: 'Sint Maarten',
    clean: 'sint maarten',
    code: '1721',
    flag: '🇸🇽',
  },
  {
    key: 'slovakia-421',
    name: 'Slovakia',
    clean: 'slovakia',
    code: '421',
    flag: '🇸🇰',
  },
  {
    key: 'slovenia-386',
    name: 'Slovenia',
    clean: 'slovenia',
    code: '386',
    flag: '🇸🇮',
  },
  {
    key: 'so-georgia-so-sandwich-isl-500',
    name: 'So. Georgia & So. Sandwich Isl.',
    clean: 'so. georgia & so. sandwich isl.',
    code: '500',
    flag: '🇬🇸',
  },
  {
    key: 'solomon-islands-677',
    name: 'Solomon Islands',
    clean: 'solomon islands',
    code: '677',
    flag: '🇸🇧',
  },
  {
    key: 'somalia-252',
    name: 'Somalia',
    clean: 'somalia',
    code: '252',
    flag: '🇸🇴',
  },
  {
    key: 'south-africa-27',
    name: 'South Africa',
    clean: 'south africa',
    code: '27',
    flag: '🇿🇦',
  },
  {
    key: 'south-korea-82',
    name: 'South Korea',
    clean: 'south korea',
    code: '82',
    flag: '🇰🇷',
  },
  {
    key: 'south-sudan-211',
    name: 'South Sudan',
    clean: 'south sudan',
    code: '211',
    flag: '🇸🇸',
  },
  {
    key: 'spain-34',
    name: 'Spain',
    clean: 'spain',
    code: '34',
    flag: '🇪🇸',
  },
  {
    key: 'sri-lanka-94',
    name: 'Sri Lanka',
    clean: 'sri lanka',
    code: '94',
    flag: '🇱🇰',
  },
  {
    key: 'st-barthelemy-590',
    name: 'St. Barthélemy',
    clean: 'st. barthelemy',
    code: '590',
    flag: '🇧🇱',
  },
  {
    key: 'st-helena-290',
    name: 'St. Helena',
    clean: 'st. helena',
    code: '290',
    flag: '🇸🇭',
  },
  {
    key: 'st-kitts-nevis-1869',
    name: 'St. Kitts & Nevis',
    clean: 'st. kitts & nevis',
    code: '1869',
    flag: '🇰🇳',
  },
  {
    key: 'st-lucia-1758',
    name: 'St. Lucia',
    clean: 'st. lucia',
    code: '1758',
    flag: '🇱🇨',
  },
  {
    key: 'st-martin-590',
    name: 'St. Martin',
    clean: 'st. martin',
    code: '590',
    flag: '🇲🇫',
  },
  {
    key: 'st-pierre-miquelon-508',
    name: 'St. Pierre & Miquelon',
    clean: 'st. pierre & miquelon',
    code: '508',
    flag: '🇵🇲',
  },
  {
    key: 'st-vincent-grenadines-1784',
    name: 'St. Vincent & Grenadines',
    clean: 'st. vincent & grenadines',
    code: '1784',
    flag: '🇻🇨',
  },
  {
    key: 'sudan-249',
    name: 'Sudan',
    clean: 'sudan',
    code: '249',
    flag: '🇸🇩',
  },
  {
    key: 'suriname-597',
    name: 'Suriname',
    clean: 'suriname',
    code: '597',
    flag: '🇸🇷',
  },
  {
    key: 'svalbard-jan-mayen-4779',
    name: 'Svalbard & Jan Mayen',
    clean: 'svalbard & jan mayen',
    code: '4779',
    flag: '🇸🇯',
  },
  {
    key: 'swaziland-268',
    name: 'Swaziland',
    clean: 'swaziland',
    code: '268',
    flag: '🇸🇿',
  },
  {
    key: 'sweden-46',
    name: 'Sweden',
    clean: 'sweden',
    code: '46',
    flag: '🇸🇪',
  },
  {
    key: 'switzerland-41',
    name: 'Switzerland',
    clean: 'switzerland',
    code: '41',
    flag: '🇨🇭',
  },
  {
    key: 'syria-963',
    name: 'Syria',
    clean: 'syria',
    code: '963',
    flag: '🇸🇾',
  },
  {
    key: 'taiwan-886',
    name: 'Taiwan',
    clean: 'taiwan',
    code: '886',
    flag: '🇹🇼',
  },
  {
    key: 'tajikistan-992',
    name: 'Tajikistan',
    clean: 'tajikistan',
    code: '992',
    flag: '🇹🇯',
  },
  {
    key: 'tanzania-255',
    name: 'Tanzania',
    clean: 'tanzania',
    code: '255',
    flag: '🇹🇿',
  },
  {
    key: 'thailand-66',
    name: 'Thailand',
    clean: 'thailand',
    code: '66',
    flag: '🇹🇭',
  },
  {
    key: 'timor-leste-670',
    name: 'Timor-Leste',
    clean: 'timor leste',
    code: '670',
    flag: '🇹🇱',
  },
  {
    key: 'togo-228',
    name: 'Togo',
    clean: 'togo',
    code: '228',
    flag: '🇹🇬',
  },
  {
    key: 'tokelau-690',
    name: 'Tokelau',
    clean: 'tokelau',
    code: '690',
    flag: '🇹🇰',
  },
  {
    key: 'tonga-676',
    name: 'Tonga',
    clean: 'tonga',
    code: '676',
    flag: '🇹🇴',
  },
  {
    key: 'trinidad-tobago-1868',
    name: 'Trinidad & Tobago',
    clean: 'trinidad & tobago',
    code: '1868',
    flag: '🇹🇹',
  },
  {
    key: 'tunisia-216',
    name: 'Tunisia',
    clean: 'tunisia',
    code: '216',
    flag: '🇹🇳',
  },
  {
    key: 'turkey-90',
    name: 'Turkey',
    clean: 'turkey',
    code: '90',
    flag: '🇹🇷',
  },
  {
    key: 'turkmenistan-993',
    name: 'Turkmenistan',
    clean: 'turkmenistan',
    code: '993',
    flag: '🇹🇲',
  },
  {
    key: 'turks-caicos-islands-1649',
    name: 'Turks & Caicos Islands',
    clean: 'turks & caicos islands',
    code: '1649',
    flag: '🇹🇨',
  },
  {
    key: 'tuvalu-688',
    name: 'Tuvalu',
    clean: 'tuvalu',
    code: '688',
    flag: '🇹🇻',
  },
  {
    key: 'u-s-virgin-islands-1340',
    name: 'U.S. Virgin Islands',
    clean: 'u.s. virgin islands',
    code: '1340',
    flag: '🇻🇮',
  },
  {
    key: 'uganda-256',
    name: 'Uganda',
    clean: 'uganda',
    code: '256',
    flag: '🇺🇬',
  },
  {
    key: 'ukraine-380',
    name: 'Ukraine',
    clean: 'ukraine',
    code: '380',
    flag: '🇺🇦',
  },
  {
    key: 'united-arab-emirates-971',
    name: 'United Arab Emirates',
    clean: 'united arab emirates',
    code: '971',
    flag: '🇦🇪',
  },
  {
    key: 'united-kingdom-44',
    name: 'United Kingdom',
    clean: 'united kingdom',
    code: '44',
    flag: '🇬🇧',
  },
  {
    key: 'united-states-1',
    name: 'United States',
    clean: 'united states',
    code: '1',
    flag: '🇺🇸',
  },
  {
    key: 'uruguay-598',
    name: 'Uruguay',
    clean: 'uruguay',
    code: '598',
    flag: '🇺🇾',
  },
  {
    key: 'uzbekistan-998',
    name: 'Uzbekistan',
    clean: 'uzbekistan',
    code: '998',
    flag: '🇺🇿',
  },
  {
    key: 'vanuatu-678',
    name: 'Vanuatu',
    clean: 'vanuatu',
    code: '678',
    flag: '🇻🇺',
  },
  {
    key: 'vatican-city-379',
    name: 'Vatican City',
    clean: 'vatican city',
    code: '379',
    flag: '🇻🇦',
  },
  {
    key: 'venezuela-58',
    name: 'Venezuela',
    clean: 'venezuela',
    code: '58',
    flag: '🇻🇪',
  },
  {
    key: 'vietnam-84',
    name: 'Vietnam',
    clean: 'vietnam',
    code: '84',
    flag: '🇻🇳',
  },
  {
    key: 'wallis-futuna-681',
    name: 'Wallis & Futuna',
    clean: 'wallis & futuna',
    code: '681',
    flag: '🇼🇫',
  },
  {
    key: 'western-sahara-212',
    name: 'Western Sahara',
    clean: 'western sahara',
    code: '212',
    flag: '🇪🇭',
  },
  {
    key: 'yemen-967',
    name: 'Yemen',
    clean: 'yemen',
    code: '967',
    flag: '🇾🇪',
  },
  {
    key: 'zambia-260',
    name: 'Zambia',
    clean: 'zambia',
    code: '260',
    flag: '🇿🇲',
  },
  {
    key: 'zimbabwe-263',
    name: 'Zimbabwe',
    clean: 'zimbabwe',
    code: '263',
    flag: '🇿🇼',
  },
]: Array<Country>)
