// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: pkg/errorcodes/errors.proto

package errorcodes // import "berty.tech/core/pkg/errorcodes"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gogo/protobuf/gogoproto"

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Code int32

const (
	ErrUndefined                    Code = 0
	OK                              Code = 1
	ErrBase                         Code = 2
	ErrUnimplemented                Code = 3
	ErrRandomGeneratorFailed        Code = 4
	ErrUUIDGeneratorFailed          Code = 5
	ErrSerialization                Code = 6
	ErrDeserialization              Code = 7
	ErrPanic                        Code = 8
	ErrEnvelope                     Code = 1000
	ErrEnvelopeUntrusted            Code = 1001
	ErrEnvelopeNoDeviceFound        Code = 1002
	ErrEntity                       Code = 2000
	ErrEntityInput                  Code = 2001
	ErrEntityData                   Code = 2002
	ErrEntityExists                 Code = 2003
	ErrNet                          Code = 3000
	ErrNetAnotherClientConnected    Code = 3001
	ErrNetStream                    Code = 3002
	ErrNetQueue                     Code = 3003
	ErrNetDial                      Code = 3004
	ErrNetPing                      Code = 3005
	ErrNetP2P                       Code = 3100
	ErrNetP2PIdentity               Code = 3101
	ErrNetP2PPublicKey              Code = 3102
	ErrEvent                        Code = 4000
	ErrEventSender                  Code = 4001
	ErrEventData                    Code = 4002
	ErrValidation                   Code = 5000
	ErrValidationInput              Code = 5001
	ErrValidationMyself             Code = 5002
	ErrPagination                   Code = 6000
	ErrDb                           Code = 7000
	ErrDbCreate                     Code = 7001
	ErrDbUpdate                     Code = 7002
	ErrDbDelete                     Code = 7003
	ErrDbNothingFound               Code = 7004
	ErrDbInternalError              Code = 7005
	ErrCrypto                       Code = 8000
	ErrCryptoSig                    Code = 8100
	ErrCryptoSigMismatch            Code = 8101
	ErrCryptoSigFormat              Code = 8102
	ErrCryptoEncrypt                Code = 8200
	ErrCryptoDecrypt                Code = 8300
	ErrCryptoKey                    Code = 8400
	ErrCryptoKeyGen                 Code = 8401
	ErrCryptoKeyDecode              Code = 8402
	ErrCryptoSigchain               Code = 8500
	ErrAccManager                   Code = 9000
	ErrAccManagerInitNode           Code = 9001
	ErrAccManagerDb                 Code = 9002
	ErrAccManagerDbInit             Code = 9003
	ErrAccManagerDbDrop             Code = 9004
	ErrAccManagerDbMig              Code = 9005
	ErrAccManagerDbDir              Code = 9006
	ErrAccManagerNotOpened          Code = 9007
	ErrAccManagerCfg                Code = 9100
	ErrAccManagerCfgName            Code = 9101
	ErrAccManagerCfgPassphrase      Code = 9102
	ErrAccManagerCfgNet             Code = 9104
	ErrAccManagerCfgGrpcSrv         Code = 9105
	ErrAccManagerBot                Code = 9200
	ErrAccManagerBotInit            Code = 9201
	ErrAccManagerBotExited          Code = 9202
	ErrContactReq                   Code = 10000
	ErrContactReqKey                Code = 10001
	ErrContactReqKeyMissing         Code = 10002
	ErrContactReqExisting           Code = 10003
	ErrContactReqMyself             Code = 10004
	ErrCfg                          Code = 11000
	ErrCfgMissing                   Code = 11001
	ErrCfgMyself                    Code = 11002
	ErrCfgDevices                   Code = 11003
	ErrSenderAlias                  Code = 12000
	ErrSenderAliasGen               Code = 12001
	ErrSenderAliasNoCandidates      Code = 12002
	ErrSenderAliasUpdateFailed      Code = 12003
	ErrConversation                 Code = 13000
	ErrConversationMembers          Code = 13001
	ErrConversationNotEnoughMembers Code = 13002
	ErrPush                         Code = 14000
	ErrPushUnknownProvider          Code = 14001
	ErrPushProvider                 Code = 14002
	ErrPushInvalidIdentifier        Code = 14003
	ErrPushInvalidServerConfig      Code = 14004
	ErrPushMissingBundleId          Code = 14005
	ErrPushUnknownDestination       Code = 14006
	ErrPushBroadcastIdentifier      Code = 14007
	ErrPushInvalidType              Code = 14008
	ErrPushBroadcast                Code = 14009
	ErrNotification                 Code = 15000
	ErrNotificationMarshalFCM       Code = 15001
	ErrNotificationMarshalAPNS      Code = 15002
	ErrNotificationMarshalMQTT      Code = 15003
	ErrNotificationUnmarshalFCM     Code = 15004
	ErrNotificationUnmarshalAPNS    Code = 15005
	ErrNotificationUnmarshalMQTT    Code = 15006
	ErrNotificationReceive          Code = 15007
	ErrNode                         Code = 16000
	ErrNodePushNotifSub             Code = 16001
	ErrChunk                        Code = 17000
	ErrChunkBadIndex                Code = 17001
	ErrChunkBadData                 Code = 17002
	ErrChunkBadSliceID              Code = 17003
	ErrChunkBadSliceLength          Code = 17004
	ErrChunkSliceNotComplete        Code = 17005
	ErrChunkBadSlice                Code = 17006
	ErrChunkDaemonStoragePath       Code = 17007
	ErrChunkDaemonOpenDatabase      Code = 17008
	ErrChunkSlice                   Code = 17009
	ErrChunkPublish                 Code = 17010
	ErrChunkSave                    Code = 17011
	ErrChunkFindSliceByID           Code = 17012
	ErrChunkFindAllSlices           Code = 17013
)

var Code_name = map[int32]string{
	0:     "ErrUndefined",
	1:     "OK",
	2:     "ErrBase",
	3:     "ErrUnimplemented",
	4:     "ErrRandomGeneratorFailed",
	5:     "ErrUUIDGeneratorFailed",
	6:     "ErrSerialization",
	7:     "ErrDeserialization",
	8:     "ErrPanic",
	1000:  "ErrEnvelope",
	1001:  "ErrEnvelopeUntrusted",
	1002:  "ErrEnvelopeNoDeviceFound",
	2000:  "ErrEntity",
	2001:  "ErrEntityInput",
	2002:  "ErrEntityData",
	2003:  "ErrEntityExists",
	3000:  "ErrNet",
	3001:  "ErrNetAnotherClientConnected",
	3002:  "ErrNetStream",
	3003:  "ErrNetQueue",
	3004:  "ErrNetDial",
	3005:  "ErrNetPing",
	3100:  "ErrNetP2P",
	3101:  "ErrNetP2PIdentity",
	3102:  "ErrNetP2PPublicKey",
	4000:  "ErrEvent",
	4001:  "ErrEventSender",
	4002:  "ErrEventData",
	5000:  "ErrValidation",
	5001:  "ErrValidationInput",
	5002:  "ErrValidationMyself",
	6000:  "ErrPagination",
	7000:  "ErrDb",
	7001:  "ErrDbCreate",
	7002:  "ErrDbUpdate",
	7003:  "ErrDbDelete",
	7004:  "ErrDbNothingFound",
	7005:  "ErrDbInternalError",
	8000:  "ErrCrypto",
	8100:  "ErrCryptoSig",
	8101:  "ErrCryptoSigMismatch",
	8102:  "ErrCryptoSigFormat",
	8200:  "ErrCryptoEncrypt",
	8300:  "ErrCryptoDecrypt",
	8400:  "ErrCryptoKey",
	8401:  "ErrCryptoKeyGen",
	8402:  "ErrCryptoKeyDecode",
	8500:  "ErrCryptoSigchain",
	9000:  "ErrAccManager",
	9001:  "ErrAccManagerInitNode",
	9002:  "ErrAccManagerDb",
	9003:  "ErrAccManagerDbInit",
	9004:  "ErrAccManagerDbDrop",
	9005:  "ErrAccManagerDbMig",
	9006:  "ErrAccManagerDbDir",
	9007:  "ErrAccManagerNotOpened",
	9100:  "ErrAccManagerCfg",
	9101:  "ErrAccManagerCfgName",
	9102:  "ErrAccManagerCfgPassphrase",
	9104:  "ErrAccManagerCfgNet",
	9105:  "ErrAccManagerCfgGrpcSrv",
	9200:  "ErrAccManagerBot",
	9201:  "ErrAccManagerBotInit",
	9202:  "ErrAccManagerBotExited",
	10000: "ErrContactReq",
	10001: "ErrContactReqKey",
	10002: "ErrContactReqKeyMissing",
	10003: "ErrContactReqExisting",
	10004: "ErrContactReqMyself",
	11000: "ErrCfg",
	11001: "ErrCfgMissing",
	11002: "ErrCfgMyself",
	11003: "ErrCfgDevices",
	12000: "ErrSenderAlias",
	12001: "ErrSenderAliasGen",
	12002: "ErrSenderAliasNoCandidates",
	12003: "ErrSenderAliasUpdateFailed",
	13000: "ErrConversation",
	13001: "ErrConversationMembers",
	13002: "ErrConversationNotEnoughMembers",
	14000: "ErrPush",
	14001: "ErrPushUnknownProvider",
	14002: "ErrPushProvider",
	14003: "ErrPushInvalidIdentifier",
	14004: "ErrPushInvalidServerConfig",
	14005: "ErrPushMissingBundleId",
	14006: "ErrPushUnknownDestination",
	14007: "ErrPushBroadcastIdentifier",
	14008: "ErrPushInvalidType",
	14009: "ErrPushBroadcast",
	15000: "ErrNotification",
	15001: "ErrNotificationMarshalFCM",
	15002: "ErrNotificationMarshalAPNS",
	15003: "ErrNotificationMarshalMQTT",
	15004: "ErrNotificationUnmarshalFCM",
	15005: "ErrNotificationUnmarshalAPNS",
	15006: "ErrNotificationUnmarshalMQTT",
	15007: "ErrNotificationReceive",
	16000: "ErrNode",
	16001: "ErrNodePushNotifSub",
	17000: "ErrChunk",
	17001: "ErrChunkBadIndex",
	17002: "ErrChunkBadData",
	17003: "ErrChunkBadSliceID",
	17004: "ErrChunkBadSliceLength",
	17005: "ErrChunkSliceNotComplete",
	17006: "ErrChunkBadSlice",
	17007: "ErrChunkDaemonStoragePath",
	17008: "ErrChunkDaemonOpenDatabase",
	17009: "ErrChunkSlice",
	17010: "ErrChunkPublish",
	17011: "ErrChunkSave",
	17012: "ErrChunkFindSliceByID",
	17013: "ErrChunkFindAllSlices",
}
var Code_value = map[string]int32{
	"ErrUndefined":                    0,
	"OK":                              1,
	"ErrBase":                         2,
	"ErrUnimplemented":                3,
	"ErrRandomGeneratorFailed":        4,
	"ErrUUIDGeneratorFailed":          5,
	"ErrSerialization":                6,
	"ErrDeserialization":              7,
	"ErrPanic":                        8,
	"ErrEnvelope":                     1000,
	"ErrEnvelopeUntrusted":            1001,
	"ErrEnvelopeNoDeviceFound":        1002,
	"ErrEntity":                       2000,
	"ErrEntityInput":                  2001,
	"ErrEntityData":                   2002,
	"ErrEntityExists":                 2003,
	"ErrNet":                          3000,
	"ErrNetAnotherClientConnected":    3001,
	"ErrNetStream":                    3002,
	"ErrNetQueue":                     3003,
	"ErrNetDial":                      3004,
	"ErrNetPing":                      3005,
	"ErrNetP2P":                       3100,
	"ErrNetP2PIdentity":               3101,
	"ErrNetP2PPublicKey":              3102,
	"ErrEvent":                        4000,
	"ErrEventSender":                  4001,
	"ErrEventData":                    4002,
	"ErrValidation":                   5000,
	"ErrValidationInput":              5001,
	"ErrValidationMyself":             5002,
	"ErrPagination":                   6000,
	"ErrDb":                           7000,
	"ErrDbCreate":                     7001,
	"ErrDbUpdate":                     7002,
	"ErrDbDelete":                     7003,
	"ErrDbNothingFound":               7004,
	"ErrDbInternalError":              7005,
	"ErrCrypto":                       8000,
	"ErrCryptoSig":                    8100,
	"ErrCryptoSigMismatch":            8101,
	"ErrCryptoSigFormat":              8102,
	"ErrCryptoEncrypt":                8200,
	"ErrCryptoDecrypt":                8300,
	"ErrCryptoKey":                    8400,
	"ErrCryptoKeyGen":                 8401,
	"ErrCryptoKeyDecode":              8402,
	"ErrCryptoSigchain":               8500,
	"ErrAccManager":                   9000,
	"ErrAccManagerInitNode":           9001,
	"ErrAccManagerDb":                 9002,
	"ErrAccManagerDbInit":             9003,
	"ErrAccManagerDbDrop":             9004,
	"ErrAccManagerDbMig":              9005,
	"ErrAccManagerDbDir":              9006,
	"ErrAccManagerNotOpened":          9007,
	"ErrAccManagerCfg":                9100,
	"ErrAccManagerCfgName":            9101,
	"ErrAccManagerCfgPassphrase":      9102,
	"ErrAccManagerCfgNet":             9104,
	"ErrAccManagerCfgGrpcSrv":         9105,
	"ErrAccManagerBot":                9200,
	"ErrAccManagerBotInit":            9201,
	"ErrAccManagerBotExited":          9202,
	"ErrContactReq":                   10000,
	"ErrContactReqKey":                10001,
	"ErrContactReqKeyMissing":         10002,
	"ErrContactReqExisting":           10003,
	"ErrContactReqMyself":             10004,
	"ErrCfg":                          11000,
	"ErrCfgMissing":                   11001,
	"ErrCfgMyself":                    11002,
	"ErrCfgDevices":                   11003,
	"ErrSenderAlias":                  12000,
	"ErrSenderAliasGen":               12001,
	"ErrSenderAliasNoCandidates":      12002,
	"ErrSenderAliasUpdateFailed":      12003,
	"ErrConversation":                 13000,
	"ErrConversationMembers":          13001,
	"ErrConversationNotEnoughMembers": 13002,
	"ErrPush":                         14000,
	"ErrPushUnknownProvider":          14001,
	"ErrPushProvider":                 14002,
	"ErrPushInvalidIdentifier":        14003,
	"ErrPushInvalidServerConfig":      14004,
	"ErrPushMissingBundleId":          14005,
	"ErrPushUnknownDestination":       14006,
	"ErrPushBroadcastIdentifier":      14007,
	"ErrPushInvalidType":              14008,
	"ErrPushBroadcast":                14009,
	"ErrNotification":                 15000,
	"ErrNotificationMarshalFCM":       15001,
	"ErrNotificationMarshalAPNS":      15002,
	"ErrNotificationMarshalMQTT":      15003,
	"ErrNotificationUnmarshalFCM":     15004,
	"ErrNotificationUnmarshalAPNS":    15005,
	"ErrNotificationUnmarshalMQTT":    15006,
	"ErrNotificationReceive":          15007,
	"ErrNode":                         16000,
	"ErrNodePushNotifSub":             16001,
	"ErrChunk":                        17000,
	"ErrChunkBadIndex":                17001,
	"ErrChunkBadData":                 17002,
	"ErrChunkBadSliceID":              17003,
	"ErrChunkBadSliceLength":          17004,
	"ErrChunkSliceNotComplete":        17005,
	"ErrChunkBadSlice":                17006,
	"ErrChunkDaemonStoragePath":       17007,
	"ErrChunkDaemonOpenDatabase":      17008,
	"ErrChunkSlice":                   17009,
	"ErrChunkPublish":                 17010,
	"ErrChunkSave":                    17011,
	"ErrChunkFindSliceByID":           17012,
	"ErrChunkFindAllSlices":           17013,
}

func (x Code) String() string {
	return proto.EnumName(Code_name, int32(x))
}
func (Code) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_errors_2de00bcffb68b009, []int{0}
}

// Metadata is designed to be used as grpc status detail
type Metadata struct {
	// unique enum code number to identify the error
	Code Code `protobuf:"varint,1,opt,name=code,proto3,enum=berty.errorcodes.Code" json:"code,omitempty"`
	// extended code (see hierarchy.go)
	ExtendedCodes []Code `protobuf:"varint,2,rep,packed,name=extended_codes,json=extendedCodes,enum=berty.errorcodes.Code" json:"extended_codes,omitempty"`
	// used for templated errors (i18n)
	Placeholders map[string]string `protobuf:"bytes,3,rep,name=placeholders" json:"placeholders,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// nested/wraped errors
	Parent *Metadata `protobuf:"bytes,4,opt,name=parent" json:"parent,omitempty"`
	// this field will be a duplicate for the top-level error and then skipped,
	// but this field is particularly useful to get debugging info when looking up parent errors.
	Message string `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	// caller is the first line of a stacktrace.
	Caller               string   `protobuf:"bytes,6,opt,name=caller,proto3" json:"caller,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Metadata) Reset()         { *m = Metadata{} }
func (m *Metadata) String() string { return proto.CompactTextString(m) }
func (*Metadata) ProtoMessage()    {}
func (*Metadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_errors_2de00bcffb68b009, []int{0}
}
func (m *Metadata) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Metadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Metadata.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *Metadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Metadata.Merge(dst, src)
}
func (m *Metadata) XXX_Size() int {
	return m.Size()
}
func (m *Metadata) XXX_DiscardUnknown() {
	xxx_messageInfo_Metadata.DiscardUnknown(m)
}

var xxx_messageInfo_Metadata proto.InternalMessageInfo

func (m *Metadata) GetCode() Code {
	if m != nil {
		return m.Code
	}
	return ErrUndefined
}

func (m *Metadata) GetExtendedCodes() []Code {
	if m != nil {
		return m.ExtendedCodes
	}
	return nil
}

func (m *Metadata) GetPlaceholders() map[string]string {
	if m != nil {
		return m.Placeholders
	}
	return nil
}

func (m *Metadata) GetParent() *Metadata {
	if m != nil {
		return m.Parent
	}
	return nil
}

func (m *Metadata) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Metadata) GetCaller() string {
	if m != nil {
		return m.Caller
	}
	return ""
}

func init() {
	proto.RegisterType((*Metadata)(nil), "berty.errorcodes.Metadata")
	proto.RegisterMapType((map[string]string)(nil), "berty.errorcodes.Metadata.PlaceholdersEntry")
	proto.RegisterEnum("berty.errorcodes.Code", Code_name, Code_value)
}
func (m *Metadata) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Metadata) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Code != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintErrors(dAtA, i, uint64(m.Code))
	}
	if len(m.ExtendedCodes) > 0 {
		dAtA2 := make([]byte, len(m.ExtendedCodes)*10)
		var j1 int
		for _, num := range m.ExtendedCodes {
			for num >= 1<<7 {
				dAtA2[j1] = uint8(uint64(num)&0x7f | 0x80)
				num >>= 7
				j1++
			}
			dAtA2[j1] = uint8(num)
			j1++
		}
		dAtA[i] = 0x12
		i++
		i = encodeVarintErrors(dAtA, i, uint64(j1))
		i += copy(dAtA[i:], dAtA2[:j1])
	}
	if len(m.Placeholders) > 0 {
		for k := range m.Placeholders {
			dAtA[i] = 0x1a
			i++
			v := m.Placeholders[k]
			mapSize := 1 + len(k) + sovErrors(uint64(len(k))) + 1 + len(v) + sovErrors(uint64(len(v)))
			i = encodeVarintErrors(dAtA, i, uint64(mapSize))
			dAtA[i] = 0xa
			i++
			i = encodeVarintErrors(dAtA, i, uint64(len(k)))
			i += copy(dAtA[i:], k)
			dAtA[i] = 0x12
			i++
			i = encodeVarintErrors(dAtA, i, uint64(len(v)))
			i += copy(dAtA[i:], v)
		}
	}
	if m.Parent != nil {
		dAtA[i] = 0x22
		i++
		i = encodeVarintErrors(dAtA, i, uint64(m.Parent.Size()))
		n3, err := m.Parent.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n3
	}
	if len(m.Message) > 0 {
		dAtA[i] = 0x2a
		i++
		i = encodeVarintErrors(dAtA, i, uint64(len(m.Message)))
		i += copy(dAtA[i:], m.Message)
	}
	if len(m.Caller) > 0 {
		dAtA[i] = 0x32
		i++
		i = encodeVarintErrors(dAtA, i, uint64(len(m.Caller)))
		i += copy(dAtA[i:], m.Caller)
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func encodeVarintErrors(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *Metadata) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Code != 0 {
		n += 1 + sovErrors(uint64(m.Code))
	}
	if len(m.ExtendedCodes) > 0 {
		l = 0
		for _, e := range m.ExtendedCodes {
			l += sovErrors(uint64(e))
		}
		n += 1 + sovErrors(uint64(l)) + l
	}
	if len(m.Placeholders) > 0 {
		for k, v := range m.Placeholders {
			_ = k
			_ = v
			mapEntrySize := 1 + len(k) + sovErrors(uint64(len(k))) + 1 + len(v) + sovErrors(uint64(len(v)))
			n += mapEntrySize + 1 + sovErrors(uint64(mapEntrySize))
		}
	}
	if m.Parent != nil {
		l = m.Parent.Size()
		n += 1 + l + sovErrors(uint64(l))
	}
	l = len(m.Message)
	if l > 0 {
		n += 1 + l + sovErrors(uint64(l))
	}
	l = len(m.Caller)
	if l > 0 {
		n += 1 + l + sovErrors(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovErrors(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozErrors(x uint64) (n int) {
	return sovErrors(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Metadata) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowErrors
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Metadata: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Metadata: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Code", wireType)
			}
			m.Code = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowErrors
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Code |= (Code(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType == 0 {
				var v Code
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowErrors
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= (Code(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.ExtendedCodes = append(m.ExtendedCodes, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowErrors
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= (int(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthErrors
				}
				postIndex := iNdEx + packedLen
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				var elementCount int
				if elementCount != 0 && len(m.ExtendedCodes) == 0 {
					m.ExtendedCodes = make([]Code, 0, elementCount)
				}
				for iNdEx < postIndex {
					var v Code
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowErrors
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= (Code(b) & 0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.ExtendedCodes = append(m.ExtendedCodes, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field ExtendedCodes", wireType)
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Placeholders", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowErrors
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthErrors
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Placeholders == nil {
				m.Placeholders = make(map[string]string)
			}
			var mapkey string
			var mapvalue string
			for iNdEx < postIndex {
				entryPreIndex := iNdEx
				var wire uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowErrors
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					wire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				fieldNum := int32(wire >> 3)
				if fieldNum == 1 {
					var stringLenmapkey uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowErrors
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapkey |= (uint64(b) & 0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapkey := int(stringLenmapkey)
					if intStringLenmapkey < 0 {
						return ErrInvalidLengthErrors
					}
					postStringIndexmapkey := iNdEx + intStringLenmapkey
					if postStringIndexmapkey > l {
						return io.ErrUnexpectedEOF
					}
					mapkey = string(dAtA[iNdEx:postStringIndexmapkey])
					iNdEx = postStringIndexmapkey
				} else if fieldNum == 2 {
					var stringLenmapvalue uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowErrors
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapvalue |= (uint64(b) & 0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapvalue := int(stringLenmapvalue)
					if intStringLenmapvalue < 0 {
						return ErrInvalidLengthErrors
					}
					postStringIndexmapvalue := iNdEx + intStringLenmapvalue
					if postStringIndexmapvalue > l {
						return io.ErrUnexpectedEOF
					}
					mapvalue = string(dAtA[iNdEx:postStringIndexmapvalue])
					iNdEx = postStringIndexmapvalue
				} else {
					iNdEx = entryPreIndex
					skippy, err := skipErrors(dAtA[iNdEx:])
					if err != nil {
						return err
					}
					if skippy < 0 {
						return ErrInvalidLengthErrors
					}
					if (iNdEx + skippy) > postIndex {
						return io.ErrUnexpectedEOF
					}
					iNdEx += skippy
				}
			}
			m.Placeholders[mapkey] = mapvalue
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Parent", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowErrors
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthErrors
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Parent == nil {
				m.Parent = &Metadata{}
			}
			if err := m.Parent.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Message", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowErrors
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthErrors
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Message = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Caller", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowErrors
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthErrors
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Caller = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipErrors(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthErrors
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipErrors(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowErrors
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowErrors
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowErrors
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthErrors
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowErrors
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipErrors(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthErrors = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowErrors   = fmt.Errorf("proto: integer overflow")
)

func init() { proto.RegisterFile("pkg/errorcodes/errors.proto", fileDescriptor_errors_2de00bcffb68b009) }

var fileDescriptor_errors_2de00bcffb68b009 = []byte{
	// 1657 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x57, 0x5d, 0x6c, 0x5c, 0x47,
	0x15, 0xee, 0xb5, 0x1d, 0x3b, 0x19, 0x27, 0xf6, 0xc9, 0x24, 0xb1, 0xb7, 0x4e, 0xb0, 0x0d, 0x42,
	0x4a, 0x54, 0x81, 0x8d, 0x8c, 0x14, 0x21, 0x24, 0x48, 0xbd, 0xbf, 0x5a, 0x85, 0xbd, 0xdd, 0x7a,
	0x63, 0x1e, 0x90, 0x22, 0x34, 0x7b, 0xef, 0xf1, 0xdd, 0xab, 0xdc, 0x3b, 0xb3, 0xcc, 0x9d, 0xbb,
	0x64, 0x91, 0x2a, 0x81, 0xb4, 0x0f, 0x01, 0x01, 0x6a, 0x81, 0x87, 0x02, 0x6d, 0xf9, 0x47, 0xfc,
	0xff, 0x16, 0x68, 0xf9, 0x91, 0x78, 0x0c, 0x3c, 0xa5, 0xe5, 0x85, 0x5f, 0xa9, 0xa4, 0x2f, 0x6d,
	0x29, 0x25, 0x2d, 0x20, 0xf1, 0xf3, 0x82, 0x66, 0xee, 0xec, 0xee, 0x5d, 0xdb, 0xe4, 0xc9, 0x7b,
	0xbe, 0xef, 0xcc, 0x99, 0x33, 0xe7, 0x9c, 0xf9, 0xe6, 0x9a, 0x9c, 0xed, 0x5e, 0x0b, 0x36, 0x51,
	0x4a, 0x21, 0x3d, 0xe1, 0x63, 0x92, 0xfd, 0x4c, 0x36, 0xba, 0x52, 0x28, 0x41, 0xa1, 0x8d, 0x52,
	0xf5, 0x37, 0xc6, 0xf4, 0xca, 0x9b, 0x83, 0x50, 0x75, 0xd2, 0xf6, 0x86, 0x27, 0xe2, 0xcd, 0x40,
	0x04, 0x62, 0xd3, 0x38, 0xb6, 0xd3, 0x3d, 0x63, 0x19, 0xc3, 0xfc, 0xca, 0x02, 0xbc, 0xe1, 0x95,
	0x29, 0x72, 0xb4, 0x81, 0x8a, 0xf9, 0x4c, 0x31, 0x7a, 0x1f, 0x99, 0xd1, 0x41, 0x0a, 0xce, 0xba,
	0x73, 0x61, 0x61, 0x6b, 0x69, 0x63, 0x7f, 0xf0, 0x8d, 0x92, 0xf0, 0x71, 0xc7, 0xf8, 0xd0, 0x77,
	0x90, 0x05, 0xbc, 0xae, 0x90, 0xfb, 0xe8, 0xbf, 0xd7, 0x90, 0x85, 0xa9, 0xf5, 0xe9, 0xbb, 0xac,
	0x3a, 0x31, 0xf4, 0xd6, 0x56, 0x42, 0x9b, 0xe4, 0x78, 0x37, 0x62, 0x1e, 0x76, 0x44, 0xe4, 0xa3,
	0x4c, 0x0a, 0xd3, 0xeb, 0xd3, 0x17, 0xe6, 0xb7, 0xde, 0x74, 0x70, 0xf1, 0x30, 0xb9, 0x8d, 0x66,
	0xce, 0xbd, 0xc2, 0x95, 0xec, 0xef, 0x4c, 0x44, 0xa0, 0x5b, 0x64, 0xb6, 0xcb, 0x24, 0x72, 0x55,
	0x98, 0x59, 0x77, 0x2e, 0xcc, 0x6f, 0xad, 0xfc, 0xff, 0x58, 0x3b, 0xd6, 0x93, 0x16, 0xc8, 0x5c,
	0x8c, 0x49, 0xc2, 0x02, 0x2c, 0x1c, 0x59, 0x77, 0x2e, 0x1c, 0xdb, 0x19, 0x9a, 0x74, 0x89, 0xcc,
	0x7a, 0x2c, 0x8a, 0x50, 0x16, 0x66, 0x0d, 0x61, 0xad, 0x95, 0x4b, 0xe4, 0xe4, 0x81, 0x44, 0x28,
	0x90, 0xe9, 0x6b, 0xd8, 0x37, 0x65, 0x3b, 0xb6, 0xa3, 0x7f, 0xd2, 0xd3, 0xe4, 0x48, 0x8f, 0x45,
	0x29, 0x16, 0xa6, 0x0c, 0x96, 0x19, 0x6f, 0x9f, 0x7a, 0x9b, 0x73, 0xdf, 0xcd, 0x33, 0x64, 0x46,
	0x97, 0x80, 0x02, 0x39, 0x5e, 0x91, 0x72, 0x97, 0xfb, 0xb8, 0x17, 0x72, 0xf4, 0xe1, 0x1e, 0x3a,
	0x4b, 0xa6, 0x1e, 0xb8, 0x0c, 0x0e, 0x9d, 0x27, 0x73, 0x15, 0x29, 0x8b, 0x2c, 0x41, 0x98, 0xa2,
	0xa7, 0x09, 0x18, 0xb7, 0x30, 0xee, 0x46, 0x18, 0x23, 0x57, 0xe8, 0xc3, 0x34, 0x3d, 0x47, 0x0a,
	0x15, 0x29, 0x77, 0x18, 0xf7, 0x45, 0x5c, 0x43, 0x8e, 0x92, 0x29, 0x21, 0xab, 0x2c, 0x8c, 0xd0,
	0x87, 0x19, 0xba, 0x42, 0x96, 0xf4, 0x9a, 0xdd, 0x7a, 0x79, 0x3f, 0x77, 0xc4, 0xc6, 0x6b, 0xa1,
	0x0c, 0x59, 0x14, 0x7e, 0x80, 0xa9, 0x50, 0x70, 0x98, 0xa5, 0x4b, 0x84, 0x56, 0xa4, 0x2c, 0x63,
	0x32, 0x81, 0xcf, 0xd1, 0xe3, 0xe4, 0x68, 0x45, 0xca, 0x26, 0xe3, 0xa1, 0x07, 0x47, 0x29, 0x90,
	0xf9, 0x8a, 0x94, 0x15, 0xde, 0xc3, 0x48, 0x74, 0x11, 0x5e, 0x98, 0xa3, 0xf7, 0x92, 0xd3, 0x39,
	0x64, 0x97, 0x2b, 0x99, 0x26, 0x3a, 0xc3, 0x17, 0xe7, 0xe8, 0xeb, 0x4c, 0x8a, 0x43, 0xca, 0x15,
	0x65, 0xec, 0x85, 0x1e, 0x56, 0x45, 0xca, 0x7d, 0x78, 0x69, 0x8e, 0x2e, 0x90, 0x63, 0x86, 0x56,
	0xa1, 0xea, 0xc3, 0xad, 0x45, 0x7a, 0x8a, 0x2c, 0x8c, 0xec, 0x3a, 0xef, 0xa6, 0x0a, 0x9e, 0x59,
	0xa4, 0x94, 0x9c, 0x18, 0x81, 0x65, 0xa6, 0x18, 0x3c, 0xbb, 0x48, 0x4f, 0x93, 0xc5, 0x11, 0x56,
	0xb9, 0x1e, 0x26, 0x2a, 0x81, 0xdf, 0x2c, 0xd2, 0x79, 0x32, 0x5b, 0x91, 0xd2, 0x45, 0x05, 0x4f,
	0x2d, 0xd3, 0xd7, 0x93, 0x73, 0x99, 0xb1, 0xcd, 0x85, 0xea, 0xa0, 0x2c, 0x45, 0x21, 0x72, 0x55,
	0x12, 0x9c, 0xa3, 0xa7, 0xb3, 0x7b, 0x7a, 0x99, 0x9e, 0x34, 0xd5, 0x77, 0x51, 0xb5, 0x94, 0x44,
	0x16, 0xc3, 0x4f, 0x97, 0xed, 0xe9, 0x5c, 0x54, 0x0f, 0xa6, 0x98, 0x22, 0xfc, 0x6c, 0x99, 0x2e,
	0x12, 0x92, 0x21, 0xe5, 0x90, 0x45, 0xf0, 0xf3, 0x1c, 0xd0, 0x0c, 0x79, 0x00, 0xbf, 0x58, 0xb6,
	0xa7, 0xd0, 0xc0, 0x56, 0x13, 0x1e, 0x2b, 0xd0, 0x25, 0x72, 0x72, 0x64, 0xd7, 0x7d, 0xcc, 0x4e,
	0xf7, 0x78, 0x81, 0x2e, 0x9b, 0xfa, 0x66, 0x78, 0x33, 0x6d, 0x47, 0xa1, 0x77, 0x19, 0xfb, 0xf0,
	0x44, 0x81, 0x9e, 0x30, 0x05, 0xae, 0xf4, 0x90, 0x2b, 0xf8, 0xfc, 0xda, 0xb0, 0x0a, 0xda, 0x6c,
	0xe9, 0xdb, 0x22, 0xe1, 0x0b, 0x6b, 0x36, 0x57, 0x03, 0x9a, 0x22, 0x7c, 0x71, 0xcd, 0x16, 0xe6,
	0xdd, 0x2c, 0x0a, 0xfd, 0xac, 0x55, 0x37, 0xce, 0xdb, 0x3d, 0xc6, 0x58, 0x56, 0xc5, 0x0f, 0x9f,
	0xa7, 0x05, 0x72, 0x6a, 0x82, 0x68, 0xf4, 0x13, 0x8c, 0xf6, 0xe0, 0x23, 0xe7, 0x6d, 0x98, 0x26,
	0x0b, 0x42, 0x9e, 0x85, 0xb9, 0xb3, 0x41, 0x09, 0x39, 0xa2, 0x47, 0xa1, 0x0d, 0xbf, 0xbd, 0x68,
	0x4b, 0x52, 0x6e, 0x97, 0x24, 0x32, 0x85, 0xf0, 0xbb, 0x31, 0xb2, 0xdb, 0xf5, 0x35, 0xf2, 0xfb,
	0x31, 0x52, 0xc6, 0x08, 0x15, 0xc2, 0x1f, 0x2e, 0xda, 0x22, 0x94, 0xdb, 0xae, 0x50, 0x9d, 0x90,
	0x07, 0x59, 0xcb, 0xff, 0x78, 0xd1, 0x26, 0x58, 0x6e, 0xd7, 0xb9, 0x42, 0xc9, 0x59, 0x54, 0xd1,
	0x37, 0x13, 0xfe, 0x74, 0xd1, 0x56, 0xb1, 0x24, 0xfb, 0x5d, 0x25, 0xe0, 0x97, 0xef, 0xb4, 0x07,
	0xce, 0xec, 0x56, 0x18, 0xc0, 0x97, 0x2f, 0xd9, 0x41, 0x1b, 0x41, 0x8d, 0x30, 0x89, 0x99, 0xf2,
	0x3a, 0xf0, 0x95, 0x4b, 0x36, 0xec, 0x88, 0xaa, 0x0a, 0x19, 0x33, 0x05, 0x5f, 0xbd, 0x44, 0xcf,
	0x98, 0x51, 0xcf, 0x88, 0x0a, 0xf7, 0xf4, 0x5f, 0xb8, 0x71, 0xff, 0x04, 0x5c, 0xc6, 0x0c, 0x7e,
	0xf9, 0xfe, 0x89, 0x4d, 0x75, 0x73, 0x6e, 0x6d, 0xdb, 0x51, 0x1b, 0x41, 0x35, 0xe4, 0xf0, 0xcc,
	0xf6, 0xc4, 0x7e, 0x97, 0xb1, 0x5f, 0x46, 0x2d, 0x2e, 0xf0, 0xec, 0xb6, 0x3d, 0xf7, 0x28, 0x11,
	0xaf, 0xc3, 0x42, 0x0e, 0x4f, 0x16, 0x6d, 0x95, 0xb7, 0x3d, 0xaf, 0xc1, 0x38, 0x0b, 0x50, 0xc2,
	0xd7, 0xaa, 0x74, 0x85, 0x9c, 0x99, 0xc0, 0xea, 0x3c, 0x54, 0xae, 0x8e, 0xf3, 0xf5, 0xaa, 0xdd,
	0x76, 0xcc, 0x95, 0xdb, 0xf0, 0x8d, 0xaa, 0xed, 0x62, 0x1e, 0xd5, 0x6b, 0xe0, 0x9b, 0x87, 0x31,
	0x65, 0x29, 0xba, 0xf0, 0xad, 0xaa, 0x4d, 0x35, 0xcf, 0x34, 0xc2, 0x00, 0xbe, 0x7d, 0x18, 0x51,
	0x0e, 0x25, 0x7c, 0xa7, 0x4a, 0xcf, 0x1a, 0xe9, 0x18, 0x13, 0xae, 0x50, 0x0f, 0x74, 0x51, 0xeb,
	0xd3, 0x77, 0xab, 0xb6, 0x72, 0x63, 0xb2, 0xb4, 0x17, 0xc0, 0x47, 0x6b, 0xb6, 0x37, 0x13, 0xb0,
	0xcb, 0x62, 0x84, 0x8f, 0xd5, 0xe8, 0x1a, 0x59, 0xd9, 0x4f, 0x35, 0x59, 0x92, 0x74, 0x3b, 0x52,
	0xab, 0xdb, 0xc7, 0x6b, 0x07, 0x72, 0xd7, 0x6b, 0x51, 0xc1, 0xc3, 0x35, 0x7a, 0x8e, 0x2c, 0xef,
	0x67, 0x6a, 0xb2, 0xeb, 0xb5, 0x64, 0x0f, 0x1e, 0xa9, 0x1d, 0x48, 0xa5, 0x28, 0x14, 0xdc, 0x39,
	0x98, 0x4a, 0x51, 0x28, 0x53, 0xa5, 0x57, 0x6b, 0x07, 0x4e, 0x56, 0x14, 0xaa, 0x72, 0x3d, 0xd4,
	0x72, 0xf0, 0x5a, 0xcd, 0xb6, 0xa8, 0x24, 0xb8, 0x62, 0x9e, 0xda, 0xc1, 0xf7, 0xc1, 0xc3, 0xee,
	0x70, 0x4e, 0x46, 0x98, 0x1e, 0x8a, 0x47, 0x5c, 0x9b, 0xd7, 0x04, 0xdc, 0x08, 0x93, 0x44, 0x0b,
	0xc2, 0x27, 0x5c, 0xdb, 0xd7, 0x31, 0x6b, 0x14, 0x4a, 0x73, 0x9f, 0x74, 0xed, 0x59, 0xc7, 0x9c,
	0xbd, 0x87, 0x9f, 0x72, 0xad, 0x7a, 0xe9, 0x72, 0xfe, 0x6b, 0x77, 0x98, 0xcb, 0x5e, 0x30, 0x0c,
	0xfb, 0xef, 0xdd, 0xe1, 0x70, 0xee, 0x05, 0x76, 0xcd, 0x7f, 0x72, 0x6e, 0x99, 0xb0, 0x26, 0xf0,
	0xdf, 0x5d, 0x2b, 0x1f, 0x99, 0x72, 0x6c, 0x47, 0x21, 0x4b, 0xe0, 0xb9, 0xab, 0x76, 0x2c, 0x73,
	0xa0, 0x9e, 0xe3, 0x3f, 0x5f, 0xb5, 0xbd, 0xc9, 0xe1, 0xae, 0x28, 0x31, 0xee, 0x6b, 0x91, 0xc0,
	0x04, 0x6e, 0x1f, 0xe2, 0x90, 0x5d, 0x7a, 0xfb, 0x94, 0x3c, 0x7f, 0x75, 0x78, 0x3f, 0x04, 0xef,
	0xa1, 0x4c, 0x32, 0x01, 0xb9, 0x89, 0xb6, 0xd0, 0x79, 0xb4, 0x81, 0x71, 0x1b, 0x65, 0x02, 0xbf,
	0x42, 0xfa, 0x46, 0xb2, 0xb6, 0x8f, 0x74, 0x85, 0xaa, 0x70, 0x91, 0x06, 0x9d, 0xa1, 0xd7, 0xaf,
	0x91, 0x1e, 0x37, 0x2f, 0x60, 0x33, 0x4d, 0x3a, 0xf0, 0xbd, 0xd8, 0x06, 0xd4, 0xd6, 0x2e, 0xbf,
	0xc6, 0xc5, 0xfb, 0x79, 0x53, 0x8a, 0x5e, 0xa8, 0xc5, 0xf1, 0xfb, 0xb1, 0xcd, 0x41, 0x93, 0x23,
	0xf4, 0x07, 0xb1, 0x7d, 0x7c, 0x34, 0x5a, 0xe7, 0x3d, 0x2d, 0x7c, 0x99, 0x18, 0xef, 0x85, 0x28,
	0xe1, 0x87, 0xb1, 0x3d, 0x59, 0x8e, 0x6e, 0xa1, 0xec, 0xa1, 0x4e, 0x6b, 0x2f, 0x0c, 0xe0, 0xc9,
	0xfc, 0x96, 0xb6, 0x09, 0xc5, 0x94, 0xfb, 0x11, 0xd6, 0x7d, 0xf8, 0x51, 0x4c, 0x57, 0xc9, 0xbd,
	0x93, 0xf9, 0x94, 0x51, 0xf7, 0x38, 0x2b, 0xc0, 0x8f, 0xf3, 0xd1, 0x8b, 0x52, 0x30, 0xdf, 0x63,
	0x89, 0xca, 0x6d, 0xff, 0x93, 0xd8, 0xde, 0xbe, 0xdc, 0xf6, 0x57, 0xfa, 0x5d, 0x84, 0xa7, 0x62,
	0x3b, 0x72, 0x13, 0x2b, 0xe1, 0xe9, 0xe1, 0x19, 0x5d, 0xa1, 0x23, 0x78, 0xd9, 0x36, 0x8f, 0xa6,
	0x36, 0x8d, 0x3c, 0xda, 0x60, 0x32, 0xe9, 0xb0, 0xa8, 0x5a, 0x6a, 0xc0, 0xa7, 0x53, 0x9b, 0xc6,
	0x21, 0xfc, 0x76, 0xd3, 0x6d, 0xc1, 0x67, 0xee, 0xe2, 0xd0, 0x78, 0xf0, 0xca, 0x15, 0xf8, 0x6c,
	0x4a, 0xd7, 0xc9, 0xd9, 0x7d, 0x0e, 0xbb, 0x3c, 0x1e, 0xef, 0xf1, 0x58, 0x3a, 0x7c, 0x69, 0x0f,
	0xf3, 0x30, 0xbb, 0x3c, 0x7e, 0x57, 0x17, 0xb3, 0xcf, 0x13, 0xa9, 0xad, 0x76, 0xde, 0x65, 0x07,
	0x3d, 0x0c, 0x7b, 0x08, 0x9f, 0x4b, 0xed, 0x2c, 0x18, 0x6d, 0xfc, 0xe0, 0x43, 0xf6, 0x0e, 0x69,
	0x4b, 0x57, 0xc9, 0x2c, 0x69, 0xa5, 0x6d, 0xf8, 0xd0, 0x43, 0x74, 0xc1, 0xbc, 0xa4, 0xa5, 0x4e,
	0xca, 0xaf, 0xc1, 0x0b, 0x03, 0x87, 0x2e, 0x65, 0xd7, 0x57, 0xdb, 0x45, 0xe6, 0xd7, 0xb9, 0x8f,
	0xd7, 0xe1, 0xc5, 0x81, 0x43, 0xcf, 0x64, 0x43, 0x6b, 0x71, 0xf3, 0xa0, 0xbe, 0x34, 0x70, 0x68,
	0x21, 0x53, 0x75, 0x0b, 0xb7, 0xa2, 0xd0, 0xc3, 0x7a, 0x19, 0xfe, 0x32, 0x70, 0xe8, 0xb9, 0x6c,
	0x9e, 0xf3, 0xcc, 0xbb, 0x90, 0x07, 0xaa, 0x03, 0x2f, 0x0f, 0x1c, 0xba, 0x6a, 0x26, 0xcd, 0xb0,
	0x86, 0x72, 0x85, 0x2a, 0x09, 0xfd, 0xad, 0xa6, 0x10, 0xfe, 0x7a, 0x20, 0x0d, 0xe3, 0x02, 0xaf,
	0x0c, 0x1c, 0xba, 0x66, 0xba, 0x67, 0xf0, 0x32, 0xc3, 0x58, 0xf0, 0x96, 0x12, 0x92, 0x05, 0xd8,
	0x64, 0xaa, 0x03, 0x7f, 0x1b, 0x38, 0x74, 0xdd, 0x74, 0x27, 0xe7, 0xa0, 0x75, 0x58, 0xa7, 0xdb,
	0xd6, 0xd2, 0x79, 0x67, 0xe0, 0xd0, 0x53, 0x99, 0x02, 0x8c, 0xb6, 0x86, 0x57, 0x27, 0x8f, 0x67,
	0x3e, 0x34, 0x92, 0x0e, 0xbc, 0x36, 0x70, 0x28, 0xcd, 0x04, 0xc4, 0xf8, 0xb2, 0x1e, 0xc2, 0xdf,
	0x07, 0x0e, 0x3d, 0x9b, 0x69, 0x95, 0xc6, 0xaa, 0x21, 0xcf, 0x72, 0x2b, 0xf6, 0xeb, 0x65, 0xf8,
	0xc7, 0x41, 0x72, 0x3b, 0x8a, 0x0c, 0x9f, 0xc0, 0x3f, 0x07, 0xce, 0xca, 0xcc, 0x8d, 0x2f, 0xad,
	0xde, 0x53, 0x7c, 0xcb, 0xcd, 0xdb, 0xab, 0xce, 0xad, 0xdb, 0xab, 0xce, 0x73, 0xb7, 0x57, 0x9d,
	0x47, 0x9f, 0x5f, 0xbd, 0xe7, 0x3d, 0xab, 0xd9, 0x27, 0xb7, 0x42, 0xaf, 0xb3, 0xe9, 0x09, 0x89,
	0x9b, 0x93, 0xff, 0xbb, 0xb4, 0x67, 0xcd, 0x3f, 0x1d, 0x6f, 0xfd, 0x5f, 0x00, 0x00, 0x00, 0xff,
	0xff, 0xe6, 0xee, 0x81, 0xab, 0xd4, 0x0c, 0x00, 0x00,
}
