// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: bertymessenger.proto

package bertymessenger

import (
	context "context"
	fmt "fmt"
	math "math"

	bertytypes "berty.tech/berty/v2/go/pkg/bertytypes"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type AppMessageType int32

const (
	AppMessageType_Undefined       AppMessageType = 0
	AppMessageType_UserMessage     AppMessageType = 1
	AppMessageType_UserReaction    AppMessageType = 2
	AppMessageType_GroupInvitation AppMessageType = 3
	AppMessageType_SetGroupName    AppMessageType = 4
	AppMessageType_Acknowledge     AppMessageType = 5
)

var AppMessageType_name = map[int32]string{
	0: "Undefined",
	1: "UserMessage",
	2: "UserReaction",
	3: "GroupInvitation",
	4: "SetGroupName",
	5: "Acknowledge",
}

var AppMessageType_value = map[string]int32{
	"Undefined":       0,
	"UserMessage":     1,
	"UserReaction":    2,
	"GroupInvitation": 3,
	"SetGroupName":    4,
	"Acknowledge":     5,
}

func (x AppMessageType) String() string {
	return proto.EnumName(AppMessageType_name, int32(x))
}

func (AppMessageType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_fd3bf21e238da6aa, []int{0}
}

type ParseDeepLink_Kind int32

const (
	ParseDeepLink_UnknownKind ParseDeepLink_Kind = 0
	ParseDeepLink_BertyID     ParseDeepLink_Kind = 1
	ParseDeepLink_BertyGroup  ParseDeepLink_Kind = 2
)

var ParseDeepLink_Kind_name = map[int32]string{
	0: "UnknownKind",
	1: "BertyID",
	2: "BertyGroup",
}

var ParseDeepLink_Kind_value = map[string]int32{
	"UnknownKind": 0,
	"BertyID":     1,
	"BertyGroup":  2,
}

func (x ParseDeepLink_Kind) String() string {
	return proto.EnumName(ParseDeepLink_Kind_name, int32(x))
}

func (ParseDeepLink_Kind) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_fd3bf21e238da6aa, []int{3, 0}
}

type InstanceShareableBertyID struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InstanceShareableBertyID) Reset()         { *m = InstanceShareableBertyID{} }
func (m *InstanceShareableBertyID) String() string { return proto.CompactTextString(m) }
func (*InstanceShareableBertyID) ProtoMessage()    {}
func (*InstanceShareableBertyID) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd3bf21e238da6aa, []int{0}
}
func (m *InstanceShareableBertyID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InstanceShareableBertyID.Unmarshal(m, b)
}
func (m *InstanceShareableBertyID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InstanceShareableBertyID.Marshal(b, m, deterministic)
}
func (m *InstanceShareableBertyID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InstanceShareableBertyID.Merge(m, src)
}
func (m *InstanceShareableBertyID) XXX_Size() int {
	return xxx_messageInfo_InstanceShareableBertyID.Size(m)
}
func (m *InstanceShareableBertyID) XXX_DiscardUnknown() {
	xxx_messageInfo_InstanceShareableBertyID.DiscardUnknown(m)
}

var xxx_messageInfo_InstanceShareableBertyID proto.InternalMessageInfo

type InstanceShareableBertyID_Request struct {
	// reset will regenerate a new link
	Reset_               bool     `protobuf:"varint,1,opt,name=reset,proto3" json:"reset,omitempty"`
	DisplayName          string   `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InstanceShareableBertyID_Request) Reset()         { *m = InstanceShareableBertyID_Request{} }
func (m *InstanceShareableBertyID_Request) String() string { return proto.CompactTextString(m) }
func (*InstanceShareableBertyID_Request) ProtoMessage()    {}
func (*InstanceShareableBertyID_Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd3bf21e238da6aa, []int{0, 0}
}
func (m *InstanceShareableBertyID_Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InstanceShareableBertyID_Request.Unmarshal(m, b)
}
func (m *InstanceShareableBertyID_Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InstanceShareableBertyID_Request.Marshal(b, m, deterministic)
}
func (m *InstanceShareableBertyID_Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InstanceShareableBertyID_Request.Merge(m, src)
}
func (m *InstanceShareableBertyID_Request) XXX_Size() int {
	return xxx_messageInfo_InstanceShareableBertyID_Request.Size(m)
}
func (m *InstanceShareableBertyID_Request) XXX_DiscardUnknown() {
	xxx_messageInfo_InstanceShareableBertyID_Request.DiscardUnknown(m)
}

var xxx_messageInfo_InstanceShareableBertyID_Request proto.InternalMessageInfo

func (m *InstanceShareableBertyID_Request) GetReset_() bool {
	if m != nil {
		return m.Reset_
	}
	return false
}

func (m *InstanceShareableBertyID_Request) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

type InstanceShareableBertyID_Reply struct {
	BertyID              *BertyID `protobuf:"bytes,1,opt,name=berty_id,json=bertyId,proto3" json:"berty_id,omitempty"`
	BertyIDPayload       string   `protobuf:"bytes,2,opt,name=berty_id_payload,json=bertyIdPayload,proto3" json:"berty_id_payload,omitempty"`
	DeepLink             string   `protobuf:"bytes,3,opt,name=deep_link,json=deepLink,proto3" json:"deep_link,omitempty"`
	HTMLURL              string   `protobuf:"bytes,4,opt,name=html_url,json=htmlUrl,proto3" json:"html_url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InstanceShareableBertyID_Reply) Reset()         { *m = InstanceShareableBertyID_Reply{} }
func (m *InstanceShareableBertyID_Reply) String() string { return proto.CompactTextString(m) }
func (*InstanceShareableBertyID_Reply) ProtoMessage()    {}
func (*InstanceShareableBertyID_Reply) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd3bf21e238da6aa, []int{0, 1}
}
func (m *InstanceShareableBertyID_Reply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InstanceShareableBertyID_Reply.Unmarshal(m, b)
}
func (m *InstanceShareableBertyID_Reply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InstanceShareableBertyID_Reply.Marshal(b, m, deterministic)
}
func (m *InstanceShareableBertyID_Reply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InstanceShareableBertyID_Reply.Merge(m, src)
}
func (m *InstanceShareableBertyID_Reply) XXX_Size() int {
	return xxx_messageInfo_InstanceShareableBertyID_Reply.Size(m)
}
func (m *InstanceShareableBertyID_Reply) XXX_DiscardUnknown() {
	xxx_messageInfo_InstanceShareableBertyID_Reply.DiscardUnknown(m)
}

var xxx_messageInfo_InstanceShareableBertyID_Reply proto.InternalMessageInfo

func (m *InstanceShareableBertyID_Reply) GetBertyID() *BertyID {
	if m != nil {
		return m.BertyID
	}
	return nil
}

func (m *InstanceShareableBertyID_Reply) GetBertyIDPayload() string {
	if m != nil {
		return m.BertyIDPayload
	}
	return ""
}

func (m *InstanceShareableBertyID_Reply) GetDeepLink() string {
	if m != nil {
		return m.DeepLink
	}
	return ""
}

func (m *InstanceShareableBertyID_Reply) GetHTMLURL() string {
	if m != nil {
		return m.HTMLURL
	}
	return ""
}

type ShareableBertyGroup struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShareableBertyGroup) Reset()         { *m = ShareableBertyGroup{} }
func (m *ShareableBertyGroup) String() string { return proto.CompactTextString(m) }
func (*ShareableBertyGroup) ProtoMessage()    {}
func (*ShareableBertyGroup) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd3bf21e238da6aa, []int{1}
}
func (m *ShareableBertyGroup) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShareableBertyGroup.Unmarshal(m, b)
}
func (m *ShareableBertyGroup) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShareableBertyGroup.Marshal(b, m, deterministic)
}
func (m *ShareableBertyGroup) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShareableBertyGroup.Merge(m, src)
}
func (m *ShareableBertyGroup) XXX_Size() int {
	return xxx_messageInfo_ShareableBertyGroup.Size(m)
}
func (m *ShareableBertyGroup) XXX_DiscardUnknown() {
	xxx_messageInfo_ShareableBertyGroup.DiscardUnknown(m)
}

var xxx_messageInfo_ShareableBertyGroup proto.InternalMessageInfo

type ShareableBertyGroup_Request struct {
	GroupPK              []byte   `protobuf:"bytes,1,opt,name=group_pk,json=groupPk,proto3" json:"group_pk,omitempty"`
	GroupName            string   `protobuf:"bytes,2,opt,name=group_name,json=groupName,proto3" json:"group_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShareableBertyGroup_Request) Reset()         { *m = ShareableBertyGroup_Request{} }
func (m *ShareableBertyGroup_Request) String() string { return proto.CompactTextString(m) }
func (*ShareableBertyGroup_Request) ProtoMessage()    {}
func (*ShareableBertyGroup_Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd3bf21e238da6aa, []int{1, 0}
}
func (m *ShareableBertyGroup_Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShareableBertyGroup_Request.Unmarshal(m, b)
}
func (m *ShareableBertyGroup_Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShareableBertyGroup_Request.Marshal(b, m, deterministic)
}
func (m *ShareableBertyGroup_Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShareableBertyGroup_Request.Merge(m, src)
}
func (m *ShareableBertyGroup_Request) XXX_Size() int {
	return xxx_messageInfo_ShareableBertyGroup_Request.Size(m)
}
func (m *ShareableBertyGroup_Request) XXX_DiscardUnknown() {
	xxx_messageInfo_ShareableBertyGroup_Request.DiscardUnknown(m)
}

var xxx_messageInfo_ShareableBertyGroup_Request proto.InternalMessageInfo

func (m *ShareableBertyGroup_Request) GetGroupPK() []byte {
	if m != nil {
		return m.GroupPK
	}
	return nil
}

func (m *ShareableBertyGroup_Request) GetGroupName() string {
	if m != nil {
		return m.GroupName
	}
	return ""
}

type ShareableBertyGroup_Reply struct {
	BertyGroup           *BertyGroup `protobuf:"bytes,1,opt,name=berty_group,json=bertyGroup,proto3" json:"berty_group,omitempty"`
	BertyGroupPayload    string      `protobuf:"bytes,2,opt,name=berty_group_payload,json=bertyGroupPayload,proto3" json:"berty_group_payload,omitempty"`
	DeepLink             string      `protobuf:"bytes,3,opt,name=deep_link,json=deepLink,proto3" json:"deep_link,omitempty"`
	HTMLURL              string      `protobuf:"bytes,4,opt,name=html_url,json=htmlUrl,proto3" json:"html_url,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ShareableBertyGroup_Reply) Reset()         { *m = ShareableBertyGroup_Reply{} }
func (m *ShareableBertyGroup_Reply) String() string { return proto.CompactTextString(m) }
func (*ShareableBertyGroup_Reply) ProtoMessage()    {}
func (*ShareableBertyGroup_Reply) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd3bf21e238da6aa, []int{1, 1}
}
func (m *ShareableBertyGroup_Reply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShareableBertyGroup_Reply.Unmarshal(m, b)
}
func (m *ShareableBertyGroup_Reply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShareableBertyGroup_Reply.Marshal(b, m, deterministic)
}
func (m *ShareableBertyGroup_Reply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShareableBertyGroup_Reply.Merge(m, src)
}
func (m *ShareableBertyGroup_Reply) XXX_Size() int {
	return xxx_messageInfo_ShareableBertyGroup_Reply.Size(m)
}
func (m *ShareableBertyGroup_Reply) XXX_DiscardUnknown() {
	xxx_messageInfo_ShareableBertyGroup_Reply.DiscardUnknown(m)
}

var xxx_messageInfo_ShareableBertyGroup_Reply proto.InternalMessageInfo

func (m *ShareableBertyGroup_Reply) GetBertyGroup() *BertyGroup {
	if m != nil {
		return m.BertyGroup
	}
	return nil
}

func (m *ShareableBertyGroup_Reply) GetBertyGroupPayload() string {
	if m != nil {
		return m.BertyGroupPayload
	}
	return ""
}

func (m *ShareableBertyGroup_Reply) GetDeepLink() string {
	if m != nil {
		return m.DeepLink
	}
	return ""
}

func (m *ShareableBertyGroup_Reply) GetHTMLURL() string {
	if m != nil {
		return m.HTMLURL
	}
	return ""
}

type DevShareInstanceBertyID struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DevShareInstanceBertyID) Reset()         { *m = DevShareInstanceBertyID{} }
func (m *DevShareInstanceBertyID) String() string { return proto.CompactTextString(m) }
func (*DevShareInstanceBertyID) ProtoMessage()    {}
func (*DevShareInstanceBertyID) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd3bf21e238da6aa, []int{2}
}
func (m *DevShareInstanceBertyID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DevShareInstanceBertyID.Unmarshal(m, b)
}
func (m *DevShareInstanceBertyID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DevShareInstanceBertyID.Marshal(b, m, deterministic)
}
func (m *DevShareInstanceBertyID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DevShareInstanceBertyID.Merge(m, src)
}
func (m *DevShareInstanceBertyID) XXX_Size() int {
	return xxx_messageInfo_DevShareInstanceBertyID.Size(m)
}
func (m *DevShareInstanceBertyID) XXX_DiscardUnknown() {
	xxx_messageInfo_DevShareInstanceBertyID.DiscardUnknown(m)
}

var xxx_messageInfo_DevShareInstanceBertyID proto.InternalMessageInfo

type DevShareInstanceBertyID_Request struct {
	// reset will regenerate a new link
	Reset_               bool     `protobuf:"varint,1,opt,name=reset,proto3" json:"reset,omitempty"`
	DisplayName          string   `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DevShareInstanceBertyID_Request) Reset()         { *m = DevShareInstanceBertyID_Request{} }
func (m *DevShareInstanceBertyID_Request) String() string { return proto.CompactTextString(m) }
func (*DevShareInstanceBertyID_Request) ProtoMessage()    {}
func (*DevShareInstanceBertyID_Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd3bf21e238da6aa, []int{2, 0}
}
func (m *DevShareInstanceBertyID_Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DevShareInstanceBertyID_Request.Unmarshal(m, b)
}
func (m *DevShareInstanceBertyID_Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DevShareInstanceBertyID_Request.Marshal(b, m, deterministic)
}
func (m *DevShareInstanceBertyID_Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DevShareInstanceBertyID_Request.Merge(m, src)
}
func (m *DevShareInstanceBertyID_Request) XXX_Size() int {
	return xxx_messageInfo_DevShareInstanceBertyID_Request.Size(m)
}
func (m *DevShareInstanceBertyID_Request) XXX_DiscardUnknown() {
	xxx_messageInfo_DevShareInstanceBertyID_Request.DiscardUnknown(m)
}

var xxx_messageInfo_DevShareInstanceBertyID_Request proto.InternalMessageInfo

func (m *DevShareInstanceBertyID_Request) GetReset_() bool {
	if m != nil {
		return m.Reset_
	}
	return false
}

func (m *DevShareInstanceBertyID_Request) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

type DevShareInstanceBertyID_Reply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DevShareInstanceBertyID_Reply) Reset()         { *m = DevShareInstanceBertyID_Reply{} }
func (m *DevShareInstanceBertyID_Reply) String() string { return proto.CompactTextString(m) }
func (*DevShareInstanceBertyID_Reply) ProtoMessage()    {}
func (*DevShareInstanceBertyID_Reply) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd3bf21e238da6aa, []int{2, 1}
}
func (m *DevShareInstanceBertyID_Reply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DevShareInstanceBertyID_Reply.Unmarshal(m, b)
}
func (m *DevShareInstanceBertyID_Reply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DevShareInstanceBertyID_Reply.Marshal(b, m, deterministic)
}
func (m *DevShareInstanceBertyID_Reply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DevShareInstanceBertyID_Reply.Merge(m, src)
}
func (m *DevShareInstanceBertyID_Reply) XXX_Size() int {
	return xxx_messageInfo_DevShareInstanceBertyID_Reply.Size(m)
}
func (m *DevShareInstanceBertyID_Reply) XXX_DiscardUnknown() {
	xxx_messageInfo_DevShareInstanceBertyID_Reply.DiscardUnknown(m)
}

var xxx_messageInfo_DevShareInstanceBertyID_Reply proto.InternalMessageInfo

type ParseDeepLink struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ParseDeepLink) Reset()         { *m = ParseDeepLink{} }
func (m *ParseDeepLink) String() string { return proto.CompactTextString(m) }
func (*ParseDeepLink) ProtoMessage()    {}
func (*ParseDeepLink) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd3bf21e238da6aa, []int{3}
}
func (m *ParseDeepLink) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ParseDeepLink.Unmarshal(m, b)
}
func (m *ParseDeepLink) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ParseDeepLink.Marshal(b, m, deterministic)
}
func (m *ParseDeepLink) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ParseDeepLink.Merge(m, src)
}
func (m *ParseDeepLink) XXX_Size() int {
	return xxx_messageInfo_ParseDeepLink.Size(m)
}
func (m *ParseDeepLink) XXX_DiscardUnknown() {
	xxx_messageInfo_ParseDeepLink.DiscardUnknown(m)
}

var xxx_messageInfo_ParseDeepLink proto.InternalMessageInfo

type ParseDeepLink_Request struct {
	Link                 string   `protobuf:"bytes,1,opt,name=link,proto3" json:"link,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ParseDeepLink_Request) Reset()         { *m = ParseDeepLink_Request{} }
func (m *ParseDeepLink_Request) String() string { return proto.CompactTextString(m) }
func (*ParseDeepLink_Request) ProtoMessage()    {}
func (*ParseDeepLink_Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd3bf21e238da6aa, []int{3, 0}
}
func (m *ParseDeepLink_Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ParseDeepLink_Request.Unmarshal(m, b)
}
func (m *ParseDeepLink_Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ParseDeepLink_Request.Marshal(b, m, deterministic)
}
func (m *ParseDeepLink_Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ParseDeepLink_Request.Merge(m, src)
}
func (m *ParseDeepLink_Request) XXX_Size() int {
	return xxx_messageInfo_ParseDeepLink_Request.Size(m)
}
func (m *ParseDeepLink_Request) XXX_DiscardUnknown() {
	xxx_messageInfo_ParseDeepLink_Request.DiscardUnknown(m)
}

var xxx_messageInfo_ParseDeepLink_Request proto.InternalMessageInfo

func (m *ParseDeepLink_Request) GetLink() string {
	if m != nil {
		return m.Link
	}
	return ""
}

type ParseDeepLink_Reply struct {
	Kind                 ParseDeepLink_Kind `protobuf:"varint,1,opt,name=kind,proto3,enum=berty.messenger.ParseDeepLink_Kind" json:"kind,omitempty"`
	BertyID              *BertyID           `protobuf:"bytes,3,opt,name=berty_id,json=bertyId,proto3" json:"berty_id,omitempty"`
	BertyGroup           *BertyGroup        `protobuf:"bytes,4,opt,name=berty_group,json=bertyGroup,proto3" json:"berty_group,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *ParseDeepLink_Reply) Reset()         { *m = ParseDeepLink_Reply{} }
func (m *ParseDeepLink_Reply) String() string { return proto.CompactTextString(m) }
func (*ParseDeepLink_Reply) ProtoMessage()    {}
func (*ParseDeepLink_Reply) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd3bf21e238da6aa, []int{3, 1}
}
func (m *ParseDeepLink_Reply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ParseDeepLink_Reply.Unmarshal(m, b)
}
func (m *ParseDeepLink_Reply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ParseDeepLink_Reply.Marshal(b, m, deterministic)
}
func (m *ParseDeepLink_Reply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ParseDeepLink_Reply.Merge(m, src)
}
func (m *ParseDeepLink_Reply) XXX_Size() int {
	return xxx_messageInfo_ParseDeepLink_Reply.Size(m)
}
func (m *ParseDeepLink_Reply) XXX_DiscardUnknown() {
	xxx_messageInfo_ParseDeepLink_Reply.DiscardUnknown(m)
}

var xxx_messageInfo_ParseDeepLink_Reply proto.InternalMessageInfo

func (m *ParseDeepLink_Reply) GetKind() ParseDeepLink_Kind {
	if m != nil {
		return m.Kind
	}
	return ParseDeepLink_UnknownKind
}

func (m *ParseDeepLink_Reply) GetBertyID() *BertyID {
	if m != nil {
		return m.BertyID
	}
	return nil
}

func (m *ParseDeepLink_Reply) GetBertyGroup() *BertyGroup {
	if m != nil {
		return m.BertyGroup
	}
	return nil
}

type SendContactRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendContactRequest) Reset()         { *m = SendContactRequest{} }
func (m *SendContactRequest) String() string { return proto.CompactTextString(m) }
func (*SendContactRequest) ProtoMessage()    {}
func (*SendContactRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd3bf21e238da6aa, []int{4}
}
func (m *SendContactRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendContactRequest.Unmarshal(m, b)
}
func (m *SendContactRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendContactRequest.Marshal(b, m, deterministic)
}
func (m *SendContactRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendContactRequest.Merge(m, src)
}
func (m *SendContactRequest) XXX_Size() int {
	return xxx_messageInfo_SendContactRequest.Size(m)
}
func (m *SendContactRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendContactRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendContactRequest proto.InternalMessageInfo

type SendContactRequest_Request struct {
	BertyID              *BertyID `protobuf:"bytes,1,opt,name=berty_id,json=bertyId,proto3" json:"berty_id,omitempty"`
	Metadata             []byte   `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	OwnMetadata          []byte   `protobuf:"bytes,3,opt,name=own_metadata,json=ownMetadata,proto3" json:"own_metadata,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendContactRequest_Request) Reset()         { *m = SendContactRequest_Request{} }
func (m *SendContactRequest_Request) String() string { return proto.CompactTextString(m) }
func (*SendContactRequest_Request) ProtoMessage()    {}
func (*SendContactRequest_Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd3bf21e238da6aa, []int{4, 0}
}
func (m *SendContactRequest_Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendContactRequest_Request.Unmarshal(m, b)
}
func (m *SendContactRequest_Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendContactRequest_Request.Marshal(b, m, deterministic)
}
func (m *SendContactRequest_Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendContactRequest_Request.Merge(m, src)
}
func (m *SendContactRequest_Request) XXX_Size() int {
	return xxx_messageInfo_SendContactRequest_Request.Size(m)
}
func (m *SendContactRequest_Request) XXX_DiscardUnknown() {
	xxx_messageInfo_SendContactRequest_Request.DiscardUnknown(m)
}

var xxx_messageInfo_SendContactRequest_Request proto.InternalMessageInfo

func (m *SendContactRequest_Request) GetBertyID() *BertyID {
	if m != nil {
		return m.BertyID
	}
	return nil
}

func (m *SendContactRequest_Request) GetMetadata() []byte {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *SendContactRequest_Request) GetOwnMetadata() []byte {
	if m != nil {
		return m.OwnMetadata
	}
	return nil
}

type SendContactRequest_Reply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendContactRequest_Reply) Reset()         { *m = SendContactRequest_Reply{} }
func (m *SendContactRequest_Reply) String() string { return proto.CompactTextString(m) }
func (*SendContactRequest_Reply) ProtoMessage()    {}
func (*SendContactRequest_Reply) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd3bf21e238da6aa, []int{4, 1}
}
func (m *SendContactRequest_Reply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendContactRequest_Reply.Unmarshal(m, b)
}
func (m *SendContactRequest_Reply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendContactRequest_Reply.Marshal(b, m, deterministic)
}
func (m *SendContactRequest_Reply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendContactRequest_Reply.Merge(m, src)
}
func (m *SendContactRequest_Reply) XXX_Size() int {
	return xxx_messageInfo_SendContactRequest_Reply.Size(m)
}
func (m *SendContactRequest_Reply) XXX_DiscardUnknown() {
	xxx_messageInfo_SendContactRequest_Reply.DiscardUnknown(m)
}

var xxx_messageInfo_SendContactRequest_Reply proto.InternalMessageInfo

type SendAck struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendAck) Reset()         { *m = SendAck{} }
func (m *SendAck) String() string { return proto.CompactTextString(m) }
func (*SendAck) ProtoMessage()    {}
func (*SendAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd3bf21e238da6aa, []int{5}
}
func (m *SendAck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendAck.Unmarshal(m, b)
}
func (m *SendAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendAck.Marshal(b, m, deterministic)
}
func (m *SendAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendAck.Merge(m, src)
}
func (m *SendAck) XXX_Size() int {
	return xxx_messageInfo_SendAck.Size(m)
}
func (m *SendAck) XXX_DiscardUnknown() {
	xxx_messageInfo_SendAck.DiscardUnknown(m)
}

var xxx_messageInfo_SendAck proto.InternalMessageInfo

type SendAck_Request struct {
	GroupPK              []byte   `protobuf:"bytes,1,opt,name=group_pk,json=groupPk,proto3" json:"group_pk,omitempty"`
	MessageID            []byte   `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendAck_Request) Reset()         { *m = SendAck_Request{} }
func (m *SendAck_Request) String() string { return proto.CompactTextString(m) }
func (*SendAck_Request) ProtoMessage()    {}
func (*SendAck_Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd3bf21e238da6aa, []int{5, 0}
}
func (m *SendAck_Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendAck_Request.Unmarshal(m, b)
}
func (m *SendAck_Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendAck_Request.Marshal(b, m, deterministic)
}
func (m *SendAck_Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendAck_Request.Merge(m, src)
}
func (m *SendAck_Request) XXX_Size() int {
	return xxx_messageInfo_SendAck_Request.Size(m)
}
func (m *SendAck_Request) XXX_DiscardUnknown() {
	xxx_messageInfo_SendAck_Request.DiscardUnknown(m)
}

var xxx_messageInfo_SendAck_Request proto.InternalMessageInfo

func (m *SendAck_Request) GetGroupPK() []byte {
	if m != nil {
		return m.GroupPK
	}
	return nil
}

func (m *SendAck_Request) GetMessageID() []byte {
	if m != nil {
		return m.MessageID
	}
	return nil
}

type SendAck_Reply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendAck_Reply) Reset()         { *m = SendAck_Reply{} }
func (m *SendAck_Reply) String() string { return proto.CompactTextString(m) }
func (*SendAck_Reply) ProtoMessage()    {}
func (*SendAck_Reply) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd3bf21e238da6aa, []int{5, 1}
}
func (m *SendAck_Reply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendAck_Reply.Unmarshal(m, b)
}
func (m *SendAck_Reply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendAck_Reply.Marshal(b, m, deterministic)
}
func (m *SendAck_Reply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendAck_Reply.Merge(m, src)
}
func (m *SendAck_Reply) XXX_Size() int {
	return xxx_messageInfo_SendAck_Reply.Size(m)
}
func (m *SendAck_Reply) XXX_DiscardUnknown() {
	xxx_messageInfo_SendAck_Reply.DiscardUnknown(m)
}

var xxx_messageInfo_SendAck_Reply proto.InternalMessageInfo

type SendMessage struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendMessage) Reset()         { *m = SendMessage{} }
func (m *SendMessage) String() string { return proto.CompactTextString(m) }
func (*SendMessage) ProtoMessage()    {}
func (*SendMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd3bf21e238da6aa, []int{6}
}
func (m *SendMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendMessage.Unmarshal(m, b)
}
func (m *SendMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendMessage.Marshal(b, m, deterministic)
}
func (m *SendMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendMessage.Merge(m, src)
}
func (m *SendMessage) XXX_Size() int {
	return xxx_messageInfo_SendMessage.Size(m)
}
func (m *SendMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_SendMessage.DiscardUnknown(m)
}

var xxx_messageInfo_SendMessage proto.InternalMessageInfo

type SendMessage_Request struct {
	GroupPK              []byte   `protobuf:"bytes,1,opt,name=group_pk,json=groupPk,proto3" json:"group_pk,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendMessage_Request) Reset()         { *m = SendMessage_Request{} }
func (m *SendMessage_Request) String() string { return proto.CompactTextString(m) }
func (*SendMessage_Request) ProtoMessage()    {}
func (*SendMessage_Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd3bf21e238da6aa, []int{6, 0}
}
func (m *SendMessage_Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendMessage_Request.Unmarshal(m, b)
}
func (m *SendMessage_Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendMessage_Request.Marshal(b, m, deterministic)
}
func (m *SendMessage_Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendMessage_Request.Merge(m, src)
}
func (m *SendMessage_Request) XXX_Size() int {
	return xxx_messageInfo_SendMessage_Request.Size(m)
}
func (m *SendMessage_Request) XXX_DiscardUnknown() {
	xxx_messageInfo_SendMessage_Request.DiscardUnknown(m)
}

var xxx_messageInfo_SendMessage_Request proto.InternalMessageInfo

func (m *SendMessage_Request) GetGroupPK() []byte {
	if m != nil {
		return m.GroupPK
	}
	return nil
}

func (m *SendMessage_Request) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type SendMessage_Reply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendMessage_Reply) Reset()         { *m = SendMessage_Reply{} }
func (m *SendMessage_Reply) String() string { return proto.CompactTextString(m) }
func (*SendMessage_Reply) ProtoMessage()    {}
func (*SendMessage_Reply) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd3bf21e238da6aa, []int{6, 1}
}
func (m *SendMessage_Reply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendMessage_Reply.Unmarshal(m, b)
}
func (m *SendMessage_Reply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendMessage_Reply.Marshal(b, m, deterministic)
}
func (m *SendMessage_Reply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendMessage_Reply.Merge(m, src)
}
func (m *SendMessage_Reply) XXX_Size() int {
	return xxx_messageInfo_SendMessage_Reply.Size(m)
}
func (m *SendMessage_Reply) XXX_DiscardUnknown() {
	xxx_messageInfo_SendMessage_Reply.DiscardUnknown(m)
}

var xxx_messageInfo_SendMessage_Reply proto.InternalMessageInfo

type BertyID struct {
	PublicRendezvousSeed []byte   `protobuf:"bytes,1,opt,name=public_rendezvous_seed,json=publicRendezvousSeed,proto3" json:"public_rendezvous_seed,omitempty"`
	AccountPK            []byte   `protobuf:"bytes,2,opt,name=account_pk,json=accountPk,proto3" json:"account_pk,omitempty"`
	DisplayName          string   `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BertyID) Reset()         { *m = BertyID{} }
func (m *BertyID) String() string { return proto.CompactTextString(m) }
func (*BertyID) ProtoMessage()    {}
func (*BertyID) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd3bf21e238da6aa, []int{7}
}
func (m *BertyID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BertyID.Unmarshal(m, b)
}
func (m *BertyID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BertyID.Marshal(b, m, deterministic)
}
func (m *BertyID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BertyID.Merge(m, src)
}
func (m *BertyID) XXX_Size() int {
	return xxx_messageInfo_BertyID.Size(m)
}
func (m *BertyID) XXX_DiscardUnknown() {
	xxx_messageInfo_BertyID.DiscardUnknown(m)
}

var xxx_messageInfo_BertyID proto.InternalMessageInfo

func (m *BertyID) GetPublicRendezvousSeed() []byte {
	if m != nil {
		return m.PublicRendezvousSeed
	}
	return nil
}

func (m *BertyID) GetAccountPK() []byte {
	if m != nil {
		return m.AccountPK
	}
	return nil
}

func (m *BertyID) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

type BertyGroup struct {
	Group                *bertytypes.Group `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	DisplayName          string            `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *BertyGroup) Reset()         { *m = BertyGroup{} }
func (m *BertyGroup) String() string { return proto.CompactTextString(m) }
func (*BertyGroup) ProtoMessage()    {}
func (*BertyGroup) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd3bf21e238da6aa, []int{8}
}
func (m *BertyGroup) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BertyGroup.Unmarshal(m, b)
}
func (m *BertyGroup) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BertyGroup.Marshal(b, m, deterministic)
}
func (m *BertyGroup) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BertyGroup.Merge(m, src)
}
func (m *BertyGroup) XXX_Size() int {
	return xxx_messageInfo_BertyGroup.Size(m)
}
func (m *BertyGroup) XXX_DiscardUnknown() {
	xxx_messageInfo_BertyGroup.DiscardUnknown(m)
}

var xxx_messageInfo_BertyGroup proto.InternalMessageInfo

func (m *BertyGroup) GetGroup() *bertytypes.Group {
	if m != nil {
		return m.Group
	}
	return nil
}

func (m *BertyGroup) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

type AppMessageTyped struct {
	Type                 AppMessageType `protobuf:"varint,1,opt,name=type,proto3,enum=berty.messenger.AppMessageType" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *AppMessageTyped) Reset()         { *m = AppMessageTyped{} }
func (m *AppMessageTyped) String() string { return proto.CompactTextString(m) }
func (*AppMessageTyped) ProtoMessage()    {}
func (*AppMessageTyped) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd3bf21e238da6aa, []int{9}
}
func (m *AppMessageTyped) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppMessageTyped.Unmarshal(m, b)
}
func (m *AppMessageTyped) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppMessageTyped.Marshal(b, m, deterministic)
}
func (m *AppMessageTyped) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppMessageTyped.Merge(m, src)
}
func (m *AppMessageTyped) XXX_Size() int {
	return xxx_messageInfo_AppMessageTyped.Size(m)
}
func (m *AppMessageTyped) XXX_DiscardUnknown() {
	xxx_messageInfo_AppMessageTyped.DiscardUnknown(m)
}

var xxx_messageInfo_AppMessageTyped proto.InternalMessageInfo

func (m *AppMessageTyped) GetType() AppMessageType {
	if m != nil {
		return m.Type
	}
	return AppMessageType_Undefined
}

type UserMessageAttachment struct {
	Type                 AppMessageType `protobuf:"varint,1,opt,name=type,proto3,enum=berty.messenger.AppMessageType" json:"type,omitempty"`
	Uri                  string         `protobuf:"bytes,2,opt,name=uri,proto3" json:"uri,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *UserMessageAttachment) Reset()         { *m = UserMessageAttachment{} }
func (m *UserMessageAttachment) String() string { return proto.CompactTextString(m) }
func (*UserMessageAttachment) ProtoMessage()    {}
func (*UserMessageAttachment) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd3bf21e238da6aa, []int{10}
}
func (m *UserMessageAttachment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserMessageAttachment.Unmarshal(m, b)
}
func (m *UserMessageAttachment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserMessageAttachment.Marshal(b, m, deterministic)
}
func (m *UserMessageAttachment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserMessageAttachment.Merge(m, src)
}
func (m *UserMessageAttachment) XXX_Size() int {
	return xxx_messageInfo_UserMessageAttachment.Size(m)
}
func (m *UserMessageAttachment) XXX_DiscardUnknown() {
	xxx_messageInfo_UserMessageAttachment.DiscardUnknown(m)
}

var xxx_messageInfo_UserMessageAttachment proto.InternalMessageInfo

func (m *UserMessageAttachment) GetType() AppMessageType {
	if m != nil {
		return m.Type
	}
	return AppMessageType_Undefined
}

func (m *UserMessageAttachment) GetUri() string {
	if m != nil {
		return m.Uri
	}
	return ""
}

type PayloadUserMessage struct {
	Type                 AppMessageType           `protobuf:"varint,1,opt,name=type,proto3,enum=berty.messenger.AppMessageType" json:"type,omitempty"`
	Body                 string                   `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	Attachments          []*UserMessageAttachment `protobuf:"bytes,3,rep,name=attachments,proto3" json:"attachments,omitempty"`
	SentDate             int64                    `protobuf:"varint,4,opt,name=sent_date,json=sentDate,proto3" json:"sentDate"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *PayloadUserMessage) Reset()         { *m = PayloadUserMessage{} }
func (m *PayloadUserMessage) String() string { return proto.CompactTextString(m) }
func (*PayloadUserMessage) ProtoMessage()    {}
func (*PayloadUserMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd3bf21e238da6aa, []int{11}
}
func (m *PayloadUserMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PayloadUserMessage.Unmarshal(m, b)
}
func (m *PayloadUserMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PayloadUserMessage.Marshal(b, m, deterministic)
}
func (m *PayloadUserMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PayloadUserMessage.Merge(m, src)
}
func (m *PayloadUserMessage) XXX_Size() int {
	return xxx_messageInfo_PayloadUserMessage.Size(m)
}
func (m *PayloadUserMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_PayloadUserMessage.DiscardUnknown(m)
}

var xxx_messageInfo_PayloadUserMessage proto.InternalMessageInfo

func (m *PayloadUserMessage) GetType() AppMessageType {
	if m != nil {
		return m.Type
	}
	return AppMessageType_Undefined
}

func (m *PayloadUserMessage) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func (m *PayloadUserMessage) GetAttachments() []*UserMessageAttachment {
	if m != nil {
		return m.Attachments
	}
	return nil
}

func (m *PayloadUserMessage) GetSentDate() int64 {
	if m != nil {
		return m.SentDate
	}
	return 0
}

type PayloadUserReaction struct {
	Type                 AppMessageType `protobuf:"varint,1,opt,name=type,proto3,enum=berty.messenger.AppMessageType" json:"type,omitempty"`
	Emoji                string         `protobuf:"bytes,2,opt,name=emoji,proto3" json:"emoji,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *PayloadUserReaction) Reset()         { *m = PayloadUserReaction{} }
func (m *PayloadUserReaction) String() string { return proto.CompactTextString(m) }
func (*PayloadUserReaction) ProtoMessage()    {}
func (*PayloadUserReaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd3bf21e238da6aa, []int{12}
}
func (m *PayloadUserReaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PayloadUserReaction.Unmarshal(m, b)
}
func (m *PayloadUserReaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PayloadUserReaction.Marshal(b, m, deterministic)
}
func (m *PayloadUserReaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PayloadUserReaction.Merge(m, src)
}
func (m *PayloadUserReaction) XXX_Size() int {
	return xxx_messageInfo_PayloadUserReaction.Size(m)
}
func (m *PayloadUserReaction) XXX_DiscardUnknown() {
	xxx_messageInfo_PayloadUserReaction.DiscardUnknown(m)
}

var xxx_messageInfo_PayloadUserReaction proto.InternalMessageInfo

func (m *PayloadUserReaction) GetType() AppMessageType {
	if m != nil {
		return m.Type
	}
	return AppMessageType_Undefined
}

func (m *PayloadUserReaction) GetEmoji() string {
	if m != nil {
		return m.Emoji
	}
	return ""
}

type PayloadGroupInvitation struct {
	Type                 AppMessageType `protobuf:"varint,1,opt,name=type,proto3,enum=berty.messenger.AppMessageType" json:"type,omitempty"`
	GroupPk              string         `protobuf:"bytes,2,opt,name=group_pk,json=groupPk,proto3" json:"groupPk"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *PayloadGroupInvitation) Reset()         { *m = PayloadGroupInvitation{} }
func (m *PayloadGroupInvitation) String() string { return proto.CompactTextString(m) }
func (*PayloadGroupInvitation) ProtoMessage()    {}
func (*PayloadGroupInvitation) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd3bf21e238da6aa, []int{13}
}
func (m *PayloadGroupInvitation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PayloadGroupInvitation.Unmarshal(m, b)
}
func (m *PayloadGroupInvitation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PayloadGroupInvitation.Marshal(b, m, deterministic)
}
func (m *PayloadGroupInvitation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PayloadGroupInvitation.Merge(m, src)
}
func (m *PayloadGroupInvitation) XXX_Size() int {
	return xxx_messageInfo_PayloadGroupInvitation.Size(m)
}
func (m *PayloadGroupInvitation) XXX_DiscardUnknown() {
	xxx_messageInfo_PayloadGroupInvitation.DiscardUnknown(m)
}

var xxx_messageInfo_PayloadGroupInvitation proto.InternalMessageInfo

func (m *PayloadGroupInvitation) GetType() AppMessageType {
	if m != nil {
		return m.Type
	}
	return AppMessageType_Undefined
}

func (m *PayloadGroupInvitation) GetGroupPk() string {
	if m != nil {
		return m.GroupPk
	}
	return ""
}

type PayloadSetGroupName struct {
	Type                 AppMessageType `protobuf:"varint,1,opt,name=type,proto3,enum=berty.messenger.AppMessageType" json:"type,omitempty"`
	Name                 string         `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *PayloadSetGroupName) Reset()         { *m = PayloadSetGroupName{} }
func (m *PayloadSetGroupName) String() string { return proto.CompactTextString(m) }
func (*PayloadSetGroupName) ProtoMessage()    {}
func (*PayloadSetGroupName) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd3bf21e238da6aa, []int{14}
}
func (m *PayloadSetGroupName) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PayloadSetGroupName.Unmarshal(m, b)
}
func (m *PayloadSetGroupName) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PayloadSetGroupName.Marshal(b, m, deterministic)
}
func (m *PayloadSetGroupName) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PayloadSetGroupName.Merge(m, src)
}
func (m *PayloadSetGroupName) XXX_Size() int {
	return xxx_messageInfo_PayloadSetGroupName.Size(m)
}
func (m *PayloadSetGroupName) XXX_DiscardUnknown() {
	xxx_messageInfo_PayloadSetGroupName.DiscardUnknown(m)
}

var xxx_messageInfo_PayloadSetGroupName proto.InternalMessageInfo

func (m *PayloadSetGroupName) GetType() AppMessageType {
	if m != nil {
		return m.Type
	}
	return AppMessageType_Undefined
}

func (m *PayloadSetGroupName) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type PayloadAcknowledge struct {
	Type                 AppMessageType `protobuf:"varint,1,opt,name=type,proto3,enum=berty.messenger.AppMessageType" json:"type,omitempty"`
	Target               string         `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *PayloadAcknowledge) Reset()         { *m = PayloadAcknowledge{} }
func (m *PayloadAcknowledge) String() string { return proto.CompactTextString(m) }
func (*PayloadAcknowledge) ProtoMessage()    {}
func (*PayloadAcknowledge) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd3bf21e238da6aa, []int{15}
}
func (m *PayloadAcknowledge) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PayloadAcknowledge.Unmarshal(m, b)
}
func (m *PayloadAcknowledge) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PayloadAcknowledge.Marshal(b, m, deterministic)
}
func (m *PayloadAcknowledge) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PayloadAcknowledge.Merge(m, src)
}
func (m *PayloadAcknowledge) XXX_Size() int {
	return xxx_messageInfo_PayloadAcknowledge.Size(m)
}
func (m *PayloadAcknowledge) XXX_DiscardUnknown() {
	xxx_messageInfo_PayloadAcknowledge.DiscardUnknown(m)
}

var xxx_messageInfo_PayloadAcknowledge proto.InternalMessageInfo

func (m *PayloadAcknowledge) GetType() AppMessageType {
	if m != nil {
		return m.Type
	}
	return AppMessageType_Undefined
}

func (m *PayloadAcknowledge) GetTarget() string {
	if m != nil {
		return m.Target
	}
	return ""
}

type SystemInfo struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SystemInfo) Reset()         { *m = SystemInfo{} }
func (m *SystemInfo) String() string { return proto.CompactTextString(m) }
func (*SystemInfo) ProtoMessage()    {}
func (*SystemInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd3bf21e238da6aa, []int{16}
}
func (m *SystemInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SystemInfo.Unmarshal(m, b)
}
func (m *SystemInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SystemInfo.Marshal(b, m, deterministic)
}
func (m *SystemInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SystemInfo.Merge(m, src)
}
func (m *SystemInfo) XXX_Size() int {
	return xxx_messageInfo_SystemInfo.Size(m)
}
func (m *SystemInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_SystemInfo.DiscardUnknown(m)
}

var xxx_messageInfo_SystemInfo proto.InternalMessageInfo

type SystemInfo_Request struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SystemInfo_Request) Reset()         { *m = SystemInfo_Request{} }
func (m *SystemInfo_Request) String() string { return proto.CompactTextString(m) }
func (*SystemInfo_Request) ProtoMessage()    {}
func (*SystemInfo_Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd3bf21e238da6aa, []int{16, 0}
}
func (m *SystemInfo_Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SystemInfo_Request.Unmarshal(m, b)
}
func (m *SystemInfo_Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SystemInfo_Request.Marshal(b, m, deterministic)
}
func (m *SystemInfo_Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SystemInfo_Request.Merge(m, src)
}
func (m *SystemInfo_Request) XXX_Size() int {
	return xxx_messageInfo_SystemInfo_Request.Size(m)
}
func (m *SystemInfo_Request) XXX_DiscardUnknown() {
	xxx_messageInfo_SystemInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_SystemInfo_Request proto.InternalMessageInfo

type SystemInfo_Reply struct {
	StartedAt            int64    `protobuf:"varint,1,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	NumCPU               int64    `protobuf:"varint,2,opt,name=num_cpu,json=numCpu,proto3" json:"num_cpu,omitempty"`
	GoVersion            string   `protobuf:"bytes,3,opt,name=go_version,json=goVersion,proto3" json:"go_version,omitempty"`
	NumGoroutine         int64    `protobuf:"varint,4,opt,name=num_goroutine,json=numGoroutine,proto3" json:"num_goroutine,omitempty"`
	OperatingSystem      string   `protobuf:"bytes,5,opt,name=operating_system,json=operatingSystem,proto3" json:"operating_system,omitempty"`
	HostName             string   `protobuf:"bytes,6,opt,name=host_name,json=hostName,proto3" json:"host_name,omitempty"`
	Arch                 string   `protobuf:"bytes,7,opt,name=arch,proto3" json:"arch,omitempty"`
	Version              string   `protobuf:"bytes,8,opt,name=version,proto3" json:"version,omitempty"`
	VcsRef               string   `protobuf:"bytes,9,opt,name=vcs_ref,json=vcsRef,proto3" json:"vcs_ref,omitempty"`
	BuildTime            int64    `protobuf:"varint,10,opt,name=build_time,json=buildTime,proto3" json:"build_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SystemInfo_Reply) Reset()         { *m = SystemInfo_Reply{} }
func (m *SystemInfo_Reply) String() string { return proto.CompactTextString(m) }
func (*SystemInfo_Reply) ProtoMessage()    {}
func (*SystemInfo_Reply) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd3bf21e238da6aa, []int{16, 1}
}
func (m *SystemInfo_Reply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SystemInfo_Reply.Unmarshal(m, b)
}
func (m *SystemInfo_Reply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SystemInfo_Reply.Marshal(b, m, deterministic)
}
func (m *SystemInfo_Reply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SystemInfo_Reply.Merge(m, src)
}
func (m *SystemInfo_Reply) XXX_Size() int {
	return xxx_messageInfo_SystemInfo_Reply.Size(m)
}
func (m *SystemInfo_Reply) XXX_DiscardUnknown() {
	xxx_messageInfo_SystemInfo_Reply.DiscardUnknown(m)
}

var xxx_messageInfo_SystemInfo_Reply proto.InternalMessageInfo

func (m *SystemInfo_Reply) GetStartedAt() int64 {
	if m != nil {
		return m.StartedAt
	}
	return 0
}

func (m *SystemInfo_Reply) GetNumCPU() int64 {
	if m != nil {
		return m.NumCPU
	}
	return 0
}

func (m *SystemInfo_Reply) GetGoVersion() string {
	if m != nil {
		return m.GoVersion
	}
	return ""
}

func (m *SystemInfo_Reply) GetNumGoroutine() int64 {
	if m != nil {
		return m.NumGoroutine
	}
	return 0
}

func (m *SystemInfo_Reply) GetOperatingSystem() string {
	if m != nil {
		return m.OperatingSystem
	}
	return ""
}

func (m *SystemInfo_Reply) GetHostName() string {
	if m != nil {
		return m.HostName
	}
	return ""
}

func (m *SystemInfo_Reply) GetArch() string {
	if m != nil {
		return m.Arch
	}
	return ""
}

func (m *SystemInfo_Reply) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *SystemInfo_Reply) GetVcsRef() string {
	if m != nil {
		return m.VcsRef
	}
	return ""
}

func (m *SystemInfo_Reply) GetBuildTime() int64 {
	if m != nil {
		return m.BuildTime
	}
	return 0
}

func init() {
	proto.RegisterEnum("berty.messenger.AppMessageType", AppMessageType_name, AppMessageType_value)
	proto.RegisterEnum("berty.messenger.ParseDeepLink_Kind", ParseDeepLink_Kind_name, ParseDeepLink_Kind_value)
	proto.RegisterType((*InstanceShareableBertyID)(nil), "berty.messenger.InstanceShareableBertyID")
	proto.RegisterType((*InstanceShareableBertyID_Request)(nil), "berty.messenger.InstanceShareableBertyID.Request")
	proto.RegisterType((*InstanceShareableBertyID_Reply)(nil), "berty.messenger.InstanceShareableBertyID.Reply")
	proto.RegisterType((*ShareableBertyGroup)(nil), "berty.messenger.ShareableBertyGroup")
	proto.RegisterType((*ShareableBertyGroup_Request)(nil), "berty.messenger.ShareableBertyGroup.Request")
	proto.RegisterType((*ShareableBertyGroup_Reply)(nil), "berty.messenger.ShareableBertyGroup.Reply")
	proto.RegisterType((*DevShareInstanceBertyID)(nil), "berty.messenger.DevShareInstanceBertyID")
	proto.RegisterType((*DevShareInstanceBertyID_Request)(nil), "berty.messenger.DevShareInstanceBertyID.Request")
	proto.RegisterType((*DevShareInstanceBertyID_Reply)(nil), "berty.messenger.DevShareInstanceBertyID.Reply")
	proto.RegisterType((*ParseDeepLink)(nil), "berty.messenger.ParseDeepLink")
	proto.RegisterType((*ParseDeepLink_Request)(nil), "berty.messenger.ParseDeepLink.Request")
	proto.RegisterType((*ParseDeepLink_Reply)(nil), "berty.messenger.ParseDeepLink.Reply")
	proto.RegisterType((*SendContactRequest)(nil), "berty.messenger.SendContactRequest")
	proto.RegisterType((*SendContactRequest_Request)(nil), "berty.messenger.SendContactRequest.Request")
	proto.RegisterType((*SendContactRequest_Reply)(nil), "berty.messenger.SendContactRequest.Reply")
	proto.RegisterType((*SendAck)(nil), "berty.messenger.SendAck")
	proto.RegisterType((*SendAck_Request)(nil), "berty.messenger.SendAck.Request")
	proto.RegisterType((*SendAck_Reply)(nil), "berty.messenger.SendAck.Reply")
	proto.RegisterType((*SendMessage)(nil), "berty.messenger.SendMessage")
	proto.RegisterType((*SendMessage_Request)(nil), "berty.messenger.SendMessage.Request")
	proto.RegisterType((*SendMessage_Reply)(nil), "berty.messenger.SendMessage.Reply")
	proto.RegisterType((*BertyID)(nil), "berty.messenger.BertyID")
	proto.RegisterType((*BertyGroup)(nil), "berty.messenger.BertyGroup")
	proto.RegisterType((*AppMessageTyped)(nil), "berty.messenger.AppMessageTyped")
	proto.RegisterType((*UserMessageAttachment)(nil), "berty.messenger.UserMessageAttachment")
	proto.RegisterType((*PayloadUserMessage)(nil), "berty.messenger.PayloadUserMessage")
	proto.RegisterType((*PayloadUserReaction)(nil), "berty.messenger.PayloadUserReaction")
	proto.RegisterType((*PayloadGroupInvitation)(nil), "berty.messenger.PayloadGroupInvitation")
	proto.RegisterType((*PayloadSetGroupName)(nil), "berty.messenger.PayloadSetGroupName")
	proto.RegisterType((*PayloadAcknowledge)(nil), "berty.messenger.PayloadAcknowledge")
	proto.RegisterType((*SystemInfo)(nil), "berty.messenger.SystemInfo")
	proto.RegisterType((*SystemInfo_Request)(nil), "berty.messenger.SystemInfo.Request")
	proto.RegisterType((*SystemInfo_Reply)(nil), "berty.messenger.SystemInfo.Reply")
}

func init() { proto.RegisterFile("bertymessenger.proto", fileDescriptor_fd3bf21e238da6aa) }

var fileDescriptor_fd3bf21e238da6aa = []byte{
	// 1505 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x58, 0x41, 0x6f, 0x1b, 0x45,
	0x14, 0x66, 0x6d, 0x27, 0xb6, 0x9f, 0x9d, 0xc4, 0x9d, 0xa4, 0xad, 0x71, 0x49, 0x9d, 0x6e, 0xda,
	0x28, 0x4d, 0x8b, 0xdd, 0xa6, 0x95, 0x90, 0x2a, 0x0e, 0xd8, 0x0d, 0xb4, 0x51, 0x92, 0xca, 0xda,
	0x34, 0x48, 0x70, 0xe8, 0xb2, 0xde, 0x9d, 0x38, 0x8b, 0xbd, 0x33, 0xcb, 0xee, 0xac, 0x2b, 0x57,
	0xe2, 0x82, 0xc4, 0x85, 0x13, 0x12, 0x27, 0xfe, 0x02, 0x12, 0x07, 0x4e, 0x1c, 0x10, 0xff, 0x01,
	0xc1, 0x01, 0xc1, 0xc1, 0x87, 0x88, 0x53, 0x2f, 0x5c, 0xf8, 0x01, 0x68, 0x66, 0x67, 0xd7, 0xeb,
	0x38, 0x69, 0x9b, 0x14, 0x6e, 0x33, 0x6f, 0xbe, 0x79, 0xef, 0x9b, 0x6f, 0xde, 0x9b, 0x7d, 0x36,
	0x2c, 0xb4, 0xb1, 0xc7, 0x06, 0x0e, 0xf6, 0x7d, 0x4c, 0x3a, 0xd8, 0xab, 0xb9, 0x1e, 0x65, 0x14,
	0xcd, 0x09, 0x6b, 0x2d, 0x36, 0x57, 0xde, 0xee, 0xd8, 0xec, 0x20, 0x68, 0xd7, 0x4c, 0xea, 0xd4,
	0x3b, 0xb4, 0x43, 0xeb, 0x02, 0xd7, 0x0e, 0xf6, 0xc5, 0x4c, 0x4c, 0xc4, 0x28, 0xdc, 0x5f, 0x79,
	0xab, 0x43, 0x69, 0xa7, 0x87, 0xeb, 0x86, 0x6b, 0xd7, 0x0d, 0x42, 0x28, 0x33, 0x98, 0x4d, 0x89,
	0x2f, 0x57, 0x4b, 0xc2, 0x3b, 0x1b, 0xb8, 0x58, 0x5a, 0xd4, 0x9f, 0x52, 0x50, 0xde, 0x24, 0x3e,
	0x33, 0x88, 0x89, 0x77, 0x0f, 0x0c, 0x0f, 0x1b, 0xed, 0x1e, 0x6e, 0x72, 0xd4, 0xe6, 0x46, 0xa5,
	0x09, 0x59, 0x0d, 0x7f, 0x16, 0x60, 0x9f, 0xa1, 0x05, 0x98, 0xf2, 0xb0, 0x8f, 0x59, 0x59, 0x59,
	0x52, 0x56, 0x73, 0x5a, 0x38, 0x41, 0x57, 0xa0, 0x68, 0xd9, 0xbe, 0xdb, 0x33, 0x06, 0x3a, 0x31,
	0x1c, 0x5c, 0x4e, 0x2d, 0x29, 0xab, 0x79, 0xad, 0x20, 0x6d, 0x8f, 0x0c, 0x07, 0x57, 0xfe, 0x54,
	0x60, 0x4a, 0xc3, 0x6e, 0x6f, 0x80, 0xde, 0x83, 0x9c, 0x08, 0xaf, 0xdb, 0x96, 0xf0, 0x52, 0x58,
	0x2f, 0xd7, 0x8e, 0x9c, 0xb6, 0x26, 0x23, 0x37, 0x0b, 0x87, 0xc3, 0x6a, 0x56, 0x4e, 0xb4, 0xac,
	0x40, 0x6d, 0x5a, 0xe8, 0x5d, 0x28, 0x45, 0x1e, 0x74, 0xd7, 0x18, 0xf4, 0xa8, 0x61, 0x85, 0x21,
	0x9b, 0xe8, 0x70, 0x58, 0x9d, 0x95, 0xf8, 0x56, 0xb8, 0xa2, 0xcd, 0xca, 0x6d, 0x72, 0x8e, 0xae,
	0x43, 0xde, 0xc2, 0xd8, 0xd5, 0x7b, 0x36, 0xe9, 0x96, 0xd3, 0x62, 0x5b, 0xf1, 0x70, 0x58, 0xcd,
	0x6d, 0x60, 0xec, 0x6e, 0xdb, 0xa4, 0xab, 0xe5, 0x2c, 0x39, 0x42, 0x2b, 0x90, 0x3b, 0x60, 0x4e,
	0x4f, 0x0f, 0xbc, 0x5e, 0x39, 0x23, 0x90, 0x82, 0xd0, 0xc3, 0xc7, 0x3b, 0xdb, 0x7b, 0xda, 0xb6,
	0x96, 0xe5, 0x8b, 0x7b, 0x5e, 0x4f, 0xfd, 0x23, 0x05, 0xf3, 0xe3, 0xaa, 0x3d, 0xf0, 0x68, 0xe0,
	0x56, 0x5a, 0x23, 0xe1, 0x56, 0x20, 0xd7, 0xe1, 0x36, 0xdd, 0xed, 0x8a, 0x53, 0x17, 0x43, 0x57,
	0x02, 0xd7, 0xda, 0xd2, 0xb2, 0x62, 0xb1, 0xd5, 0x45, 0x8b, 0x00, 0x21, 0x2e, 0x21, 0x64, 0x5e,
	0x58, 0x84, 0x8c, 0x7f, 0xc7, 0x32, 0x6e, 0x43, 0x21, 0x14, 0x41, 0x2c, 0x4a, 0x25, 0x2f, 0x1d,
	0xaf, 0xa4, 0x88, 0xd2, 0x9c, 0x3d, 0x1c, 0x56, 0x61, 0x34, 0xd7, 0xa0, 0x1d, 0x8f, 0xd1, 0xfb,
	0x30, 0x9f, 0xf0, 0x76, 0x44, 0xd5, 0xf3, 0x87, 0xc3, 0xea, 0xb9, 0xd1, 0xc6, 0x48, 0xd8, 0x73,
	0xed, 0xa3, 0xa6, 0xff, 0x43, 0xdb, 0x7d, 0xb8, 0xb8, 0x81, 0xfb, 0x42, 0xdd, 0x28, 0x41, 0xff,
	0xcb, 0xbc, 0xcc, 0x4a, 0x3d, 0xd5, 0x1f, 0x53, 0x30, 0xd3, 0x32, 0x3c, 0x1f, 0x47, 0x5c, 0x2b,
	0x8b, 0x23, 0xf7, 0x08, 0x32, 0xe2, 0x48, 0x8a, 0x70, 0x20, 0xc6, 0x95, 0x5f, 0xe2, 0xab, 0x78,
	0x07, 0x32, 0x5d, 0x9b, 0x84, 0xd9, 0x3c, 0xbb, 0xbe, 0x3c, 0x71, 0x07, 0x63, 0x6e, 0x6b, 0x5b,
	0x36, 0xb1, 0x34, 0xb1, 0x61, 0xac, 0x14, 0xd2, 0x67, 0x2a, 0x85, 0x23, 0x59, 0x90, 0x79, 0xad,
	0x2c, 0x50, 0xef, 0x42, 0x86, 0xb3, 0x43, 0x73, 0x50, 0xd8, 0x23, 0x5d, 0x42, 0x9f, 0x12, 0x3e,
	0x2d, 0xbd, 0x81, 0x0a, 0x10, 0x85, 0x2e, 0x29, 0x68, 0x16, 0x12, 0xfb, 0x4b, 0x29, 0xf5, 0x3b,
	0x05, 0xd0, 0x2e, 0x26, 0xd6, 0x7d, 0x4a, 0x98, 0x61, 0x32, 0xa9, 0x59, 0xe5, 0x2b, 0x65, 0xa4,
	0xdf, 0xeb, 0xd7, 0x7c, 0x05, 0x72, 0x0e, 0x66, 0x86, 0x65, 0x30, 0x43, 0x5c, 0x63, 0x51, 0x8b,
	0xe7, 0xfc, 0x9a, 0xe9, 0x53, 0xa2, 0xc7, 0xeb, 0x69, 0xb1, 0x5e, 0xa0, 0x4f, 0xc9, 0x8e, 0x34,
	0x8d, 0xae, 0xd9, 0x87, 0x2c, 0xe7, 0xda, 0x30, 0xbb, 0x15, 0xfd, 0xf4, 0xd5, 0x79, 0x13, 0x80,
	0x13, 0x36, 0x3a, 0x98, 0x9f, 0x44, 0xf0, 0x68, 0xce, 0x1c, 0x0e, 0xab, 0xf9, 0x9d, 0xd0, 0xba,
	0xb9, 0xa1, 0xe5, 0x25, 0x60, 0xd3, 0x1a, 0x05, 0x35, 0xa1, 0xc0, 0x83, 0x4a, 0x50, 0x65, 0xeb,
	0xf4, 0x81, 0xcb, 0x90, 0x95, 0x7e, 0x65, 0x12, 0x47, 0xd3, 0x51, 0x90, 0xaf, 0x95, 0xf8, 0x92,
	0xd0, 0x5d, 0xb8, 0xe0, 0x06, 0xed, 0x9e, 0x6d, 0xea, 0x1e, 0x26, 0x16, 0x7e, 0xd6, 0xa7, 0x81,
	0xaf, 0xfb, 0x18, 0x87, 0xea, 0x17, 0xb5, 0x85, 0x70, 0x55, 0x8b, 0x17, 0x77, 0x31, 0xb6, 0xf8,
	0xe9, 0x0c, 0xd3, 0xa4, 0x01, 0x61, 0x9c, 0x4e, 0xe2, 0x74, 0x8d, 0xd0, 0xda, 0xda, 0xd2, 0xf2,
	0x12, 0xd0, 0xea, 0x4e, 0x14, 0x57, 0x7a, 0xa2, 0xb8, 0xd4, 0x8f, 0x92, 0x99, 0x82, 0x56, 0x61,
	0x2a, 0xf9, 0x56, 0x21, 0x99, 0x01, 0xe1, 0x67, 0x28, 0x4c, 0xc6, 0x10, 0xf0, 0x0a, 0x75, 0xab,
	0x7e, 0x00, 0x73, 0x0d, 0xd7, 0x95, 0x8a, 0x3e, 0x1e, 0xb8, 0xd8, 0x42, 0x77, 0x20, 0xc3, 0x7d,
	0xc9, 0x32, 0xac, 0x4e, 0x24, 0xd8, 0x38, 0x5e, 0x13, 0x60, 0xf5, 0x09, 0x9c, 0xdf, 0xf3, 0xb1,
	0x27, 0x17, 0x1a, 0x8c, 0x19, 0xe6, 0x81, 0x83, 0x09, 0x3b, 0x93, 0x37, 0x54, 0x82, 0x74, 0xe0,
	0xd9, 0x92, 0x2f, 0x1f, 0xaa, 0xbf, 0x2a, 0x80, 0xe4, 0xeb, 0x98, 0x88, 0x73, 0x36, 0xef, 0x08,
	0x32, 0x6d, 0x6a, 0x0d, 0xa4, 0x7b, 0x31, 0x46, 0x0f, 0xa1, 0x60, 0xc4, 0xa4, 0xfd, 0x72, 0x7a,
	0x29, 0xbd, 0x5a, 0x58, 0x5f, 0x99, 0xf0, 0x77, 0xec, 0x19, 0xb5, 0xe4, 0x56, 0xfe, 0x76, 0xfb,
	0x98, 0x30, 0xdd, 0x32, 0x18, 0x16, 0x0f, 0x49, 0xba, 0x59, 0x7c, 0x3e, 0xac, 0xe6, 0xb8, 0x71,
	0xc3, 0x60, 0x58, 0x8b, 0x47, 0xea, 0x27, 0x30, 0x9f, 0x38, 0x93, 0x86, 0x0d, 0x93, 0x77, 0x17,
	0x67, 0x3b, 0xd4, 0x02, 0x4c, 0x61, 0x87, 0x7e, 0x1a, 0x89, 0x16, 0x4e, 0xd4, 0x00, 0x2e, 0xc8,
	0x08, 0x22, 0x31, 0x36, 0x49, 0xdf, 0x0e, 0x5b, 0x98, 0xb3, 0x05, 0x49, 0x96, 0x59, 0xf8, 0x4d,
	0x2b, 0x3c, 0x1f, 0x56, 0xa3, 0xea, 0x8a, 0xcb, 0x4c, 0x7d, 0x12, 0x1f, 0x6c, 0x17, 0xb3, 0x07,
	0xd1, 0x57, 0xf7, 0xcc, 0xb7, 0x95, 0x48, 0x5e, 0x31, 0x56, 0x8d, 0x38, 0x19, 0x1a, 0x26, 0x7f,
	0x5f, 0x7b, 0xd8, 0x3a, 0x6b, 0x32, 0x5c, 0x80, 0x69, 0x66, 0x78, 0x1d, 0xcc, 0x64, 0x00, 0x39,
	0x53, 0x7f, 0x4f, 0x01, 0xec, 0x0e, 0x7c, 0x86, 0x9d, 0x4d, 0xb2, 0x4f, 0x2b, 0xf9, 0xf8, 0xad,
	0xa9, 0xfc, 0x9c, 0x8a, 0x3e, 0x58, 0x8b, 0x00, 0x3e, 0x33, 0x3c, 0x86, 0x2d, 0xdd, 0x08, 0x3f,
	0x99, 0x69, 0x2d, 0x2f, 0x2d, 0x0d, 0x86, 0x96, 0x21, 0x4b, 0x02, 0x47, 0x37, 0xdd, 0x40, 0xf8,
	0x4e, 0x37, 0xe1, 0x70, 0x58, 0x9d, 0x7e, 0x14, 0x38, 0xf7, 0x5b, 0x7b, 0xda, 0x34, 0x09, 0x9c,
	0xfb, 0x6e, 0x20, 0x1a, 0x15, 0xaa, 0xf7, 0xb1, 0xe7, 0xdb, 0x94, 0xc8, 0xe2, 0xcf, 0x77, 0xe8,
	0x87, 0xa1, 0x01, 0x2d, 0xc3, 0x0c, 0xf7, 0xd1, 0xa1, 0x1e, 0x0d, 0x98, 0x4d, 0x64, 0x46, 0x69,
	0x45, 0x12, 0x38, 0x0f, 0x22, 0x1b, 0xba, 0x0e, 0x25, 0xea, 0x62, 0xcf, 0x60, 0x36, 0xe9, 0xe8,
	0xbe, 0x20, 0x5d, 0x9e, 0x12, 0x9e, 0xe6, 0x62, 0x7b, 0x78, 0x16, 0x74, 0x09, 0xf2, 0x07, 0xd4,
	0x67, 0xe1, 0x7b, 0x30, 0x2d, 0x30, 0x39, 0x6e, 0x10, 0xf7, 0x83, 0x20, 0x63, 0x78, 0xe6, 0x41,
	0x39, 0x1b, 0x4a, 0xcd, 0xc7, 0xfc, 0xc5, 0x8c, 0xc8, 0xe5, 0xc2, 0x17, 0x53, 0x4e, 0xd1, 0x45,
	0xc8, 0xf6, 0x4d, 0x5f, 0xf7, 0xf0, 0x7e, 0x39, 0x1f, 0x4a, 0xd7, 0x37, 0x7d, 0x0d, 0xef, 0xf3,
	0x23, 0xb5, 0x03, 0xbb, 0x67, 0xe9, 0xcc, 0x76, 0x70, 0x19, 0x42, 0x59, 0x84, 0xe5, 0xb1, 0xed,
	0xe0, 0xb5, 0x67, 0x30, 0x3b, 0x7e, 0x13, 0x68, 0x06, 0xf2, 0x7b, 0xc4, 0xc2, 0xfb, 0x36, 0xc1,
	0xfc, 0x2b, 0xc9, 0x3f, 0x9b, 0xa3, 0x3a, 0x2b, 0x29, 0xa8, 0x04, 0xc5, 0x64, 0x81, 0x94, 0x52,
	0x68, 0x1e, 0xe6, 0x8e, 0x24, 0x74, 0x29, 0xcd, 0x61, 0xc9, 0x74, 0x2b, 0x65, 0xb8, 0xa7, 0x44,
	0x82, 0x94, 0xa6, 0xd6, 0xff, 0xc9, 0x41, 0x69, 0x27, 0x4a, 0x88, 0x5d, 0xec, 0xf5, 0x6d, 0x13,
	0xa3, 0x1f, 0x94, 0x93, 0x9b, 0x76, 0x74, 0x7b, 0x22, 0x8d, 0x4e, 0x82, 0xd6, 0xa2, 0x04, 0xa9,
	0x9f, 0x66, 0x0b, 0xff, 0xe4, 0xdc, 0xfe, 0xe2, 0xb7, 0xbf, 0xbe, 0x49, 0xdd, 0x50, 0x57, 0xea,
	0xf1, 0x96, 0x7a, 0xff, 0x76, 0xfd, 0xa4, 0x5d, 0xf7, 0x94, 0x35, 0x44, 0x8f, 0xed, 0x94, 0xd1,
	0xcd, 0x89, 0xd0, 0xc7, 0xa0, 0x62, 0xa2, 0x6b, 0xaf, 0x88, 0xe6, 0xb9, 0xfe, 0xbd, 0x72, 0x62,
	0x03, 0x89, 0x6e, 0x4d, 0xf8, 0x39, 0x01, 0x19, 0x47, 0xae, 0x9d, 0x62, 0x07, 0x57, 0xe8, 0x96,
	0x50, 0x68, 0x4d, 0xbd, 0x36, 0xae, 0xd0, 0x09, 0x9b, 0xb8, 0x40, 0x5f, 0x2a, 0x47, 0xfa, 0x50,
	0xb4, 0xf2, 0x92, 0x86, 0x32, 0xe2, 0x76, 0xf5, 0xa5, 0x38, 0xce, 0x68, 0x45, 0x30, 0x5a, 0x52,
	0x2f, 0x8d, 0x33, 0x1a, 0x83, 0x72, 0x1e, 0xdf, 0x1e, 0xdb, 0xd5, 0xa1, 0x1b, 0x93, 0xd2, 0x4f,
	0x80, 0x62, 0x46, 0xd7, 0x5f, 0x0d, 0xcc, 0x69, 0xdd, 0x10, 0xb4, 0xae, 0xa9, 0x4b, 0xe3, 0xb4,
	0x26, 0xf1, 0x9c, 0xdb, 0xe7, 0x63, 0xfd, 0x14, 0xba, 0x7a, 0x6c, 0x18, 0xb9, 0x1a, 0x93, 0x51,
	0x5f, 0x82, 0xe2, 0x2c, 0xae, 0x0a, 0x16, 0x97, 0xd5, 0x37, 0x27, 0x59, 0x48, 0x20, 0x0f, 0xef,
	0xc4, 0x3d, 0x24, 0x5a, 0x3a, 0xd6, 0x69, 0xc3, 0x1c, 0xdd, 0xca, 0xe5, 0x17, 0x20, 0x78, 0xc8,
	0x25, 0x11, 0xb2, 0xa2, 0x9e, 0x9f, 0x0c, 0xd9, 0x30, 0xc5, 0x4d, 0x0c, 0x92, 0x0f, 0x3a, 0x9a,
	0xfc, 0x79, 0x31, 0x5a, 0x8c, 0x83, 0x5e, 0x79, 0x31, 0x88, 0xc7, 0x5d, 0x16, 0x71, 0x17, 0xd5,
	0xf2, 0x91, 0xb8, 0x31, 0xee, 0x9e, 0xb2, 0xd6, 0x5c, 0xfd, 0x78, 0x45, 0x36, 0x69, 0xd8, 0x3c,
	0xa8, 0x8b, 0x61, 0xbd, 0x43, 0xeb, 0x6e, 0xb7, 0x53, 0x1f, 0xff, 0xdb, 0xa2, 0x3d, 0x2d, 0xfe,
	0x47, 0xb8, 0xf3, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x82, 0xcb, 0xa2, 0x50, 0xcf, 0x10, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MessengerServiceClient is the client API for MessengerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MessengerServiceClient interface {
	// InstanceShareableBertyID returns a Berty ID that can be shared as a string, QR code or deep link.
	InstanceShareableBertyID(ctx context.Context, in *InstanceShareableBertyID_Request, opts ...grpc.CallOption) (*InstanceShareableBertyID_Reply, error)
	// ShareableBertyGroup returns a Berty Group that can be shared as a string, QR code or deep link.
	ShareableBertyGroup(ctx context.Context, in *ShareableBertyGroup_Request, opts ...grpc.CallOption) (*ShareableBertyGroup_Reply, error)
	// DevShareInstanceBertyID shares your Berty ID on a dev channel.
	// TODO: remove for public.
	DevShareInstanceBertyID(ctx context.Context, in *DevShareInstanceBertyID_Request, opts ...grpc.CallOption) (*DevShareInstanceBertyID_Reply, error)
	// ParseDeepLink parses a link in the form of berty://xxx or https://berty.tech/id# and returns a structure
	// that can be used to display information.
	// This action is read-only.
	ParseDeepLink(ctx context.Context, in *ParseDeepLink_Request, opts ...grpc.CallOption) (*ParseDeepLink_Reply, error)
	// SendContactRequest takes the payload received from ParseDeepLink and send a contact request using the Berty Protocol.
	SendContactRequest(ctx context.Context, in *SendContactRequest_Request, opts ...grpc.CallOption) (*SendContactRequest_Reply, error)
	// SendMessage sends a message to a group
	SendMessage(ctx context.Context, in *SendMessage_Request, opts ...grpc.CallOption) (*SendMessage_Reply, error)
	// SendAck sends an acknowledge payload for given message id
	SendAck(ctx context.Context, in *SendAck_Request, opts ...grpc.CallOption) (*SendAck_Reply, error)
	SystemInfo(ctx context.Context, in *SystemInfo_Request, opts ...grpc.CallOption) (*SystemInfo_Reply, error)
}

type messengerServiceClient struct {
	cc *grpc.ClientConn
}

func NewMessengerServiceClient(cc *grpc.ClientConn) MessengerServiceClient {
	return &messengerServiceClient{cc}
}

func (c *messengerServiceClient) InstanceShareableBertyID(ctx context.Context, in *InstanceShareableBertyID_Request, opts ...grpc.CallOption) (*InstanceShareableBertyID_Reply, error) {
	out := new(InstanceShareableBertyID_Reply)
	err := c.cc.Invoke(ctx, "/berty.messenger.MessengerService/InstanceShareableBertyID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messengerServiceClient) ShareableBertyGroup(ctx context.Context, in *ShareableBertyGroup_Request, opts ...grpc.CallOption) (*ShareableBertyGroup_Reply, error) {
	out := new(ShareableBertyGroup_Reply)
	err := c.cc.Invoke(ctx, "/berty.messenger.MessengerService/ShareableBertyGroup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messengerServiceClient) DevShareInstanceBertyID(ctx context.Context, in *DevShareInstanceBertyID_Request, opts ...grpc.CallOption) (*DevShareInstanceBertyID_Reply, error) {
	out := new(DevShareInstanceBertyID_Reply)
	err := c.cc.Invoke(ctx, "/berty.messenger.MessengerService/DevShareInstanceBertyID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messengerServiceClient) ParseDeepLink(ctx context.Context, in *ParseDeepLink_Request, opts ...grpc.CallOption) (*ParseDeepLink_Reply, error) {
	out := new(ParseDeepLink_Reply)
	err := c.cc.Invoke(ctx, "/berty.messenger.MessengerService/ParseDeepLink", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messengerServiceClient) SendContactRequest(ctx context.Context, in *SendContactRequest_Request, opts ...grpc.CallOption) (*SendContactRequest_Reply, error) {
	out := new(SendContactRequest_Reply)
	err := c.cc.Invoke(ctx, "/berty.messenger.MessengerService/SendContactRequest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messengerServiceClient) SendMessage(ctx context.Context, in *SendMessage_Request, opts ...grpc.CallOption) (*SendMessage_Reply, error) {
	out := new(SendMessage_Reply)
	err := c.cc.Invoke(ctx, "/berty.messenger.MessengerService/SendMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messengerServiceClient) SendAck(ctx context.Context, in *SendAck_Request, opts ...grpc.CallOption) (*SendAck_Reply, error) {
	out := new(SendAck_Reply)
	err := c.cc.Invoke(ctx, "/berty.messenger.MessengerService/SendAck", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messengerServiceClient) SystemInfo(ctx context.Context, in *SystemInfo_Request, opts ...grpc.CallOption) (*SystemInfo_Reply, error) {
	out := new(SystemInfo_Reply)
	err := c.cc.Invoke(ctx, "/berty.messenger.MessengerService/SystemInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MessengerServiceServer is the server API for MessengerService service.
type MessengerServiceServer interface {
	// InstanceShareableBertyID returns a Berty ID that can be shared as a string, QR code or deep link.
	InstanceShareableBertyID(context.Context, *InstanceShareableBertyID_Request) (*InstanceShareableBertyID_Reply, error)
	// ShareableBertyGroup returns a Berty Group that can be shared as a string, QR code or deep link.
	ShareableBertyGroup(context.Context, *ShareableBertyGroup_Request) (*ShareableBertyGroup_Reply, error)
	// DevShareInstanceBertyID shares your Berty ID on a dev channel.
	// TODO: remove for public.
	DevShareInstanceBertyID(context.Context, *DevShareInstanceBertyID_Request) (*DevShareInstanceBertyID_Reply, error)
	// ParseDeepLink parses a link in the form of berty://xxx or https://berty.tech/id# and returns a structure
	// that can be used to display information.
	// This action is read-only.
	ParseDeepLink(context.Context, *ParseDeepLink_Request) (*ParseDeepLink_Reply, error)
	// SendContactRequest takes the payload received from ParseDeepLink and send a contact request using the Berty Protocol.
	SendContactRequest(context.Context, *SendContactRequest_Request) (*SendContactRequest_Reply, error)
	// SendMessage sends a message to a group
	SendMessage(context.Context, *SendMessage_Request) (*SendMessage_Reply, error)
	// SendAck sends an acknowledge payload for given message id
	SendAck(context.Context, *SendAck_Request) (*SendAck_Reply, error)
	SystemInfo(context.Context, *SystemInfo_Request) (*SystemInfo_Reply, error)
}

// UnimplementedMessengerServiceServer can be embedded to have forward compatible implementations.
type UnimplementedMessengerServiceServer struct {
}

func (*UnimplementedMessengerServiceServer) InstanceShareableBertyID(ctx context.Context, req *InstanceShareableBertyID_Request) (*InstanceShareableBertyID_Reply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InstanceShareableBertyID not implemented")
}
func (*UnimplementedMessengerServiceServer) ShareableBertyGroup(ctx context.Context, req *ShareableBertyGroup_Request) (*ShareableBertyGroup_Reply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ShareableBertyGroup not implemented")
}
func (*UnimplementedMessengerServiceServer) DevShareInstanceBertyID(ctx context.Context, req *DevShareInstanceBertyID_Request) (*DevShareInstanceBertyID_Reply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DevShareInstanceBertyID not implemented")
}
func (*UnimplementedMessengerServiceServer) ParseDeepLink(ctx context.Context, req *ParseDeepLink_Request) (*ParseDeepLink_Reply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ParseDeepLink not implemented")
}
func (*UnimplementedMessengerServiceServer) SendContactRequest(ctx context.Context, req *SendContactRequest_Request) (*SendContactRequest_Reply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendContactRequest not implemented")
}
func (*UnimplementedMessengerServiceServer) SendMessage(ctx context.Context, req *SendMessage_Request) (*SendMessage_Reply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendMessage not implemented")
}
func (*UnimplementedMessengerServiceServer) SendAck(ctx context.Context, req *SendAck_Request) (*SendAck_Reply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendAck not implemented")
}
func (*UnimplementedMessengerServiceServer) SystemInfo(ctx context.Context, req *SystemInfo_Request) (*SystemInfo_Reply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SystemInfo not implemented")
}

func RegisterMessengerServiceServer(s *grpc.Server, srv MessengerServiceServer) {
	s.RegisterService(&_MessengerService_serviceDesc, srv)
}

func _MessengerService_InstanceShareableBertyID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InstanceShareableBertyID_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessengerServiceServer).InstanceShareableBertyID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/berty.messenger.MessengerService/InstanceShareableBertyID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessengerServiceServer).InstanceShareableBertyID(ctx, req.(*InstanceShareableBertyID_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessengerService_ShareableBertyGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShareableBertyGroup_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessengerServiceServer).ShareableBertyGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/berty.messenger.MessengerService/ShareableBertyGroup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessengerServiceServer).ShareableBertyGroup(ctx, req.(*ShareableBertyGroup_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessengerService_DevShareInstanceBertyID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DevShareInstanceBertyID_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessengerServiceServer).DevShareInstanceBertyID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/berty.messenger.MessengerService/DevShareInstanceBertyID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessengerServiceServer).DevShareInstanceBertyID(ctx, req.(*DevShareInstanceBertyID_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessengerService_ParseDeepLink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ParseDeepLink_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessengerServiceServer).ParseDeepLink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/berty.messenger.MessengerService/ParseDeepLink",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessengerServiceServer).ParseDeepLink(ctx, req.(*ParseDeepLink_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessengerService_SendContactRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendContactRequest_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessengerServiceServer).SendContactRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/berty.messenger.MessengerService/SendContactRequest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessengerServiceServer).SendContactRequest(ctx, req.(*SendContactRequest_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessengerService_SendMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendMessage_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessengerServiceServer).SendMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/berty.messenger.MessengerService/SendMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessengerServiceServer).SendMessage(ctx, req.(*SendMessage_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessengerService_SendAck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendAck_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessengerServiceServer).SendAck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/berty.messenger.MessengerService/SendAck",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessengerServiceServer).SendAck(ctx, req.(*SendAck_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessengerService_SystemInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SystemInfo_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessengerServiceServer).SystemInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/berty.messenger.MessengerService/SystemInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessengerServiceServer).SystemInfo(ctx, req.(*SystemInfo_Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _MessengerService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "berty.messenger.MessengerService",
	HandlerType: (*MessengerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InstanceShareableBertyID",
			Handler:    _MessengerService_InstanceShareableBertyID_Handler,
		},
		{
			MethodName: "ShareableBertyGroup",
			Handler:    _MessengerService_ShareableBertyGroup_Handler,
		},
		{
			MethodName: "DevShareInstanceBertyID",
			Handler:    _MessengerService_DevShareInstanceBertyID_Handler,
		},
		{
			MethodName: "ParseDeepLink",
			Handler:    _MessengerService_ParseDeepLink_Handler,
		},
		{
			MethodName: "SendContactRequest",
			Handler:    _MessengerService_SendContactRequest_Handler,
		},
		{
			MethodName: "SendMessage",
			Handler:    _MessengerService_SendMessage_Handler,
		},
		{
			MethodName: "SendAck",
			Handler:    _MessengerService_SendAck_Handler,
		},
		{
			MethodName: "SystemInfo",
			Handler:    _MessengerService_SystemInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bertymessenger.proto",
}
