name: "Feature request"
description: Suggest an idea for this project.
labels: [":rocket: feature-request"]
body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for this feature request.
      options:
      - label: I have searched the existing issues
        required: true
  - type: dropdown
    id: product
    attributes:
      label: Berty product
      description: What Berty product is the requsted feature for?
      options:
        - Mobile app
        - Desktop app
        - CLI tools (berty mini, daemon, etc.)
        - Code package
    validations:
      required: true
  - type: textarea
    id: feature
    attributes:
      label: Feature request
      description: Provide a detailed description of the change or addition you are proposing.
      placeholder: There should be ...
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Context
      description: Why is this change important to you? How would you use it? How can it benefit other users?
      placeholder: This feature request is important because ...
    validations:
      required: true
  - type: textarea
    id: implementation
    attributes:
      label: Possible implementation
      description: Not obligatory, but suggest an idea for implementing addition or change.
      placeholder: This feature could be implemented by ...
