// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: api/node/service.proto

package node // import "berty.tech/core/api/node"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import p2p "berty.tech/core/api/p2p"
import _ "berty.tech/core/api/protobuf"
import entity "berty.tech/core/entity"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PingDestination struct {
	Destination          string   `protobuf:"bytes,1,opt,name=destination,proto3" json:"destination,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingDestination) Reset()         { *m = PingDestination{} }
func (m *PingDestination) String() string { return proto.CompactTextString(m) }
func (*PingDestination) ProtoMessage()    {}
func (*PingDestination) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_2c3afb50d9ca8484, []int{0}
}
func (m *PingDestination) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PingDestination) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PingDestination.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *PingDestination) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingDestination.Merge(dst, src)
}
func (m *PingDestination) XXX_Size() int {
	return m.Size()
}
func (m *PingDestination) XXX_DiscardUnknown() {
	xxx_messageInfo_PingDestination.DiscardUnknown(m)
}

var xxx_messageInfo_PingDestination proto.InternalMessageInfo

func (m *PingDestination) GetDestination() string {
	if m != nil {
		return m.Destination
	}
	return ""
}

type ContactRequestInput struct {
	Contact              *entity.Contact `protobuf:"bytes,1,opt,name=contact" json:"contact,omitempty"`
	IntroText            string          `protobuf:"bytes,2,opt,name=intro_text,json=introText,proto3" json:"intro_text,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ContactRequestInput) Reset()         { *m = ContactRequestInput{} }
func (m *ContactRequestInput) String() string { return proto.CompactTextString(m) }
func (*ContactRequestInput) ProtoMessage()    {}
func (*ContactRequestInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_2c3afb50d9ca8484, []int{1}
}
func (m *ContactRequestInput) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ContactRequestInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ContactRequestInput.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *ContactRequestInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContactRequestInput.Merge(dst, src)
}
func (m *ContactRequestInput) XXX_Size() int {
	return m.Size()
}
func (m *ContactRequestInput) XXX_DiscardUnknown() {
	xxx_messageInfo_ContactRequestInput.DiscardUnknown(m)
}

var xxx_messageInfo_ContactRequestInput proto.InternalMessageInfo

func (m *ContactRequestInput) GetContact() *entity.Contact {
	if m != nil {
		return m.Contact
	}
	return nil
}

func (m *ContactRequestInput) GetIntroText() string {
	if m != nil {
		return m.IntroText
	}
	return ""
}

type ConversationAddMessageInput struct {
	Conversation         *entity.Conversation `protobuf:"bytes,1,opt,name=conversation" json:"conversation,omitempty"`
	Message              *entity.Message      `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ConversationAddMessageInput) Reset()         { *m = ConversationAddMessageInput{} }
func (m *ConversationAddMessageInput) String() string { return proto.CompactTextString(m) }
func (*ConversationAddMessageInput) ProtoMessage()    {}
func (*ConversationAddMessageInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_2c3afb50d9ca8484, []int{2}
}
func (m *ConversationAddMessageInput) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ConversationAddMessageInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ConversationAddMessageInput.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *ConversationAddMessageInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConversationAddMessageInput.Merge(dst, src)
}
func (m *ConversationAddMessageInput) XXX_Size() int {
	return m.Size()
}
func (m *ConversationAddMessageInput) XXX_DiscardUnknown() {
	xxx_messageInfo_ConversationAddMessageInput.DiscardUnknown(m)
}

var xxx_messageInfo_ConversationAddMessageInput proto.InternalMessageInfo

func (m *ConversationAddMessageInput) GetConversation() *entity.Conversation {
	if m != nil {
		return m.Conversation
	}
	return nil
}

func (m *ConversationAddMessageInput) GetMessage() *entity.Message {
	if m != nil {
		return m.Message
	}
	return nil
}

type EventStreamInput struct {
	Filter               *p2p.Event `protobuf:"bytes,1,opt,name=filter" json:"filter,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *EventStreamInput) Reset()         { *m = EventStreamInput{} }
func (m *EventStreamInput) String() string { return proto.CompactTextString(m) }
func (*EventStreamInput) ProtoMessage()    {}
func (*EventStreamInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_2c3afb50d9ca8484, []int{3}
}
func (m *EventStreamInput) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventStreamInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventStreamInput.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *EventStreamInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventStreamInput.Merge(dst, src)
}
func (m *EventStreamInput) XXX_Size() int {
	return m.Size()
}
func (m *EventStreamInput) XXX_DiscardUnknown() {
	xxx_messageInfo_EventStreamInput.DiscardUnknown(m)
}

var xxx_messageInfo_EventStreamInput proto.InternalMessageInfo

func (m *EventStreamInput) GetFilter() *p2p.Event {
	if m != nil {
		return m.Filter
	}
	return nil
}

type EventListInput struct {
	Limit                uint32     `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Filter               *p2p.Event `protobuf:"bytes,2,opt,name=filter" json:"filter,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *EventListInput) Reset()         { *m = EventListInput{} }
func (m *EventListInput) String() string { return proto.CompactTextString(m) }
func (*EventListInput) ProtoMessage()    {}
func (*EventListInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_2c3afb50d9ca8484, []int{4}
}
func (m *EventListInput) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventListInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventListInput.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *EventListInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventListInput.Merge(dst, src)
}
func (m *EventListInput) XXX_Size() int {
	return m.Size()
}
func (m *EventListInput) XXX_DiscardUnknown() {
	xxx_messageInfo_EventListInput.DiscardUnknown(m)
}

var xxx_messageInfo_EventListInput proto.InternalMessageInfo

func (m *EventListInput) GetLimit() uint32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *EventListInput) GetFilter() *p2p.Event {
	if m != nil {
		return m.Filter
	}
	return nil
}

type ConversationManageMembersInput struct {
	Conversation         *entity.Conversation         `protobuf:"bytes,1,opt,name=conversation" json:"conversation,omitempty"`
	Members              []*entity.ConversationMember `protobuf:"bytes,2,rep,name=members" json:"members,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *ConversationManageMembersInput) Reset()         { *m = ConversationManageMembersInput{} }
func (m *ConversationManageMembersInput) String() string { return proto.CompactTextString(m) }
func (*ConversationManageMembersInput) ProtoMessage()    {}
func (*ConversationManageMembersInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_2c3afb50d9ca8484, []int{5}
}
func (m *ConversationManageMembersInput) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ConversationManageMembersInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ConversationManageMembersInput.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *ConversationManageMembersInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConversationManageMembersInput.Merge(dst, src)
}
func (m *ConversationManageMembersInput) XXX_Size() int {
	return m.Size()
}
func (m *ConversationManageMembersInput) XXX_DiscardUnknown() {
	xxx_messageInfo_ConversationManageMembersInput.DiscardUnknown(m)
}

var xxx_messageInfo_ConversationManageMembersInput proto.InternalMessageInfo

func (m *ConversationManageMembersInput) GetConversation() *entity.Conversation {
	if m != nil {
		return m.Conversation
	}
	return nil
}

func (m *ConversationManageMembersInput) GetMembers() []*entity.ConversationMember {
	if m != nil {
		return m.Members
	}
	return nil
}

type Void struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Void) Reset()         { *m = Void{} }
func (m *Void) String() string { return proto.CompactTextString(m) }
func (*Void) ProtoMessage()    {}
func (*Void) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_2c3afb50d9ca8484, []int{6}
}
func (m *Void) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Void) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Void.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *Void) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Void.Merge(dst, src)
}
func (m *Void) XXX_Size() int {
	return m.Size()
}
func (m *Void) XXX_DiscardUnknown() {
	xxx_messageInfo_Void.DiscardUnknown(m)
}

var xxx_messageInfo_Void proto.InternalMessageInfo

func init() {
	proto.RegisterType((*PingDestination)(nil), "berty.node.PingDestination")
	proto.RegisterType((*ContactRequestInput)(nil), "berty.node.ContactRequestInput")
	proto.RegisterType((*ConversationAddMessageInput)(nil), "berty.node.ConversationAddMessageInput")
	proto.RegisterType((*EventStreamInput)(nil), "berty.node.EventStreamInput")
	proto.RegisterType((*EventListInput)(nil), "berty.node.EventListInput")
	proto.RegisterType((*ConversationManageMembersInput)(nil), "berty.node.ConversationManageMembersInput")
	proto.RegisterType((*Void)(nil), "berty.node.Void")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ServiceClient is the client API for Service service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ServiceClient interface {
	// yield new events in real-time
	EventStream(ctx context.Context, in *EventStreamInput, opts ...grpc.CallOption) (Service_EventStreamClient, error)
	// list old events
	EventList(ctx context.Context, in *EventListInput, opts ...grpc.CallOption) (Service_EventListClient, error)
	GetEvent(ctx context.Context, in *p2p.Event, opts ...grpc.CallOption) (*p2p.Event, error)
	ContactRequest(ctx context.Context, in *ContactRequestInput, opts ...grpc.CallOption) (*entity.Contact, error)
	ContactAcceptRequest(ctx context.Context, in *entity.Contact, opts ...grpc.CallOption) (*entity.Contact, error)
	ContactRemove(ctx context.Context, in *entity.Contact, opts ...grpc.CallOption) (*entity.Contact, error)
	ContactUpdate(ctx context.Context, in *entity.Contact, opts ...grpc.CallOption) (*entity.Contact, error)
	ContactList(ctx context.Context, in *Void, opts ...grpc.CallOption) (Service_ContactListClient, error)
	GetContact(ctx context.Context, in *entity.Contact, opts ...grpc.CallOption) (*entity.Contact, error)
	ConversationCreate(ctx context.Context, in *entity.Conversation, opts ...grpc.CallOption) (*entity.Conversation, error)
	ConversationList(ctx context.Context, in *Void, opts ...grpc.CallOption) (Service_ConversationListClient, error)
	ConversationInvite(ctx context.Context, in *ConversationManageMembersInput, opts ...grpc.CallOption) (*entity.Conversation, error)
	ConversationExclude(ctx context.Context, in *ConversationManageMembersInput, opts ...grpc.CallOption) (*entity.Conversation, error)
	ConversationAddMessage(ctx context.Context, in *ConversationAddMessageInput, opts ...grpc.CallOption) (*p2p.Event, error)
	GetConversation(ctx context.Context, in *entity.Conversation, opts ...grpc.CallOption) (*entity.Conversation, error)
	GetConversationMember(ctx context.Context, in *entity.ConversationMember, opts ...grpc.CallOption) (*entity.ConversationMember, error)
	// HandleEvent is the unencrypted (and unsafe) version of HandleEnvelope.
	// it's only exposed over the node API, it should be completely deactivated in public releases
	HandleEvent(ctx context.Context, in *p2p.Event, opts ...grpc.CallOption) (*Void, error)
	GenerateFakeData(ctx context.Context, in *Void, opts ...grpc.CallOption) (*Void, error)
	DebugPing(ctx context.Context, in *PingDestination, opts ...grpc.CallOption) (*Void, error)
}

type serviceClient struct {
	cc *grpc.ClientConn
}

func NewServiceClient(cc *grpc.ClientConn) ServiceClient {
	return &serviceClient{cc}
}

func (c *serviceClient) EventStream(ctx context.Context, in *EventStreamInput, opts ...grpc.CallOption) (Service_EventStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Service_serviceDesc.Streams[0], "/berty.node.Service/EventStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &serviceEventStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Service_EventStreamClient interface {
	Recv() (*p2p.Event, error)
	grpc.ClientStream
}

type serviceEventStreamClient struct {
	grpc.ClientStream
}

func (x *serviceEventStreamClient) Recv() (*p2p.Event, error) {
	m := new(p2p.Event)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *serviceClient) EventList(ctx context.Context, in *EventListInput, opts ...grpc.CallOption) (Service_EventListClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Service_serviceDesc.Streams[1], "/berty.node.Service/EventList", opts...)
	if err != nil {
		return nil, err
	}
	x := &serviceEventListClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Service_EventListClient interface {
	Recv() (*p2p.Event, error)
	grpc.ClientStream
}

type serviceEventListClient struct {
	grpc.ClientStream
}

func (x *serviceEventListClient) Recv() (*p2p.Event, error) {
	m := new(p2p.Event)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *serviceClient) GetEvent(ctx context.Context, in *p2p.Event, opts ...grpc.CallOption) (*p2p.Event, error) {
	out := new(p2p.Event)
	err := c.cc.Invoke(ctx, "/berty.node.Service/GetEvent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) ContactRequest(ctx context.Context, in *ContactRequestInput, opts ...grpc.CallOption) (*entity.Contact, error) {
	out := new(entity.Contact)
	err := c.cc.Invoke(ctx, "/berty.node.Service/ContactRequest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) ContactAcceptRequest(ctx context.Context, in *entity.Contact, opts ...grpc.CallOption) (*entity.Contact, error) {
	out := new(entity.Contact)
	err := c.cc.Invoke(ctx, "/berty.node.Service/ContactAcceptRequest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) ContactRemove(ctx context.Context, in *entity.Contact, opts ...grpc.CallOption) (*entity.Contact, error) {
	out := new(entity.Contact)
	err := c.cc.Invoke(ctx, "/berty.node.Service/ContactRemove", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) ContactUpdate(ctx context.Context, in *entity.Contact, opts ...grpc.CallOption) (*entity.Contact, error) {
	out := new(entity.Contact)
	err := c.cc.Invoke(ctx, "/berty.node.Service/ContactUpdate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) ContactList(ctx context.Context, in *Void, opts ...grpc.CallOption) (Service_ContactListClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Service_serviceDesc.Streams[2], "/berty.node.Service/ContactList", opts...)
	if err != nil {
		return nil, err
	}
	x := &serviceContactListClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Service_ContactListClient interface {
	Recv() (*entity.Contact, error)
	grpc.ClientStream
}

type serviceContactListClient struct {
	grpc.ClientStream
}

func (x *serviceContactListClient) Recv() (*entity.Contact, error) {
	m := new(entity.Contact)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *serviceClient) GetContact(ctx context.Context, in *entity.Contact, opts ...grpc.CallOption) (*entity.Contact, error) {
	out := new(entity.Contact)
	err := c.cc.Invoke(ctx, "/berty.node.Service/GetContact", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) ConversationCreate(ctx context.Context, in *entity.Conversation, opts ...grpc.CallOption) (*entity.Conversation, error) {
	out := new(entity.Conversation)
	err := c.cc.Invoke(ctx, "/berty.node.Service/ConversationCreate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) ConversationList(ctx context.Context, in *Void, opts ...grpc.CallOption) (Service_ConversationListClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Service_serviceDesc.Streams[3], "/berty.node.Service/ConversationList", opts...)
	if err != nil {
		return nil, err
	}
	x := &serviceConversationListClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Service_ConversationListClient interface {
	Recv() (*entity.Conversation, error)
	grpc.ClientStream
}

type serviceConversationListClient struct {
	grpc.ClientStream
}

func (x *serviceConversationListClient) Recv() (*entity.Conversation, error) {
	m := new(entity.Conversation)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *serviceClient) ConversationInvite(ctx context.Context, in *ConversationManageMembersInput, opts ...grpc.CallOption) (*entity.Conversation, error) {
	out := new(entity.Conversation)
	err := c.cc.Invoke(ctx, "/berty.node.Service/ConversationInvite", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) ConversationExclude(ctx context.Context, in *ConversationManageMembersInput, opts ...grpc.CallOption) (*entity.Conversation, error) {
	out := new(entity.Conversation)
	err := c.cc.Invoke(ctx, "/berty.node.Service/ConversationExclude", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) ConversationAddMessage(ctx context.Context, in *ConversationAddMessageInput, opts ...grpc.CallOption) (*p2p.Event, error) {
	out := new(p2p.Event)
	err := c.cc.Invoke(ctx, "/berty.node.Service/ConversationAddMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) GetConversation(ctx context.Context, in *entity.Conversation, opts ...grpc.CallOption) (*entity.Conversation, error) {
	out := new(entity.Conversation)
	err := c.cc.Invoke(ctx, "/berty.node.Service/GetConversation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) GetConversationMember(ctx context.Context, in *entity.ConversationMember, opts ...grpc.CallOption) (*entity.ConversationMember, error) {
	out := new(entity.ConversationMember)
	err := c.cc.Invoke(ctx, "/berty.node.Service/GetConversationMember", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) HandleEvent(ctx context.Context, in *p2p.Event, opts ...grpc.CallOption) (*Void, error) {
	out := new(Void)
	err := c.cc.Invoke(ctx, "/berty.node.Service/HandleEvent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) GenerateFakeData(ctx context.Context, in *Void, opts ...grpc.CallOption) (*Void, error) {
	out := new(Void)
	err := c.cc.Invoke(ctx, "/berty.node.Service/GenerateFakeData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) DebugPing(ctx context.Context, in *PingDestination, opts ...grpc.CallOption) (*Void, error) {
	out := new(Void)
	err := c.cc.Invoke(ctx, "/berty.node.Service/DebugPing", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServiceServer is the server API for Service service.
type ServiceServer interface {
	// yield new events in real-time
	EventStream(*EventStreamInput, Service_EventStreamServer) error
	// list old events
	EventList(*EventListInput, Service_EventListServer) error
	GetEvent(context.Context, *p2p.Event) (*p2p.Event, error)
	ContactRequest(context.Context, *ContactRequestInput) (*entity.Contact, error)
	ContactAcceptRequest(context.Context, *entity.Contact) (*entity.Contact, error)
	ContactRemove(context.Context, *entity.Contact) (*entity.Contact, error)
	ContactUpdate(context.Context, *entity.Contact) (*entity.Contact, error)
	ContactList(*Void, Service_ContactListServer) error
	GetContact(context.Context, *entity.Contact) (*entity.Contact, error)
	ConversationCreate(context.Context, *entity.Conversation) (*entity.Conversation, error)
	ConversationList(*Void, Service_ConversationListServer) error
	ConversationInvite(context.Context, *ConversationManageMembersInput) (*entity.Conversation, error)
	ConversationExclude(context.Context, *ConversationManageMembersInput) (*entity.Conversation, error)
	ConversationAddMessage(context.Context, *ConversationAddMessageInput) (*p2p.Event, error)
	GetConversation(context.Context, *entity.Conversation) (*entity.Conversation, error)
	GetConversationMember(context.Context, *entity.ConversationMember) (*entity.ConversationMember, error)
	// HandleEvent is the unencrypted (and unsafe) version of HandleEnvelope.
	// it's only exposed over the node API, it should be completely deactivated in public releases
	HandleEvent(context.Context, *p2p.Event) (*Void, error)
	GenerateFakeData(context.Context, *Void) (*Void, error)
	DebugPing(context.Context, *PingDestination) (*Void, error)
}

func RegisterServiceServer(s *grpc.Server, srv ServiceServer) {
	s.RegisterService(&_Service_serviceDesc, srv)
}

func _Service_EventStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(EventStreamInput)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ServiceServer).EventStream(m, &serviceEventStreamServer{stream})
}

type Service_EventStreamServer interface {
	Send(*p2p.Event) error
	grpc.ServerStream
}

type serviceEventStreamServer struct {
	grpc.ServerStream
}

func (x *serviceEventStreamServer) Send(m *p2p.Event) error {
	return x.ServerStream.SendMsg(m)
}

func _Service_EventList_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(EventListInput)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ServiceServer).EventList(m, &serviceEventListServer{stream})
}

type Service_EventListServer interface {
	Send(*p2p.Event) error
	grpc.ServerStream
}

type serviceEventListServer struct {
	grpc.ServerStream
}

func (x *serviceEventListServer) Send(m *p2p.Event) error {
	return x.ServerStream.SendMsg(m)
}

func _Service_GetEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(p2p.Event)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).GetEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/berty.node.Service/GetEvent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).GetEvent(ctx, req.(*p2p.Event))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_ContactRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContactRequestInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).ContactRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/berty.node.Service/ContactRequest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).ContactRequest(ctx, req.(*ContactRequestInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_ContactAcceptRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(entity.Contact)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).ContactAcceptRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/berty.node.Service/ContactAcceptRequest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).ContactAcceptRequest(ctx, req.(*entity.Contact))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_ContactRemove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(entity.Contact)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).ContactRemove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/berty.node.Service/ContactRemove",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).ContactRemove(ctx, req.(*entity.Contact))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_ContactUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(entity.Contact)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).ContactUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/berty.node.Service/ContactUpdate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).ContactUpdate(ctx, req.(*entity.Contact))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_ContactList_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Void)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ServiceServer).ContactList(m, &serviceContactListServer{stream})
}

type Service_ContactListServer interface {
	Send(*entity.Contact) error
	grpc.ServerStream
}

type serviceContactListServer struct {
	grpc.ServerStream
}

func (x *serviceContactListServer) Send(m *entity.Contact) error {
	return x.ServerStream.SendMsg(m)
}

func _Service_GetContact_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(entity.Contact)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).GetContact(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/berty.node.Service/GetContact",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).GetContact(ctx, req.(*entity.Contact))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_ConversationCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(entity.Conversation)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).ConversationCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/berty.node.Service/ConversationCreate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).ConversationCreate(ctx, req.(*entity.Conversation))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_ConversationList_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Void)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ServiceServer).ConversationList(m, &serviceConversationListServer{stream})
}

type Service_ConversationListServer interface {
	Send(*entity.Conversation) error
	grpc.ServerStream
}

type serviceConversationListServer struct {
	grpc.ServerStream
}

func (x *serviceConversationListServer) Send(m *entity.Conversation) error {
	return x.ServerStream.SendMsg(m)
}

func _Service_ConversationInvite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConversationManageMembersInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).ConversationInvite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/berty.node.Service/ConversationInvite",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).ConversationInvite(ctx, req.(*ConversationManageMembersInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_ConversationExclude_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConversationManageMembersInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).ConversationExclude(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/berty.node.Service/ConversationExclude",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).ConversationExclude(ctx, req.(*ConversationManageMembersInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_ConversationAddMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConversationAddMessageInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).ConversationAddMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/berty.node.Service/ConversationAddMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).ConversationAddMessage(ctx, req.(*ConversationAddMessageInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_GetConversation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(entity.Conversation)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).GetConversation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/berty.node.Service/GetConversation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).GetConversation(ctx, req.(*entity.Conversation))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_GetConversationMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(entity.ConversationMember)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).GetConversationMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/berty.node.Service/GetConversationMember",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).GetConversationMember(ctx, req.(*entity.ConversationMember))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_HandleEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(p2p.Event)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).HandleEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/berty.node.Service/HandleEvent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).HandleEvent(ctx, req.(*p2p.Event))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_GenerateFakeData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Void)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).GenerateFakeData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/berty.node.Service/GenerateFakeData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).GenerateFakeData(ctx, req.(*Void))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_DebugPing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingDestination)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).DebugPing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/berty.node.Service/DebugPing",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).DebugPing(ctx, req.(*PingDestination))
	}
	return interceptor(ctx, in, info, handler)
}

var _Service_serviceDesc = grpc.ServiceDesc{
	ServiceName: "berty.node.Service",
	HandlerType: (*ServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetEvent",
			Handler:    _Service_GetEvent_Handler,
		},
		{
			MethodName: "ContactRequest",
			Handler:    _Service_ContactRequest_Handler,
		},
		{
			MethodName: "ContactAcceptRequest",
			Handler:    _Service_ContactAcceptRequest_Handler,
		},
		{
			MethodName: "ContactRemove",
			Handler:    _Service_ContactRemove_Handler,
		},
		{
			MethodName: "ContactUpdate",
			Handler:    _Service_ContactUpdate_Handler,
		},
		{
			MethodName: "GetContact",
			Handler:    _Service_GetContact_Handler,
		},
		{
			MethodName: "ConversationCreate",
			Handler:    _Service_ConversationCreate_Handler,
		},
		{
			MethodName: "ConversationInvite",
			Handler:    _Service_ConversationInvite_Handler,
		},
		{
			MethodName: "ConversationExclude",
			Handler:    _Service_ConversationExclude_Handler,
		},
		{
			MethodName: "ConversationAddMessage",
			Handler:    _Service_ConversationAddMessage_Handler,
		},
		{
			MethodName: "GetConversation",
			Handler:    _Service_GetConversation_Handler,
		},
		{
			MethodName: "GetConversationMember",
			Handler:    _Service_GetConversationMember_Handler,
		},
		{
			MethodName: "HandleEvent",
			Handler:    _Service_HandleEvent_Handler,
		},
		{
			MethodName: "GenerateFakeData",
			Handler:    _Service_GenerateFakeData_Handler,
		},
		{
			MethodName: "DebugPing",
			Handler:    _Service_DebugPing_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "EventStream",
			Handler:       _Service_EventStream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "EventList",
			Handler:       _Service_EventList_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ContactList",
			Handler:       _Service_ContactList_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ConversationList",
			Handler:       _Service_ConversationList_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/node/service.proto",
}

func (m *PingDestination) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PingDestination) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Destination) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintService(dAtA, i, uint64(len(m.Destination)))
		i += copy(dAtA[i:], m.Destination)
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *ContactRequestInput) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ContactRequestInput) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Contact != nil {
		dAtA[i] = 0xa
		i++
		i = encodeVarintService(dAtA, i, uint64(m.Contact.Size()))
		n1, err := m.Contact.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n1
	}
	if len(m.IntroText) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintService(dAtA, i, uint64(len(m.IntroText)))
		i += copy(dAtA[i:], m.IntroText)
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *ConversationAddMessageInput) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ConversationAddMessageInput) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Conversation != nil {
		dAtA[i] = 0xa
		i++
		i = encodeVarintService(dAtA, i, uint64(m.Conversation.Size()))
		n2, err := m.Conversation.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n2
	}
	if m.Message != nil {
		dAtA[i] = 0x12
		i++
		i = encodeVarintService(dAtA, i, uint64(m.Message.Size()))
		n3, err := m.Message.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n3
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *EventStreamInput) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventStreamInput) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Filter != nil {
		dAtA[i] = 0xa
		i++
		i = encodeVarintService(dAtA, i, uint64(m.Filter.Size()))
		n4, err := m.Filter.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n4
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *EventListInput) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventListInput) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Limit != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintService(dAtA, i, uint64(m.Limit))
	}
	if m.Filter != nil {
		dAtA[i] = 0x12
		i++
		i = encodeVarintService(dAtA, i, uint64(m.Filter.Size()))
		n5, err := m.Filter.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n5
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *ConversationManageMembersInput) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ConversationManageMembersInput) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Conversation != nil {
		dAtA[i] = 0xa
		i++
		i = encodeVarintService(dAtA, i, uint64(m.Conversation.Size()))
		n6, err := m.Conversation.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n6
	}
	if len(m.Members) > 0 {
		for _, msg := range m.Members {
			dAtA[i] = 0x12
			i++
			i = encodeVarintService(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *Void) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Void) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func encodeVarintService(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *PingDestination) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Destination)
	if l > 0 {
		n += 1 + l + sovService(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *ContactRequestInput) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Contact != nil {
		l = m.Contact.Size()
		n += 1 + l + sovService(uint64(l))
	}
	l = len(m.IntroText)
	if l > 0 {
		n += 1 + l + sovService(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *ConversationAddMessageInput) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Conversation != nil {
		l = m.Conversation.Size()
		n += 1 + l + sovService(uint64(l))
	}
	if m.Message != nil {
		l = m.Message.Size()
		n += 1 + l + sovService(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *EventStreamInput) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Filter != nil {
		l = m.Filter.Size()
		n += 1 + l + sovService(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *EventListInput) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Limit != 0 {
		n += 1 + sovService(uint64(m.Limit))
	}
	if m.Filter != nil {
		l = m.Filter.Size()
		n += 1 + l + sovService(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *ConversationManageMembersInput) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Conversation != nil {
		l = m.Conversation.Size()
		n += 1 + l + sovService(uint64(l))
	}
	if len(m.Members) > 0 {
		for _, e := range m.Members {
			l = e.Size()
			n += 1 + l + sovService(uint64(l))
		}
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *Void) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovService(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozService(x uint64) (n int) {
	return sovService(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *PingDestination) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowService
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PingDestination: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PingDestination: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Destination", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthService
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Destination = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipService(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthService
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ContactRequestInput) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowService
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ContactRequestInput: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ContactRequestInput: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Contact", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthService
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Contact == nil {
				m.Contact = &entity.Contact{}
			}
			if err := m.Contact.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field IntroText", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthService
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.IntroText = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipService(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthService
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ConversationAddMessageInput) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowService
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ConversationAddMessageInput: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ConversationAddMessageInput: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Conversation", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthService
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Conversation == nil {
				m.Conversation = &entity.Conversation{}
			}
			if err := m.Conversation.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Message", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthService
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Message == nil {
				m.Message = &entity.Message{}
			}
			if err := m.Message.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipService(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthService
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EventStreamInput) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowService
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventStreamInput: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventStreamInput: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Filter", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthService
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Filter == nil {
				m.Filter = &p2p.Event{}
			}
			if err := m.Filter.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipService(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthService
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EventListInput) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowService
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventListInput: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventListInput: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Limit", wireType)
			}
			m.Limit = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Limit |= (uint32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Filter", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthService
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Filter == nil {
				m.Filter = &p2p.Event{}
			}
			if err := m.Filter.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipService(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthService
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ConversationManageMembersInput) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowService
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ConversationManageMembersInput: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ConversationManageMembersInput: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Conversation", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthService
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Conversation == nil {
				m.Conversation = &entity.Conversation{}
			}
			if err := m.Conversation.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Members", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthService
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Members = append(m.Members, &entity.ConversationMember{})
			if err := m.Members[len(m.Members)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipService(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthService
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Void) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowService
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Void: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Void: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipService(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthService
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipService(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowService
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowService
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowService
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthService
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowService
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipService(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthService = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowService   = fmt.Errorf("proto: integer overflow")
)

func init() { proto.RegisterFile("api/node/service.proto", fileDescriptor_service_2c3afb50d9ca8484) }

var fileDescriptor_service_2c3afb50d9ca8484 = []byte{
	// 917 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x96, 0xdf, 0x8f, 0xdb, 0x44,
	0x10, 0xc7, 0xeb, 0x42, 0xaf, 0xcd, 0xe4, 0xda, 0x46, 0xdb, 0xeb, 0x71, 0x76, 0xb9, 0xd4, 0xb5,
	0x0a, 0x3d, 0x4e, 0xa7, 0xb8, 0xca, 0x89, 0x5f, 0xa7, 0x0a, 0xd4, 0x26, 0xe5, 0x38, 0x41, 0xd0,
	0x91, 0x03, 0x1e, 0xa8, 0x10, 0xda, 0xd8, 0xd3, 0xdc, 0xaa, 0xc9, 0xda, 0xb5, 0x37, 0xd1, 0xe5,
	0x09, 0xde, 0x10, 0x2f, 0x7d, 0xe6, 0x01, 0xf8, 0x7b, 0x90, 0x9f, 0x10, 0x7f, 0x01, 0x3a, 0xfe,
	0x01, 0xff, 0x09, 0xc8, 0xeb, 0x8d, 0xe3, 0x24, 0x4e, 0xa2, 0x22, 0x90, 0x78, 0xf4, 0xec, 0xcc,
	0x7c, 0xbe, 0x33, 0xbb, 0xb3, 0x6b, 0xd8, 0xa4, 0x3e, 0xb3, 0xb9, 0xe7, 0xa2, 0x1d, 0x62, 0x30,
	0x64, 0x0e, 0xd6, 0xfc, 0xc0, 0x13, 0x1e, 0x81, 0x0e, 0x06, 0x62, 0x54, 0x4b, 0x56, 0x0c, 0x23,
	0xf1, 0x91, 0xe6, 0xce, 0xe0, 0xa9, 0xdd, 0x0d, 0xa8, 0x7f, 0xfa, 0xbc, 0x97, 0xfa, 0x19, 0x37,
	0xe4, 0x5a, 0xdd, 0xb7, 0x71, 0x88, 0x5c, 0x28, 0xe3, 0x06, 0x72, 0xc1, 0xc4, 0xc8, 0x76, 0x3c,
	0x2e, 0xa8, 0x33, 0xb6, 0xea, 0x13, 0xeb, 0x10, 0x83, 0x90, 0x0a, 0xe6, 0xf1, 0x99, 0x80, 0x3e,
	0x86, 0x21, 0xed, 0x2a, 0x0d, 0xd6, 0x3e, 0x5c, 0x3f, 0x66, 0xbc, 0xdb, 0xc4, 0x50, 0x30, 0x2e,
	0xdd, 0x89, 0x09, 0x65, 0x77, 0xf2, 0xb9, 0xa5, 0x99, 0xda, 0x4e, 0xa9, 0x9d, 0x37, 0x59, 0x08,
	0x37, 0x1a, 0x29, 0xb6, 0x8d, 0xcf, 0x07, 0x18, 0x8a, 0x23, 0xee, 0x0f, 0x04, 0xb1, 0xe1, 0xb2,
	0x52, 0x23, 0x83, 0xca, 0xf5, 0x9b, 0xb5, 0xb4, 0xc2, 0x94, 0x5c, 0x1b, 0xc7, 0x8c, 0xbd, 0xc8,
	0x36, 0x00, 0xe3, 0x22, 0xf0, 0xbe, 0x15, 0x78, 0x26, 0xb6, 0x2e, 0x4a, 0x50, 0x49, 0x5a, 0xbe,
	0xc0, 0x33, 0x61, 0xbd, 0xd0, 0xe0, 0x56, 0x23, 0x57, 0xc8, 0x43, 0xd7, 0x6d, 0xa5, 0xe2, 0x53,
	0xde, 0x07, 0xb0, 0x9e, 0xaf, 0x53, 0x41, 0x8d, 0x39, 0x68, 0xe6, 0xd1, 0x9e, 0xf2, 0x4f, 0xf4,
	0xaa, 0x66, 0x48, 0xf6, 0x9c, 0x5e, 0x05, 0x6b, 0x8f, 0xbd, 0xac, 0x07, 0x50, 0x79, 0x9c, 0x6c,
	0xc1, 0x89, 0x08, 0x90, 0xf6, 0x53, 0x11, 0x3b, 0xb0, 0xf6, 0x94, 0xf5, 0x04, 0x06, 0x0a, 0x5f,
	0x51, 0x39, 0xfc, 0xba, 0x5f, 0x93, 0xce, 0x6d, 0xb5, 0x6e, 0x1d, 0xc3, 0x35, 0x69, 0xf8, 0x94,
	0x8d, 0x1b, 0xb6, 0x01, 0x97, 0x7a, 0xac, 0xcf, 0xd2, 0x76, 0x5d, 0x6d, 0xa7, 0x1f, 0xb9, 0x8c,
	0x17, 0x57, 0x64, 0xfc, 0x59, 0x83, 0x6a, 0xbe, 0xbe, 0x16, 0xe5, 0xb4, 0x8b, 0x2d, 0xec, 0x77,
	0x30, 0x08, 0xff, 0x9d, 0x1e, 0x1d, 0x24, 0x3d, 0x92, 0xf9, 0xb6, 0x2e, 0x9a, 0xaf, 0xec, 0x94,
	0xeb, 0xe6, 0xe2, 0xd0, 0x14, 0xdc, 0x1e, 0x07, 0x58, 0x6b, 0xf0, 0xea, 0x57, 0x1e, 0x73, 0xeb,
	0x3f, 0x56, 0xe0, 0xf2, 0x49, 0x7a, 0xf2, 0xc9, 0x08, 0xca, 0xb9, 0x16, 0x92, 0xd7, 0x6b, 0x93,
	0x19, 0xa8, 0xcd, 0xf6, 0xd6, 0x98, 0xab, 0xdc, 0x7a, 0x2f, 0x8a, 0xf5, 0xbb, 0xcf, 0x18, 0x77,
	0x0f, 0xcc, 0x13, 0x11, 0x30, 0xde, 0xdd, 0x33, 0xf3, 0x72, 0x8f, 0x9a, 0x63, 0xfb, 0x1f, 0xb1,
	0xbe, 0x7e, 0x32, 0xe8, 0x84, 0x4e, 0xc0, 0xfc, 0x64, 0xe5, 0xbe, 0x46, 0xbe, 0xd7, 0xa0, 0x94,
	0x6d, 0x00, 0x31, 0xe6, 0xc8, 0xd9, 0xbe, 0x14, 0x70, 0x1b, 0x51, 0xac, 0xbf, 0x23, 0xb7, 0xe7,
	0xc0, 0x3c, 0xe2, 0x62, 0xcf, 0x4c, 0x35, 0x3c, 0x4a, 0xdc, 0x8e, 0xeb, 0xfe, 0x27, 0x8c, 0xbb,
	0x4b, 0x94, 0x5c, 0xfa, 0x7c, 0x80, 0xc1, 0xe8, 0xbe, 0x46, 0x5a, 0x70, 0xe5, 0x10, 0x85, 0x4c,
	0x49, 0xe6, 0x20, 0x05, 0xd8, 0xed, 0x28, 0xd6, 0x2b, 0x72, 0xea, 0x27, 0xf9, 0xee, 0x64, 0x09,
	0xc9, 0x77, 0x70, 0x6d, 0x7a, 0x0e, 0xc9, 0xed, 0x7c, 0x55, 0x05, 0x33, 0x6a, 0x14, 0x8f, 0xa4,
	0xf5, 0x76, 0x14, 0xeb, 0x6f, 0xa8, 0xb1, 0xcc, 0xa1, 0xf6, 0xcc, 0x6c, 0x1a, 0x73, 0xe5, 0x5c,
	0x69, 0x0d, 0x44, 0x7a, 0x3a, 0x4e, 0x61, 0x43, 0x65, 0x78, 0xe8, 0x38, 0xe8, 0x67, 0x32, 0x8a,
	0x29, 0x8b, 0xe0, 0x56, 0x14, 0xeb, 0x64, 0x1e, 0x3e, 0x45, 0xa2, 0x70, 0x35, 0x2b, 0xa7, 0xef,
	0x0d, 0xf1, 0x3f, 0x40, 0x0c, 0x33, 0xc4, 0x97, 0xbe, 0x4b, 0xc5, 0xcb, 0x22, 0xde, 0x8d, 0x62,
	0xfd, 0x5e, 0x51, 0x0b, 0x5d, 0x16, 0xfa, 0x3d, 0x3a, 0xfa, 0x8c, 0xf6, 0xb1, 0xb0, 0x89, 0x0d,
	0x28, 0xab, 0x1c, 0xf2, 0x60, 0x56, 0xf2, 0x5b, 0x98, 0xcc, 0xcf, 0x22, 0x60, 0x29, 0x7f, 0xb2,
	0x9e, 0x00, 0x1c, 0xa2, 0x50, 0x4b, 0x2f, 0xa9, 0xfc, 0xf6, 0xc2, 0xe6, 0xa8, 0x73, 0x26, 0x80,
	0xe4, 0xe7, 0xbc, 0x11, 0x60, 0xd2, 0x9e, 0x25, 0x97, 0x88, 0xb1, 0x64, 0xcd, 0x7a, 0x33, 0x8a,
	0xf5, 0x4d, 0x85, 0x0b, 0x13, 0xde, 0x13, 0x05, 0xfc, 0x66, 0x7a, 0x3f, 0x5a, 0x50, 0xc9, 0xc7,
	0x2d, 0x68, 0xce, 0x32, 0xd2, 0x54, 0x87, 0x7e, 0xd1, 0xa6, 0xab, 0x38, 0xe2, 0x43, 0x26, 0x90,
	0xec, 0xce, 0x4c, 0xcc, 0x92, 0xcb, 0x74, 0x29, 0xeb, 0xc3, 0x28, 0xd6, 0xed, 0xe2, 0x1b, 0xe0,
	0x8e, 0xbc, 0x1a, 0x56, 0x95, 0xfb, 0xab, 0x26, 0x5f, 0xd5, 0x2c, 0xfe, 0xf1, 0x99, 0xd3, 0x1b,
	0xb8, 0xff, 0x23, 0x81, 0x2f, 0x34, 0xd8, 0x2c, 0x7e, 0x8e, 0xc9, 0xbd, 0x45, 0x1a, 0x67, 0x9e,
	0xec, 0x82, 0x2b, 0xee, 0xfd, 0x28, 0xd6, 0xdf, 0x5a, 0x28, 0x4b, 0xbd, 0xbc, 0xc5, 0x03, 0xeb,
	0xc1, 0xf5, 0xf4, 0xcc, 0x4f, 0x9e, 0xab, 0x7f, 0x7a, 0x26, 0xef, 0x46, 0xb1, 0xfe, 0xda, 0x02,
	0x15, 0x93, 0x39, 0xf8, 0x41, 0x83, 0x9b, 0x33, 0xc4, 0xb4, 0xfd, 0x64, 0xe5, 0xab, 0x68, 0xac,
	0xf4, 0xb0, 0x76, 0xa3, 0x58, 0xdf, 0x76, 0xe6, 0xec, 0x85, 0x4a, 0xf6, 0xa1, 0xfc, 0x31, 0xe5,
	0x6e, 0x0f, 0x57, 0xbd, 0x25, 0xd9, 0xa0, 0x58, 0x17, 0x48, 0x13, 0x2a, 0x87, 0xc8, 0x31, 0xa0,
	0x02, 0x3f, 0xa2, 0xcf, 0xb0, 0x49, 0x05, 0x2d, 0x18, 0xa8, 0xf9, 0xc8, 0xf5, 0xa9, 0xae, 0x3f,
	0x80, 0x52, 0x13, 0x3b, 0x83, 0x6e, 0xf2, 0xdb, 0x48, 0x6e, 0xe5, 0x9d, 0x67, 0x7e, 0x24, 0x8b,
	0x34, 0x3c, 0xda, 0xfd, 0xed, 0xbc, 0xaa, 0xfd, 0x7e, 0x5e, 0xd5, 0xfe, 0x3c, 0xaf, 0x6a, 0x3f,
	0xfd, 0x55, 0xbd, 0xf0, 0xf5, 0x56, 0xea, 0x24, 0xd0, 0x39, 0xb5, 0x1d, 0x2f, 0x40, 0x7b, 0xfc,
	0xb7, 0xdc, 0x59, 0x93, 0xbf, 0xa8, 0xfb, 0x7f, 0x07, 0x00, 0x00, 0xff, 0xff, 0xe8, 0x57, 0xd6,
	0x49, 0x40, 0x0b, 0x00, 0x00,
}
