platform :ios, '10.0'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target 'Berty' do
  # Pods for Berty
  pod 'React', :path => '../node_modules/react-native/'
  pod 'React-Core', :path => '../node_modules/react-native/React'
  pod 'React-DevSupport', :path => '../node_modules/react-native/React'
  pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
  pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
  pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
  pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
  pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
  pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
  pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
  pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
  pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'
  pod 'React-RCTWebSocket', :path => '../node_modules/react-native/Libraries/WebSocket'
  pod 'React-RCTPushNotification', :path => '../node_modules/react-native/Libraries/PushNotificationIOS'

  pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
  pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
  pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
  pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  # @FIXME: https://github.com/avishayil/react-native-restart/issues/34
  pod 'RCTRestart', :path => '../node_modules/react-native-restart/ios'

  pod 'react-native-camera', :path => '../node_modules/react-native-camera'

  pod 'RNDevMenu', :path => '../node_modules/react-native-dev-menu'

  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'

  pod 'ReactNativeExceptionHandler', :path => '../node_modules/react-native-exception-handler'

  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

  pod 'RNLanguages', :path => '../node_modules/react-native-languages'

  pod 'react-native-network-info', :path => '../node_modules/react-native-network-info'

  pod 'ReactNativePermissions', :path => '../node_modules/react-native-permissions'

  pod 'RNSVG', :path => '../node_modules/react-native-svg'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'RNViewShot', :path => '../node_modules/react-native-view-shot'

  pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'


  pod 'lottie-ios', :path => '../node_modules/lottie-ios'

  pod 'lottie-react-native', :path => '../node_modules/lottie-react-native'



  pod 'react-native-config', :path => '../node_modules/react-native-config'




  target 'BertyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  use_native_modules!
end

target 'Berty-tvOS' do
  # Pods for Berty-tvOS

  target 'Berty-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

# @FIXME: remove this when react-native-config could be use with react-native >= 0.60
# post_install do |installer|
#     installer.pods_project.targets.each do |target|
#
#       # The following is needed to ensure the "archive" step works in XCode.
#       # It removes React & Yoga from the Pods project, as it is already included in the main project.
#       # Without this, you'd see errors when you archive like:
#       # "Multiple commands produce ... libReact.a"
#       # "Multiple commands produce ... libyoga.a"
#
#       # targets_to_ignore = %w(React yoga)
#
#       # if targets_to_ignore.include? target.name
#       #   target.remove_from_project
#       # end
#
#       if target.name == 'react-native-config'
#         phase = target.project.new(Xcodeproj::Project::Object::PBXShellScriptBuildPhase)
#         phase.shell_script = "cd ../../"\
#                              " && RNC_ROOT=./node_modules/react-native-config/"\
#                              " && export SYMROOT=$RNC_ROOT/ios/ReactNativeConfig"\
#                              " && export BUILD_DIR=$RNC_ROOT/ios/ReactNativeConfig"\
#                              " && ruby $RNC_ROOT/ios/ReactNativeConfig/BuildDotenvConfig.rb"
#
#         target.build_phases << phase
#         target.build_phases.move(phase,0)
#       end
#
#     end
#   end
