run:
  deadline: 1m
  tests: false
  skip-files:
    - ".*\\.pb\\.go"
    - ".*\\.pb\\.gw\\.go"
    - ".*\\.gen\\.go"
    - "_test\\.go"
    - "testing.go"

linters-settings:
  golint:
    min-confidence: 0
  maligned:
    suggest-new: true
  goconst:
    min-len: 5
    min-occurrences: 4
  misspell:
    locale: US
  gci:
    local-prefixes: berty.tech

linters:
  disable-all: true
  enable:
    - asciicheck
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - errcheck
    #- exhaustive    # nice to have
    - exportloopref
    - gci
    - gochecknoinits
    #- gocognit      # nice to have
    - goconst
    - goconst
    - gocritic
    #- godot         # nice to have
    #- goerr113      # nice to have
    - gofmt
    #- gofumpt       # depends on https://github.com/mvdan/gofumpt/issues/86
    - goimports
    - golint
    #- gomnd         # nice to have
    - gomodguard
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - noctx
    #- nolintlint
    - scopelint
    - sqlclosecheck
    - staticcheck
    - structcheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace
