run:
  deadline: 1m
  tests: false
  skip-files:
    - ".*\\.pb\\.go"
    - ".*\\.gen\\.go"
    - "testing.go"

linters-settings:
  golint:
    min-confidence: 0
  maligned:
    suggest-new: true
  goconst:
    min-len: 5
    min-occurrences: 4
  misspell:
    locale: US

linters:
  disable-all: true
  enable:
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    #- dupl
    - errcheck
    - gochecknoinits
    #- gocognit
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - golint
    - gosimple
    - govet
    - ineffassign
    #- interfacer
    - maligned
    - misspell
    - nakedret
    #- prealloc
    - scopelint
    - staticcheck
    - structcheck
    #- stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace
