workspace(name = "berty_go")

load("@berty_go//:repositories.bzl", "berty_go_repositories")

# fetch berty repos

berty_go_repositories()

# check bazel version

load("@build_bazel_rules_nodejs//:index.bzl", "check_bazel_version")

check_bazel_version("0.29.1")

# config go berty

load("@berty_go//:config.bzl", "berty_go_config")

berty_go_config()
