source "https://rubygems.org"

gem "cocoapods", "~> 1.11.2"

gem "rexml", "~> 3.2"
# ethon is manually updated to avoid segmentation fault crashes on the M1. See https://github.com/CocoaPods/CocoaPods/issues/10446
gem 'ethon', '>=0.13.0'
