# # This file contains the fastlane.tools configuration
# # You can find the documentation at https://docs.fastlane.tools
# #
# # For a list of all available actions, check out
# #
# #     https://docs.fastlane.tools/actions
# #
# # For a list of all available plugins, check out
# #
# #     https://docs.fastlane.tools/plugins/available-plugins
# #

# # Uncomment the line if you want fastlane to automatically update itself
# # update_fastlane

fastlane_version "2.76.1"

default_platform :ios

platform :ios do

  lane :build do |options|
    gym(
      verbose: true,
      configuration: "Debug",
      scheme: "berty",
      clean: true,
      include_symbols: true,
      export_method: "development",
    )
  end

end
