// Code generated by berty.tech/core/.scripts/generate-logger.sh

package pubsub

import "go.uber.org/zap"

func logger() *zap.Logger {
	return zap.L().Named("core.network.p2p.protocol.provider.pubsub")
}
